[package]
edition = "2021"
name    = "psy_node_store_memory"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["std", "parth_core/serialize_rkyv", "parth_core/serialize_speedy", "parth_core/serialize_postcard", "async_tokio"]
std = ["parth_core/std", "pser/std"]
parallel_rayon = ["dep:rayon"]
async_tokio = ["dep:tokio"]

[dependencies]
dashmap = { workspace = true }
crossbeam-skiplist = { workspace = true }
parking_lot = { workspace = true }
anyhow     = { workspace = true }
uuid = { workspace = true }
async-trait      = { workspace = true }
tracing = { workspace = true }
auto_impl = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
# start local packages
pser = { workspace = true }
parth_core = { workspace = true }
parth_common = { workspace = true }
# psy_core = { workspace = true }
# parth_crypto = { workspace = true }
# psy_common = { workspace = true }
psy_node_core = { workspace = true }
psy_serialize = { workspace = true }
# psy_data = { workspace = true }
rayon = { workspace = true, optional = true  }
tokio = { workspace = true, optional = true  }

[dev-dependencies]
criterion = { workspace = true }
parth_crypto = { workspace = true }
psy_data = { workspace = true }
tokio = { workspace = true}
rand = { workspace = true }

hex = { workspace = true }
hex-literal = { workspace = true }




[[bench]]
name = "main"
harness = false