pub mod prove_proxy;

use std::sync::Arc;
use std::time::Duration;
use parking_lot::{RwLock, Mutex};
use jsonrpsee::core::async_trait;
use jsonrpsee::proc_macros::rpc;
use jsonrpsee::types::{ErrorObject, ErrorObjectOwned};

use plonky2::field::goldilocks_field::GoldilocksField;
use plonky2::plonk::config::PoseidonGoldilocksConfig;
use tokio::time::timeout;
use qed_core::data::qhashout::QHashOut;
use qed_crypto::signature::zk::data::ZKPublicKeyInfo;
use qed_data::qblock::cmds::deploy_contract::QBCDeployContract;
use qedlang_core::dpn::vm::def::DPNFunctionCircuitDefinition;
use crate::session::{WalletKeyPair, WalletSession};
use crate::local::store::UserProverWorkerStore;
use crate::local::args::ContractCallArgs;
use crate::local::provider::RpcProvider;

type C = PoseidonGoldilocksConfig;
type F = GoldilocksField;
const D: usize = 2;

#[rpc(server, client, namespace = "qed")]
pub trait Rpc {
    /// local proving operation
    #[method(name = "exec_contract_call")]
    async fn exec_contract_call(
        &self,
        public_key: QHashOut<F>,
        contract_call_args: Vec<ContractCallArgs>,
    ) -> Result<String, ErrorObjectOwned>;
    #[method(name = "start_session")]
    async fn start_session(&self, public_key: QHashOut<F>) -> Result<String, ErrorObjectOwned>;
    #[method(name = "prove_contract_call")]
    async fn prove_contract_call(
        &self,
        public_key: QHashOut<F>,
        contract_call_arg: ContractCallArgs,
    ) -> Result<String, ErrorObjectOwned>;
    #[method(name = "prove_contract_calls")]
    async fn prove_contract_calls(
        &self,
        public_key: QHashOut<F>,
        contract_call_args: Vec<ContractCallArgs>,
    ) -> Result<String, ErrorObjectOwned>;
    #[method(name = "sign_and_submit")]
    async fn sign_and_submit(&self, public_key: QHashOut<F>) -> Result<String, ErrorObjectOwned>;
    #[method(name = "register_user")]
    async fn register_user(&self, private_key: QHashOut<F>) -> Result<QHashOut<F>, ErrorObjectOwned>;
    #[method(name = "add_user")]
    async fn add_user(&self, private_key: QHashOut<F>) -> Result<QHashOut<F>, ErrorObjectOwned>;
    #[method(name = "get_zk_public_key")]
    async fn get_zk_public_key(&self, private_key: QHashOut<F>) -> Result<ZKPublicKeyInfo<F>, ErrorObjectOwned>;
    #[method(name = "get_random_keypair")]
    async fn get_random_keypair(&self) -> Result<WalletKeyPair, ErrorObjectOwned>;
    #[method(name = "deploy_contract")]
    async fn deploy_contract(
        &self,
        deployer: QHashOut<F>,
        circuit_defs: Vec<DPNFunctionCircuitDefinition>,
    ) -> Result<String, ErrorObjectOwned>;
    #[method(name = "get_deploy_contract_cmd")]
    async fn get_deploy_contract_cmd(
        &self,
        deployer: QHashOut<F>,
        circuit_defs: Vec<DPNFunctionCircuitDefinition>,
    ) -> Result<QBCDeployContract<F>, ErrorObjectOwned>;
}

// RpcServer trait is generated by the #[rpc] macro above

#[derive(Clone)]
pub struct RpcServerImpl {
    wallet_session: Arc<RwLock<WalletSession>>,
}

impl RpcServerImpl {
    pub fn new(
        wallet_session: Arc<RwLock<WalletSession>>,
    ) -> Self {
        Self {
            wallet_session,
        }
    }

    pub fn rpc_provider(&self) -> RpcProvider {
        self.wallet_session.read().st_provider.clone()
    }

}

#[async_trait]
impl RpcServer for RpcServerImpl {
    async fn exec_contract_call(
        &self,
        public_key: QHashOut<F>,
        contract_call_args: Vec<ContractCallArgs>,
    ) -> Result<String, ErrorObjectOwned> {
        self.wallet_session
            .write()
            .exec_contract_call(public_key, contract_call_args)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
        Ok("exec contract call".to_string())
    }

    async fn start_session(&self, public_key: QHashOut<F>) -> Result<String, ErrorObjectOwned> {
        self.wallet_session
            .write()
            .start_session(public_key)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
        Ok("start session".to_string())
    }

    async fn prove_contract_call(
        &self,
        public_key: QHashOut<F>,
        contract_call_arg: ContractCallArgs,
    ) -> Result<String, ErrorObjectOwned> {
        self.wallet_session
            .write()
            .prove_contract_call(public_key, contract_call_arg)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
        Ok("prove contract call".to_string())
    }

    async fn prove_contract_calls(
        &self,
        public_key: QHashOut<F>,
        contract_call_args: Vec<ContractCallArgs>,
    ) -> Result<String, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        match timeout(
            Duration::from_secs(60),
            tokio::task::spawn_blocking(move || {
                wallet_session
                    .write()
                    .prove_contract_calls(public_key, contract_call_args)
            })
        ).await {
            Ok(join_result) => {
                match join_result {
                    Ok(result) => {
                        result.map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
                        Ok("prove contract calls".to_string())
                    }
                    Err(join_err) => {
                        Err(ErrorObject::owned(1, join_err.to_string(), None::<()>))
                    }
                }
            }
            Err(_timeout_err) => {
                Err(ErrorObject::owned(1, "Timeout: prove_contract_calls took longer than 60 seconds".to_string(), None::<()>))
            }
        }
    }

    async fn sign_and_submit(&self, public_key: QHashOut<F>) -> Result<String, ErrorObjectOwned> {
        self.wallet_session
            .write()
            .sign_and_submit(public_key)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
        Ok("sign and submit".to_string())
    }

    async fn register_user(&self, private_key: QHashOut<F>) -> Result<QHashOut<F>, ErrorObjectOwned> {
        self.wallet_session
            .write()
            .register_user(private_key)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn add_user(&self, private_key: QHashOut<F>) -> Result<QHashOut<F>, ErrorObjectOwned> {
        self.wallet_session
            .write()
            .add_user(private_key)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn get_zk_public_key(&self, private_key: QHashOut<F>) -> Result<ZKPublicKeyInfo<F>, ErrorObjectOwned> {
        self.wallet_session
            .read()
            .get_zk_public_key(private_key)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn get_random_keypair(&self) -> Result<WalletKeyPair, ErrorObjectOwned> {
        self.wallet_session
            .read()
            .get_random_keypair()
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn deploy_contract(
        &self,
        deployer: QHashOut<F>,
        circuit_defs: Vec<DPNFunctionCircuitDefinition>,
    ) -> Result<String, ErrorObjectOwned> {
        self.wallet_session
            .write()
            .deploy_contract(deployer, circuit_defs)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
        Ok("deploy contract".to_string())
    }

    async fn get_deploy_contract_cmd(
        &self,
        deployer: QHashOut<F>,
        circuit_defs: Vec<DPNFunctionCircuitDefinition>,
    ) -> Result<QBCDeployContract<F>, ErrorObjectOwned> {
        self.wallet_session
            .read()
            .get_deploy_contract_cmd(deployer, circuit_defs)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }
}