[package]
edition = "2021"
name    = "qed-interpreter"
version = "0.1.0"

[dependencies]
qed-ast = { workspace = true }
qed-parser = { workspace = true }
qed-sema = { workspace = true }
anyhow = { workspace = true }
strum = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
qed-common = { workspace = true }
insta = { workspace = true }
qed-fmt = { workspace = true }
qed-utils = { workspace = true }
either = { workspace = true }
hashbrown = { workspace = true }
plonky2 = { workspace = true }
indexmap = { workspace = true }
enum-as-inner = { workspace = true }
qedlang_core = { workspace = true }
qed_crypto = { workspace = true }
qed_store = { workspace = true }
qed_exec = { workspace = true }

[dev-dependencies]
kvq = { workspace = true }
qed_data = { workspace = true }
qed_core = { workspace = true }
qed_prover = { workspace = true }
qed_common_circuit = { workspace = true }
