[package]
name = "psy-precompiles"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
serde_json = { workspace = true }
psy_vm = { workspace = true }

[build-dependencies]
serde_json = { workspace = true }
anyhow = { workspace = true }
dargo = { workspace = true }
psy-package = { workspace = true }
psy-interpreter = { workspace = true }
psy_data = { workspace = true }
psy_config = { workspace = true }
minijinja = { workspace = true }

[lints]
workspace = true
