/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmrpcserver_free: (a: number, b: number) => void;
export const wasmrpcserver_new: (a: number, b: number) => [number, number, number];
export const wasmrpcserver_start_session: (a: number) => [number, number, number, number];
export const wasmrpcserver_prove_contract_call_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_prove_contract_calls_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_sign_and_submit: (a: number) => [number, number, number, number];
export const wasmrpcserver_register_user: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_add_user: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_switch_user: (a: number, b: number, c: number) => [number, number];
export const wasmrpcserver_get_zk_public_key_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_get_random_keypair_json: (a: number) => [number, number, number, number];
export const wasmrpcserver_deploy_contract_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_get_deploy_contract_cmd_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_get_sighash: (a: number, b: bigint) => [number, number, number, number];
export const wasmrpcserver_get_zk_signature_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_get_end_cap_proof_json: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_get_user_ec_input_json: (a: number) => [number, number, number, number];
export const wasmrpcserver_ping: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_get_result: (a: number, b: number, c: number) => [number, number, number, number];
export const wasm_main: () => void;
export const init_logging: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h057c9d17e6681a94: (a: number, b: number) => void;
export const closure1256_externref_shim: (a: number, b: number, c: any) => void;
export const __wbindgen_start: () => void;
