[package]
edition = "2021"
name    = "qedlang_core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_cbor = { workspace = true }
bincode      = { workspace = true }
serde_repr = { workspace = true }
plonky2 = { workspace = true }
twox-hash = { workspace = true }
hashbrown = { workspace = true }
ts-rs = { workspace = true }

k256 = { workspace = true }

psy_core = { workspace = true }
psy_data = { workspace = true }
psy_crypto = { workspace = true }
