// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractFunctionCodeDefinition } from "./ContractFunctionCodeDefinition";

export type ContractCodeDefinition = { state_tree_height: number, functions: Array<ContractFunctionCodeDefinition>, };
