// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DPNStateCmdGetOtherUserContractStateSlotSingle = { user_id: bigint, contract_id: bigint, sub_slot_index: bigint, contract_state_tree_height: number, };
