// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DPNStateCmdSetContractStateSlotSingle = { condition: bigint, sub_slot_index: bigint, value: bigint, };
