// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyCheckpointGlobalStateRoots } from "./PsyCheckpointGlobalStateRoots";
import type { PsyCheckpointLeafCompact } from "./PsyCheckpointLeafCompact";

export type PsyCheckpointLeafCompactWithStateRoots = { checkpoint_leaf: PsyCheckpointLeafCompact, global_state_roots: PsyCheckpointGlobalStateRoots, };
