// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { PsyUserLeaf } from "./PsyUserLeaf";
import type { UPSEndCapResultCompact } from "./UPSEndCapResultCompact";

export type SubmitUserEndCapNonProofCoreInput = { checkpoint_id: bigint, stats: GUTAStats, state_transition: UPSEndCapResultCompact, new_user_leaf: PsyUserLeaf, };
