[package]
edition = "2021"
name    = "qed_crypto"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
ts-rs = { workspace = true }
bincode = { workspace = true }
hex = { workspace = true }
async-trait = { workspace = true }
plonky2 = { workspace = true }
plonky2_maybe_rayon = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
itertools = { workspace = true }
kvq = { workspace = true }
qed_core = { workspace = true }



ripemd = { workspace = true }
num = { workspace = true, default-features = false }

sha2 = { workspace = true }


k256 = { workspace = true }

hashbrown = { workspace = true }
