[package]
edition = "2021"
name    = "psy-interpreter"
version = "0.1.0"

[dependencies]
psy-ast = { workspace = true }
psy-parser = { workspace = true }
psy-sema = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
psy-common = { workspace = true }
insta = { workspace = true }
psy-fmt = { workspace = true }
plonky2 = { workspace = true }
indexmap = { workspace = true }
enum-as-inner = { workspace = true }
psy_vm = { workspace = true }
psy_crypto = { workspace = true }
ariadne = { workspace = true }
tokio = { workspace = true }
psy_data = { workspace = true }
psy_core = { workspace = true }
psy_config = { workspace = true }
psy_common_circuit = { workspace = true }
psy_store = { workspace = true }

[features]
# default = ["is_sync"]
is_sync = [
    "psy_data/is_sync",
    "psy_store/is_sync",
]

[dev-dependencies]
psy_prover = { workspace = true }
psy_common_circuit = { workspace = true }
serial_test = { workspace = true }
