[package]
name = "qed_user_prover_wasm"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core QED dependencies (WASM compatible only)
qed_core = { workspace = true }
qed_crypto = { workspace = true }
qed_data = { workspace = true }
qed_common_circuit = { workspace = true }
qedlang_core = { workspace = true }
qed_prover ={ workspace = true   }
kvq = { workspace = true }

qed_store ={ workspace = true }

# kvq_store_lmdbx ={ workspace = true } // don't support lmdbx for wasm

# Plonky2 dependencies
plonky2 = { workspace = true }

# WebAssembly dependencies
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "console",
  "Worker",
  "MessageEvent",
  "MessagePort",
  "DedicatedWorkerGlobalScope",
  "WorkerGlobalScope",
  "Performance",
  "Window",
  "Document",
]}
indexed_db_futures = "0.6.4"
indexed_db_futures_macros_internal = "1.0.0"

serde_json = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }

serde-wasm-bindgen = "0.6"
async-trait = {workspace = true}

# Async runtime for WASM
wasm-bindgen-rayon = { version = "1.0", optional = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
log = "0.4"
console_error_panic_hook = { version = "0.1", optional = true }
wasm-logger = { version = "0.2", optional = true }

# Utilities
getrandom = { workspace = true }
hex = "0.4"
rand = { workspace = true }
hashbrown = { workspace = true }

reqwest = { version = "0.12", features = ["json", "stream","multipart"], default-features = false }

[features]
default = ["console_error_panic_hook", "wasm-logger"]
parallel = ["wasm-bindgen-rayon"]
console_error_panic_hook = ["dep:console_error_panic_hook"]
wasm-logger = ["dep:wasm-logger"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[dev-dependencies]
wasm-bindgen-test = "0.3"