/* tslint:disable */
/* eslint-disable */
export const init_logging: () => void;
export const main: () => void;
export const __wbg_wasmrpcserver_free: (a: number, b: number) => void;
export const wasmrpcserver_add_user: (a: number, b: number, c: number) => any;
export const wasmrpcserver_add_user_with_type: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const wasmrpcserver_claim_rewards_json: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmrpcserver_deploy_contract_json: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmrpcserver_exec_contract_call_json: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmrpcserver_exec_contract_call_with_sign_data_json: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const wasmrpcserver_get_claim_rewards_call_args_json: (a: number, b: number, c: number) => any;
export const wasmrpcserver_get_deploy_contract_cmd_json: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const wasmrpcserver_get_random_keypair_json: (a: number) => any;
export const wasmrpcserver_get_result: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_get_zk_public_key_json: (a: number, b: number, c: number) => any;
export const wasmrpcserver_new: (a: number, b: number) => any;
export const wasmrpcserver_ping: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmrpcserver_prove_contract_call_json: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmrpcserver_prove_contract_calls_json: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmrpcserver_register_user: (a: number, b: number, c: number) => any;
export const wasmrpcserver_register_user_with_type: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const wasmrpcserver_sign_and_submit: (a: number, b: number, c: number) => any;
export const wasmrpcserver_sign_and_submit_with_sign_data: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmrpcserver_start_session: (a: number, b: number, c: number) => any;
export const memory: WebAssembly.Memory;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_3: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_7: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hac89665212b2a743: (a: number, b: number) => void;
export const closure1877_externref_shim: (a: number, b: number, c: any) => void;
export const closure2286_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
