[workspace]
members = [
    "psy_vm",
    "qed_compiler/qedlang_ex",
    "qed_compiler/qedlang_macros",
    "kvq",
    "psy_core",
    "psy_crypto",
    "psy_store",
    "qed_prover",
    "psy_exec",
    "psy_data",
    "psy_common_circuit",
    "psy_network_circuit",
    "psy_node",
    "qed_user_cli",
    "qed_rollup_cli",
    "qed_dev_cli",
    "qed_rollup_utils",
    "qed_precompiles",
    "qed_compiler/qed-fmt",
    "qed_compiler/qed-lsp-server",
    "qed_compiler/qed-parser",
    "qed_compiler/qed-common",
    "qed_compiler/qed-ast",
    "qed_compiler/qed-sema",
    "qed_compiler/qed-lexer",
    "qed_compiler/qed-interpreter",
    "qed_compiler/qed_package",
    "qed_compiler/qed-dargo-cli",
    "qed_api_services",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.86"
version = "0.1.0"
homepage = "https://qedprotocol.com"
repository = "https://github.com/QEDProtocol/qedlang-rust"

[workspace.lints]

[workspace.dependencies]
colored = "2"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.4.0", features = ["hex"] }
serde_repr = "0.1.19"
hex = "0.4.3"
hex-literal = "0.4.1"
lazy_static = "1.4.0"
once_cell = "1.19.0"
twox-hash = "1.6.3"
async-recursion = "1.0"
hashbrown = "0.14.5"
anyhow = "1.0.75"
async-trait = { version = "0.1.88" }
base64 = "0.22"
bitcoin = { version = "0.31.1", features = ["serde", "rand"] }
chrono = "0.4.39"
homedir = "0.3"

rand = "0.8.5"
rand_core = "0.9"
rand_pcg = "0.9"
getrandom = { version = "0.2", features = ["js"] }
rayon = { version = "1.10.0" }
bincode = "=1.3.3"
serde_cbor = { version = "0.11.2" }

tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = [
    "std",
    "env-filter",
    "json",
    "chrono",
] }
itertools = "0.14"

bytes = "1"
byteorder = "1.5"
derive_more = { version = "2", default-features = false, features = ["full"] }
indexmap = { version = "2.9", features = ["serde"] }
parking_lot = { version = "0.12", features = ["nightly"] }
smallvec = "1.15"
thiserror = "2.0"
dashmap = "6.1"
cc = "1.2"
bindgen = "0.71"

clap = { version = "4.5.39", features = ["derive", "env"] }
k256 = { version = "0.13.2", features = [
  "arithmetic",
  "ecdsa",
  "pkcs8",
  "precomputed-tables",
  "schnorr",
  "signature",
  "std",
  "serde",
] }

sha2 = "0.10.8"
sha3 = "0.10.8"

repl-rs = "0.2.8"

num = { version = "0.4.0", default-features = false }
minijinja = { version = "2.0", features = ["serde"] }
unroll = "0.1.5"
postcard = { version = "1.0.0", default-features = false, features = ["alloc"] }

bitflags = "2.5.0"

ripemd = "0.1.3"
log = { version = "0.4.14", default-features = false }
env_logger = { version = "0.11", default-features = false }
dotenvy = "0.15.0"

tokio = { version = "1.47.0", features = ["rt", "macros", "sync"] }
tokio-util = "0.7"

futures = "0.3.0"
redis = { version = "0.30.0", default-features = false, features = [
    "acl",
    "keep-alive",
    "script",
    "tokio-comp",
    "connection-manager",
    "r2d2"
] }
bb8-redis = "0.22.0"
bb8 = "0.9"
fred = "10.0.4"

criterion = "0.5"
pprof = "0.14"
tempfile = "3.19"

miette = { version = "7.2", features = ["fancy"] }
dotenv = "0.15"

smol_str = { version = "0.3",  features = ["serde"] }
thin-vec = "0.2"
id-arena = "2.2"
unescaper = "0.1"
derivative = "2.2"

petgraph = "0.7"
rangemap = "1.4"
chalk = "0.1"
ena = "0.14"
unicode-segmentation = "1.12"

syn = { version = "2.0", features = ["full"] }
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"

# Additional common dependencies
uuid = { version = "1.0", features = ["serde", "v4", "js"] }
scylla = { version = "0.15.1" }
tikv-client = { git = "https://github.com/clint-long/client-rust", branch = "qed_node" }
http = "1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
wasm-logger = "0.2"
wasm-tracing = "2.0"
rsmq = { git = "https://github.com/QEDProtocol/rsmq-async-rs", package = "rsmq_async", features = ["break-js-comp", "sync", "tokio"], rev = "49b317094585e75dcdb619d204b6cf19010049fb" }

num-traits = "0.2"
num-bigint = { version = "0.4" }
num-integer = { version = "0.1", default-features = false }
ruint = { version = "1.12", default-features = false, features = [
  "serde",
  "num-bigint",
] }
clap_complete = "4.5"
color-eyre = "0.6"


enum-as-inner = "0.6"
strum = { version = "0.27", features = ["derive"] }

# plonky2 = { path = "../plonky2-hwa/plonky2" }
# plonky2_maybe_rayon = { path = "../plonky2-hwa/maybe_rayon" }
plonky2 = { git = "https://github.com/clint-long/plonky2-hwa", rev = "5bf6940a3ea2d27e854931787e93bb46be27ffa3" }
plonky2_maybe_rayon = { git = "https://github.com/clint-long/plonky2-hwa", rev = "5bf6940a3ea2d27e854931787e93bb46be27ffa3", default-features = false }

tracing-appender = "0.2"

blake2 = { version = "0.10", default-features = false }
blake3 = { version = "1.5", default-features = false }
tiny-keccak = { version = "2.0", features = ["sha3", "keccak"] }

lalrpop-util = { version = "0.22", features = ["lexer", "unicode"] }
lalrpop = "0.22"

walkdir = "2.5"
insta = { version = "1.40", features = ["glob"] }
home = { version = "0.5" }

tower-lsp = "0.20"
lsp-server = "0.7"
lsp-types = "0.97"

nom = "8.0"
logos = "0.15"
ariadne = { version = "0.5.0", features = ["auto-color"] }

either = "1"
llvm-sys = "191.0"
melior = { version = "0.21", features = ["ods-dialects"] }
mlir-sys = { version = "0.4" }

envy = "0.4"
regex = "1.11"
toml = "0.8"
url = "2.5"
dirs = "6.0"
semver = "1.0"
md5 = "0.7"
jsonrpsee = { version = "0.26", features = ["server", "client", "macros"] }
config = "0.15"

psy_vm = { path = "./psy_vm" }
qedlang_macros = { path = "./qed_compiler/qedlang_macros" }
psy_crypto = { path = "./psy_crypto" }
psy_exec = { path = "./psy_exec", default-features = false}
psy_store = { path = "./psy_store", default-features = false}
psy_data = { path = "./psy_data",default-features = false}
psy_core = { path = "./psy_core" }
psy_node = { path = "./psy_node" }
qed_prover = { path = "./qed_prover", default-features = false }
psy_common_circuit = { path = "./psy_common_circuit" ,default-features = false}
kvq = { path = "./kvq" }
psy_network_circuit = { path = "./psy_network_circuit" , default-features = false}
qed_rollup_utils= { path = "./qed_rollup_utils" , default-features = false}
qed_precompiles = { path = "./qed_precompiles" , default-features = false}

qed-ast = { path = "./qed_compiler/qed-ast" }
qed-fmt = { path = "./qed_compiler/qed-fmt" }
qed-lsp-server = { path = "./qed_compiler/qed-lsp-server" }
qed-parser = { path = "./qed_compiler/qed-parser" }
qed-common = { path = "./qed_compiler/qed-common" }
qed-sema = { path = "./qed_compiler/qed-sema" }
qed-lexer = { path = "./qed_compiler/qed-lexer" }
qed-interpreter = { path = "./qed_compiler/qed-interpreter" }
qed_package = { path = "./qed_compiler/qed_package" }
dargo = { path = "./qed_compiler/qed-dargo-cli" }
psy-abi = { path = "./qed_compiler/psy-abi" }
qed_api_services = { path = "./qed_api_services" }
serial_test = "3.2"

shadow-rs = "0.27.1"
bs58 = { version = "0.5.1", features = ["std", "check"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "blocking",
] }

jsonwebtoken = "9.3.1"

qed_user_cli = { path = "./qed_user_cli" }
qed-ts-type = { path = "./qed-ts-type" }

futures-util = "0.3.28"
axum = "0.8.3"
ts-rs = "10.1.0"

tower-http = { version = "0.6", features = ["full"] }
tower = { version = "0.5", features = ["full"] }
cfg-if = "1.0"
maybe-async = { version = "0.2", default-features = false }
web-sys = "0.3"
js-sys = "0.3"
serde-wasm-bindgen = "0.6"
lapin = "=2.5.0"
r2d2 = "0.8.10"
rabbitmq-stream-client = "0.8.0"
headers = { version = "0.4" }
ambassador = "0.4"
auto_impl = "1"
sodalite = "0.4.0"
secp256k1 = { version = "0.31", features = ["rand", "hashes"] }
rpassword = "7.3"
ecdsa = "0.16.0"
alloy-signer = { version = "1.0.23", default-features = false }
alloy-signer-local = { version = "1.0.23", features = ["mnemonic", "keystore"] }
alloy-primitives = { version = "1.3.1", features = [
    "getrandom",
    "rand",
    "map-fxhash",
    "map-foldhash",
] }
strum_macros = "0.27"

[profile.release]
debug = false
