[workspace]
members = [
    "qed_compiler/qed-fmt",
    "qed_compiler/qed-cli",
    "qed_compiler/qed-lsp-server",
    "qed_compiler/qed-parser",
    "qed_compiler/qed-utils",
    "qed_compiler/qed-common",
    "qed_compiler/qed-ast",
    "qed_compiler/qed-derive",
    "qed_compiler/qed-sema",
    "qed_compiler/qed-lexer",
    "qed_compiler/qed-interpreter",
    "qed_compiler/qed-dargo",
    "qed_compiler/qed-dargo-toml",
    "qed_compiler/qed-dargo-cli",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
miette = { version = "7.2", features = ["fancy"] }
thiserror = "2.0"
dotenv = "0.15"

once_cell = "1.19"
smol_str = "0.3"
thin-vec = "0.2"
smallvec = { version = "1.7", default-features = false, features = [
    "union",
    "const_new",
    "const_generics",
] }
indexmap = "2.6"
bitflags = { version = "2.0", default-features = false }
id-arena = "2.2"
unescaper = "0.1"
derivative = "2.2"
itertools = "0.14"

petgraph = "0.7"
rangemap = "1.4"
chalk = "0.1"
ena = "0.14"
unicode-segmentation = "1.12"

syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"

num-traits = "0.2"
num-bigint = { version = "0.1" }
num = { version = "0.1", default-features = false }
num-integer = { version = "0.1", default-features = false }
ruint = { version = "1.12", default-features = false, features = [
    "serde",
    "num-bigint",
] }
clap = { version = "4.4", features = ["derive", "env"] }
clap_complete = "4.5"
color-eyre = "0.6"

rayon = { version = "1.10" }

hex = "0.4"
bytes = "1.7.0"
hashbrown = "0.15"

colored = "3"

bincode = "1.3"
enum-as-inner = "0.6"
strum = { version = "0.27", features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = [
    "arbitrary_precision",
    "alloc",
] }
serde_with = { version = "3.8", default-features = false, features = [
    "macros",
    "hex",
] }
serde_repr = "0.1"

plonky2 = { git = "https://github.com/QEDProtocol/plonky2-hwa", rev = "5e8d6a22cdc12e6e1e4928da1f877fc659d0304c" }
plonky2_maybe_rayon = { git = "https://github.com/QEDProtocol/plonky2-hwa", rev = "5e8d6a22cdc12e6e1e4928da1f877fc659d0304c", default-features = false }

tracing = "0.1"
log = "0.4"
tracing-log = "0.2"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "json"] }

sha3 = { version = "0.10", default-features = false }
blake2 = { version = "0.10", default-features = false }
blake3 = { version = "1.5", default-features = false }
tiny-keccak = { version = "2.0", features = ["sha3", "keccak"] }
twox-hash = "1.6"
k256 = { version = "0.13", features = [
    "arithmetic",
    "ecdsa",
    "pkcs8",
    "precomputed-tables",
    "schnorr",
    "signature",
    "std",
    "serde",
] }

lalrpop-util = { version = "0.22", features = ["lexer", "unicode"] }
lalrpop = "0.22"

walkdir = "2.5"
insta = { version = "1.40", features = ["glob"] }
home = { version = "0.5" }

tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "io-std", "io-util"] }
tower-lsp = "0.20"
lsp-server = "0.7"
lsp-types = "0.97"
dashmap = "6.1"
env_logger = "0.11"

nom = "8.0"
logos = "0.15"
ariadne = { version = "0.5.0", features = ["auto-color"] }

either = "1"
llvm-sys = "191.0"
melior = { version = "0.21", features = ["ods-dialects"] }
mlir-sys = { version = "0.4" }

regex = "1.11"
toml = "0.8"
url = "2.5"
dirs = "6.0"
semver = "1.0"
tempfile = "3.19"
md5 = "0.7"

qedlang_core = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
qed_crypto = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
qed_exec = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
qed_store = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
qed_data = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
qed_core = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
qed_prover = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
qed_common_circuit = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
kvq = { git = "ssh://git@github.com/QEDProtocol/qedlang-rust", branch = "feat/qed-lang" }
# qedlang_core = { path = "../qedlang-rust/qedlang_core" }
# qed_crypto = { path = "../qedlang-rust/qed_crypto" }
# qed_exec = { path = "../qedlang-rust/qed_exec" }
# qed_store = { path = "../qedlang-rust/qed_store" }
# qed_data = { path = "../qedlang-rust/qed_data" }
# qed_core = { path = "../qedlang-rust/qed_core" }
# qed_prover = { path = "../qedlang-rust/qed_prover" }
# qed_common_circuit = { path = "../qedlang-rust/qed_common_circuit" }
# kvq = { path = "../qedlang-rust/kvq" }

qed-ast = { path = "./qed_compiler/qed-ast" }
qed-cli = { path = "./qed_compiler/qed-cli" }
qed-derive = { path = "./qed_compiler/qed-derive" }
qed-fmt = { path = "./qed_compiler/qed-fmt" }
qed-lsp-server = { path = "./qed_compiler/qed-lsp-server" }
qed-parser = { path = "./qed_compiler/qed-parser" }
qed-utils = { path = "./qed_compiler/qed-utils" }
qed-common = { path = "./qed_compiler/qed-common" }
qed-sema = { path = "./qed_compiler/qed-sema" }
qed-lexer = { path = "./qed_compiler/qed-lexer" }
qed-interpreter = { path = "./qed_compiler/qed-interpreter" }
qed-dargo = { path = "./qed_compiler/qed-dargo" }
qed-dargo-toml = { path = "./qed_compiler/qed-dargo-toml" }
dargo = { path = "./qed_compiler/qed-dargo-cli" }

serial_test = "3.2"
