#FROM ubuntu:24.04
FROM archlinux:latest

WORKDIR /qed-rollup

# Copy built binaries
COPY ./target/release/qed_rollup_cli /usr/local/bin/

# Copy configuration files
COPY config.json ./
COPY .env ./

# Set environment variables
ENV RUST_LOG="qed_rollup_utils=trace,tikv_client=warn,qed_store=trace,qed_user_cli=debug,qed_dev_cli=debug,qed_api_services=info,qed_rollup_cli=debug,qed_node=trace,qed_common_circuit=trace,qed_rollup_circuit=trace,qed_prover=trace,qed_data=trace,plonky2=error"
ENV TIKV_PD_ENDPOINTS="127.0.0.1:2379,127.0.0.1:2381,127.0.0.1:2383"
ENV DATABASE_URL="postgres://postgres:password@127.0.0.1:5432/postgres"

# Default command
CMD ["qed_rollup_cli", "--help"]