[package]
name = "qed-ts-type"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true


[[bin]]
name = "qed-ts-type"
path = "src/main.rs"

[dependencies]
anyhow = "1"
qed_user_cli = { path = "../qed_user_cli" }

[lints]
workspace = true
