pub const U64_SINGLETON_TABLE_OBJ_ID_CHECKPOINT_ID: u64 = 1;
pub const U64_SINGLETON_TABLE_OBJ_ID_PENDING_ID: u64 = 2;

pub const LATEST_INFO_TABLE_OBJ_ID_LATEST_L2_BLOCK_STATE: u64 = 1;
pub const LATEST_INFO_TABLE_OBJ_ID_LATEST_CHECKPOINT_TREE_ROOT: u64 = 2;

pub const CHECKPOINTED_OBJECT_TABLE_OBJ_ID_REALM_ROOT_TO_GLOBAL_USER_TREE_ROOT_MERKLE_PROOF: u64 = 1;
pub const CHECKPOINTED_OBJECT_TABLE_OBJ_ID_REALM_ROOT_TO_GLOBAL_REWARDS_TAG_TREE_ROOT_PROOF: u64 = 2;