[package]
name = "psy_services"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true


[dependencies]
psy_core = { workspace = true }

# Web framework
axum = { workspace = true, features = ["ws"] }
tower-http = { workspace = true }
tokio = { workspace = true, features = ["full"]}

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }

sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json", "macros"] }
uuid = { workspace = true, features = ["v4"] }

# Error handling
anyhow = { workspace = true }

# Time handling
chrono = { workspace = true, features = ["serde"] }

# Async & Utils
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }


clap = {workspace = true}
jsonwebtoken = {workspace = true}
dotenv = {workspace = true}

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
tokio-tungstenite = { version = "0.28", features = ["native-tls"] }
colored = {workspace = true}
futures-util = { workspace = true }
env_logger = { version = "0"}

# For TUI example
ratatui = "0.26"
crossterm = "0.27"

[lints]
workspace = true
