use qed_common::{FileId, Arena};
use qedlang_core::dpn::ops::context_trait::{ContextFelt, DPNContext};
use qed_ast::*;
use qed_lexer::{Token, Error};

grammar<'input, F, C>(
    file_content: &'input str,
    file_id: FileId,
    module_name: IdentId,
    expr_nodes: &mut Arena<ExprId, ExprNode<F>>,
    stmt_nodes: &mut Arena<StmtId, StmtNode>,
    def_nodes: &mut Arena<DefId, DefinitionNode>,
    interner: &mut Interner,
    _visibility_: Visibility,
    is_std: bool,
    is_self_std: bool,
    is_self_prelude: bool,
    is_self_primitive: bool,
    ctx: &mut C
) where F: ContextFelt + From<u32>, C: DPNContext<F>;

use super::Loc;
use std::convert::TryFrom;

ModuleItem: ModuleItemNode = {
    InlineModule => ModuleItemNode::InlineModule(<>),
    ModuleDecl => ModuleItemNode::ModuleDecl(<>),
    Definition => ModuleItemNode::Definition(def_nodes.alloc_item(<>)),
}

pub Module: ModuleNode = {
    <l:@L> <module_items: ModuleItem*> <r:@R> => ModuleNode::new(
        module_name,
        file_id,
        _visibility_,
        module_items,
        is_std,
        is_self_std,
        is_self_prelude,
        is_self_primitive,
        Span::new(file_id, l, r),
    )
}

InlineModule: ModuleNode = {
    <l:@L> <visibility:Visibility> MOD <name:Identifier> "{" <module_items: ModuleItem*> "}" <r:@R> => ModuleNode::new(
        name,
        file_id,
        visibility,
        module_items,
        is_std,
        is_self_std,
        is_self_prelude,
        is_self_primitive,
        Span::new(file_id, l, r),
    )
}

ModuleDecl: (IdentId, Visibility, Span) = {
    <l:@L> <visibility:Visibility> MOD <name:Identifier> ";" <r:@R> => {
        (name, visibility, Span::new(file_id, l, r))
    },
}

Statement: StmtNode = {
    VariableStatement,
    AssignmentStatement,
    ReturnStatement,
    WhileStatement,
    ForStatement,
    Definition => StmtNode::Definition(def_nodes.alloc_item(<>)),
    IntrinsicStatement,
    ExpressionStatement
}

ExpressionStatement: StmtNode = {
    <l:@L> <expr:Expression> ";" <r:@R> => StmtNode::Expression(expr_nodes.alloc_item(expr)),
}

IntrinsicStatement: StmtNode = {
    <l:@L> <variable:ASSERT> "(" <left: Expression> "," <message: STRING?> ","? ")" ";" <r:@R> => {
        StmtNode::Intrinsic(
            IntrinsicStmtNode::Assert {
                left: expr_nodes.alloc_item(left),
                message: message.map(|m| m.to_string()),
                span: Span::new(file_id, l, r),
            }
        )
    },
    <l:@L> <variable:ASSERT_EQ> "(" <left: Expression> "," <right: Expression> "," <message: STRING?> ","? ")" ";" <r:@R> => {
        StmtNode::Intrinsic(
            IntrinsicStmtNode::AssertEq {
                left: expr_nodes.alloc_item(left),
                right: expr_nodes.alloc_item(right),
                message: message.map(|m| m.to_string()),
                span: Span::new(file_id, l, r),
            }
        )
    },
}

Definition: DefinitionNode = {
    ImplDef => DefinitionNode::Impl(<>),
    ImplTraitDef => DefinitionNode::ImplTrait(<>),
    TraitDef => DefinitionNode::Trait(<>),
    EnumDef => DefinitionNode::Enum(<>),
    StructDef => DefinitionNode::Struct(<>),
    TypeAliasDef => <>,
    FunctionDef => <>,
    ConstDef => <>,
    UseDef => DefinitionNode::Use(<>),
}

UseDef: UseNode = {
    <l:@L> <visibility:Visibility> USE <path:UseNode> ";" <r:@R> => {
        UseNode {
            visibility,
            kind: path.0,
            target: path.2,
            segments: path.1,
            span: Span::new(file_id, l, r),
        }
    }
}

ImplDef: ImplNode = {
   <l:@L> IMPL <generic_parameters_lhs:GenericParameters> <ty:Ty> "{" <body:FunctionDef*> "}" <r:@R> => {
       // assert_eq!(generic_parameters_lhs, generic_parameters_rhs);
       ImplNode {
           generic_parameters: generic_parameters_lhs,
           ty,
           body: def_nodes.alloc_items(body),
           span: Span::new(file_id, l, r),
       }
   }
}

ImplTraitDef: ImplTraitNode = {
   <l:@L> IMPL <generic_parameters_lhs:GenericParameters> <trait_ty:Ty> FOR <ty:Ty> "{" <body:FunctionDef*> "}" <r:@R> => {
       // assert_eq!(generic_parameters_lhs, generic_parameters_rhs);
       ImplTraitNode {
           generic_parameters: generic_parameters_lhs,
           trait_ty: trait_ty,
           ty,
           body: def_nodes.alloc_items(body),
           span: Span::new(file_id, l, r),
       }
   }
}

TraitDef: TraitNode = {
   <l:@L> <visibility:Visibility> TRAIT <name:Identifier> <generic_parameters:GenericParameters> "{" <body:FunctionDef*> "}" <r:@R> => {
       TraitNode {
           generic_parameters,
           name,
           body: def_nodes.alloc_items(body),
           visibility,
           span: Span::new(file_id, l, r),
       }
   }
}

EnumDef: EnumNode = {
    <l:@L> <visibility:Visibility> ENUM <name:Identifier> <generic_parameters:GenericParameters> "{" <variants:Comma<EnumVariant>>  "}" <r:@R> => EnumNode {
        name,
        generic_parameters,
        variants,
        visibility,
        span: Span::new(file_id, l, r),
    }
}

TypeAliasDef: DefinitionNode = {
    <l:@L> <visibility:Visibility> TYPE <name:Identifier> "=" <ty:Ty> ";" <r:@R> => DefinitionNode::TypeAlias(TypeAliasNode {
        name,
        ty,
        visibility,
        span: Span::new(file_id, l, r),
    })
}

StructDef: StructNode = {
    <l:@L> <attrs:Attribute*> <visibility: Visibility> STRUCT <name:Identifier> <generic_parameters:GenericParameters> "{" <fields:Comma<FieldTypeAnnotation>> "}" <r:@R> => StructNode {
        name,
        generic_parameters,
        fields: fields.into_iter().map(|(field_name, field_type, visibility)| (field_name, (field_type, visibility))).collect(),
        attrs,
        visibility,
        span: Span::new(file_id, l, r),
    }
}

ConstDef: DefinitionNode = {
    <l:@L> <visibility:Visibility> CONST <name:Identifier> ":" <ty:ConstType> "=" <value:Expression> ";" <r:@R> => DefinitionNode::Const(ConstNode {
        name,
        ty,
        value: expr_nodes.alloc_item(value),
        visibility,
        span: Span::new(file_id, l, r),
    })
}

FunctionDef: DefinitionNode = {
    <l:@L> <attrs:Attribute*> <visibility:Visibility> <qualifier:Qualifier> FN <name:IdentifierOrNew> <generic_parameters:GenericParameters> "(" <parameters:Comma<FunctionParameter>> ")" <return_type:FunctionReturn?> <block_expr:BlockExpression> <r:@R> => DefinitionNode::Function(FunctionNode {
        name,
        parameters,
        generic_parameters,
        body: Some(expr_nodes.alloc_item(block_expr)),
        return_type,
        qualifier: {
           assert!(!qualifier.is_extern || is_std);
           qualifier
        },
        visibility,
        attrs,
        span: Span::new(file_id, l, r),
    }),
    <l:@L> <attrs:Attribute*> <visibility:Visibility> <qualifier:Qualifier> FN <name:IdentifierOrNew> <generic_parameters:GenericParameters> "(" <parameters:Comma<FunctionParameter>> ")" <return_type:FunctionReturn?> ";" <r:@R> => DefinitionNode::Function(FunctionNode {
        name,
        parameters,
        generic_parameters,
        body: None,
        return_type,
        qualifier: {
           assert!(!qualifier.is_extern || is_std);
           qualifier
        },
        visibility,
        attrs,
        span: Span::new(file_id, l, r),
    })
}

Attribute: AttrNode = {
    <l:@L> "#" "[" <name:Identifier>  <properties:AttributeProperties> "]" <r:@R> => AttrNode { name, properties, span: Span::new(file_id, l, r) }
}

AttributeProperties: Vec<IdentId> = {
    <l:@L> "(" <properties:Comma<Identifier>> ")" <r:@R> => properties,
    () => vec![]
}

Qualifier: Qualifier = {
    <l:@L> <is_const:CONST?> <is_extern:EXTERN?> <r:@R> => Qualifier {
        is_extern: is_extern.is_some(),
        is_const: is_const.is_some()
    },
}

TypeQualifier: TypeQualifier = {
    <l:@L> <is_mutable: MUT?> <r:@R> => TypeQualifier {
        is_mutable: is_mutable.is_some(),
    },
}

FunctionSignature: UncheckedType = {
    <l:@L> FN "(" <parameters:Comma<Ty>> ")" <return_type:FunctionReturn?> <r:@R> => UncheckedType::FunctionSignature(
        Box::new(FunctionSignature {parameters, return_type})
    )
}

FunctionParameter: (IdentId, TypeQualifier, UncheckedType) = {
    <l:@L> <type_qualifier: TypeQualifier> <name:IdentifierOrSelf> ":" <ty:Ty> <r:@R> => (name, type_qualifier, ty),
    <l:@L> <type_qualifier: TypeQualifier> <name:SELF> <r:@R> => {
        (IdentId::SELF, type_qualifier, UncheckedType::Basic(IdentId::TYPE_SELF))
    },
}

FunctionReturn: UncheckedType = {
    <l:@L> "->" <return_type:Ty> <r:@R> => return_type
}

EnumVariant: EnumVariant = {
    <l:@L> <name:Identifier> <r:@R> => EnumVariant::Basic(name),
    <l:@L> <name:Identifier> "(" <members:Comma<Ty>> ")" <r:@R> => EnumVariant::Tuple(name, members),
    <l:@L> <name:Identifier> "{" <fields:Comma<FieldTypeAnnotation>> "}" <r:@R> => EnumVariant::Struct(
        name,
        fields.into_iter().map(|(field_name, field_type, visibility)| (field_name, (field_type, visibility))).collect()
    )
}

TypeAnnotation: (IdentId, UncheckedType) = {
    <l:@L> <name:Identifier> ":" <ty:Ty> <r:@R> => (name, ty),
    <l:@L> <name:Identifier> <r:@R> => (name, UncheckedType::Unknown)
}

FieldTypeAnnotation: (IdentId, UncheckedType, Visibility) = {
    <l:@L> <visibility:Visibility> <name:Identifier> ":" <ty:Ty> <r:@R> => (name, ty, visibility)
}

Visibility: Visibility = {
    PUB => Visibility::Public,
    () => Visibility::Private
}

GenericParameters: Vec<IdentId> = {
    <l:@L> "<" <generic_parameters:Comma<Identifier>> ">" <r:@R> => generic_parameters,
    () => vec![]
}

BlockExpression: ExprNode<F> = {
    <l:@L> "{" <stmts:Statement*> <ret:Expression?> "}" <r:@R> => {
        ExprNode::BlockExpr(
            BlockExprNode {
                stmts: stmt_nodes.alloc_items(stmts),
                expr: ret.map(|x| expr_nodes.alloc_item(x)),
                span: Span::new(file_id, l, r),
            }
        )
    }
}

WhileStatement: StmtNode = {
    <l:@L> WHILE <predicate:Expression> <block_expr:BlockExpression> <r:@R>  => StmtNode::While(WhileNode {
        predicate: expr_nodes.alloc_item(predicate),
        body: expr_nodes.alloc_item(block_expr),
        span: Span::new(file_id, l, r),
    }),
}

MatchExpression: ExprNode<F> = {
    <l:@L> MATCH <scrutinee:Expression> "{" <arms:Comma<MatchArm>> "}" <r:@R> => ExprNode::Match(MatchNode {
        scrutinee: expr_nodes.alloc_item(scrutinee),
        arms,
        span: Span::new(file_id, l, r),
    }),
}

MatchArm: MatchArm = {
    <l:@L> <pattern:MatchPattern> "=>" <expr:Expression> <r:@R> => MatchArm {
        pattern,
        body: expr_nodes.alloc_item(expr),
        span: Span::new(file_id, l, r),
    }
}

MatchPattern: MatchPattern = {
    <l:@L> <pattern:Expression> <r:@R> => MatchPattern::Value(expr_nodes.alloc_item(pattern), Span::new(file_id, l, r)),
    <l:@L>  "_" <r:@R> =>  MatchPattern::PlaceHolder(Span::new(file_id, l, r)),

}

ForStatement: StmtNode = {
    <l:@L> FOR <variable:Identifier> IN <start:Expression> ".." <end:Expression> <block_expr:BlockExpression> <r:@R> => StmtNode::For(
        ForNode {
            variable,
            start: expr_nodes.alloc_item(start),
            end: expr_nodes.alloc_item(end),
            body: expr_nodes.alloc_item(block_expr),
            span: Span::new(file_id, l, r),
        }
    ),
}

IfExpression: ExprNode<F> = {
    <l:@L> <if_branch:IfBranch> <elseif_branches:ElseIfBranch*> <else_branch:ElseBranch?> <r:@R> => ExprNode::IfExpr(
        IfExprNode {
            if_branch,
            elseif_branches,
            else_branch,
            span: Span::new(file_id, l, r),
        }
    ),
}

IfBranch: Case = {
    <l:@L> IF <predicate:Expression> <block_expr:BlockExpression> <r:@R> => Case::new(
        expr_nodes.alloc_item(predicate),
        expr_nodes.alloc_item(block_expr),
        Span::new(file_id, l, r)
    ),
}

ElseIfBranch: Case = {
    <l:@L> ELSE IF <predicate:Expression> <block_expr:BlockExpression> <r:@R> => Case::new(
        expr_nodes.alloc_item(predicate),
        expr_nodes.alloc_item(block_expr),
        Span::new(file_id, l, r)
    ),
}

ElseBranch: ExprId = {
    <l:@L> ELSE <block_expr:BlockExpression> <r:@R> => expr_nodes.alloc_item(block_expr),
}

ReturnStatement: StmtNode = {
    <l:@L> RETURN <ret:Expression?> ";" <r:@R> => StmtNode::Return(ReturnNode{
        expr_id: ret.map(|x| expr_nodes.alloc_item(x)),
        span: Span::new(file_id, l, r),
    })
}

TupleType: UncheckedType = {
    "(" <types:Comma<Ty>> ")" => UncheckedType::Tuple(types)
}

TupleExpression: ExprNode<F> = {
    <l:@L> "(" <first:Expression> "," <rest:Comma<Expression>> ")" <r:@R> => {
        let mut elements = vec![expr_nodes.alloc_item(first)];
        elements.extend(rest.into_iter().map(|e| expr_nodes.alloc_item(e)));
        ExprNode::<F>::Tuple(TupleExprNode { elements, span: Span::new(file_id, l, r) })
    },
    //if the tuple has only one element, it should be treated as a normal expression
    "(" <expr:Expression> ")" => expr,
}

VariableStatement: StmtNode = {
    <l:@L> LET <type_qualifier: TypeQualifier> <decl:TypeAnnotation> "=" <value:Expression> ";" <r:@R>  => StmtNode::Variable(
        VariableNode {
            name: decl.0,
            ty: decl.1,
            qualifier: type_qualifier,
            value: expr_nodes.alloc_item(value),
            span: Span::new(file_id, l, r),
        }
    ),
}

AssignmentStatement: StmtNode = {
    <l:@L> <variable:Expression> "=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::Eq, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "+=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::AddAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "-=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::SubAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "*=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::MulAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "/=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::DivAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "%=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::ModAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "&=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitAndAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "|=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitOrAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "^=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitXorAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> "<<=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitShlAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    ),
    <l:@L> <variable:Expression> ">>=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitShrAssign, expr_nodes.alloc_item(value), Span::new(file_id, l, r))
    )
}


Expression: ExprNode<F> = {
    #[precedence(level="1")]
    Term,
    #[precedence(level="2")]
    <l:@L> <variable:STORAGE_READ> "(" <offset: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::Read {
                offset: expr_nodes.alloc_item(offset),
            }
        )
    },
    <l:@L> <variable:STORAGE_WRITE> "(" <offset: Expression> "," <value: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::Write {
                offset: expr_nodes.alloc_item(offset),
                value: expr_nodes.alloc_item(value),
            }
        )
    },
    <l:@L> <variable:Hash> "(" <data:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::Hash {
                data: expr_nodes.alloc_item(data),
            }
        )
    },
    <l:@L> <variable:CTX_GET_USER_ID> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetUserId
        )
    },
    <l:@L> <variable:CTX_GET_CONTRACT_ID> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetContractId
        )
    },
    <l:@L> <variable:CTX_GET_CHECKPOINT_ID> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCheckpointId
        )
    },
    <l:@L> <variable:CTX_GET_LAST_NONCE> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetLastNonce
        )
    },
    <l:@L> <variable:CTX_GET_USER_PUBLIC_KEY_HASH> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetUserPublicKeyHash
        )
    },
    <l:@L> <variable:CTX_GET_STATE_HASH_AT> "(" <slot_index: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetStateHashAt { slot_index: expr_nodes.alloc_item(slot_index) }
        )
    },
    <l:@L> <variable:CTX_GET_OTHER_CONTRACT_STATE_HASH_AT> "(" <contract_state_tree_height: Expression> "," <contract_id: Expression> "," <slot_index: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetOtherContractStateHashAt {
                contract_state_tree_height: expr_nodes.alloc_item(contract_state_tree_height),
                contract_id: expr_nodes.alloc_item(contract_id),
                slot_index: expr_nodes.alloc_item(slot_index),
            }
        )
    },
    <l:@L> <variable:CTX_GET_OTHER_USER_CONTRACT_STATE_HASH_AT> "(" <contract_state_tree_height: Expression> "," <user_id: Expression> "," <contract_id: Expression> "," <slot_index: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetOtherUserContractStateHashAt {
                contract_state_tree_height: expr_nodes.alloc_item(contract_state_tree_height),
                user_id: expr_nodes.alloc_item(user_id),
                contract_id: expr_nodes.alloc_item(contract_id),
                slot_index: expr_nodes.alloc_item(slot_index),
            }
        )
    },
    <l:@L> <variable:CTX_SET_STATE_HASH_AT> "(" <slot_index: Expression> "," <new_value: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::CSetStateHashAt {
                slot_index: expr_nodes.alloc_item(slot_index),
                new_value: expr_nodes.alloc_item(new_value),
            }
        )
    },
    <l:@L> <callee:Expression> <generic_parameters:Monomorphization> "(" <args:ArgumentList> ")" <r:@R> => {
       if let ExprNode::<F>::MemberAccess(MemberAccessNode {
          target: receiver, ..
       }) = &callee {
            ExprNode::<F>::MemberCall(
               MemberCallNode {
                   receiver: receiver.clone(),
                   callee: expr_nodes.alloc_item(callee),
                   generic_parameters,
                   args: expr_nodes.alloc_items(args),
                   span: Span::new(file_id, l, r),
               }
            )
       } else {
            ExprNode::<F>::Call(
               CallNode {
                   callee: expr_nodes.alloc_item(callee),
                   generic_parameters,
                   args: expr_nodes.alloc_items(args),
                   span: Span::new(file_id, l, r),
               }
            )
       }
    },
    <l:@L> <variable:Expression> "[" <index:Expression> "]" <r:@R> => ExprNode::<F>::IndexAccess(IndexAccessNode {
        target: expr_nodes.alloc_item(variable),
        index: expr_nodes.alloc_item(index),
        span: Span::new(file_id, l, r),
    }),
    <l:@L> <variable:Expression> "." <index:U64> <r:@R> => ExprNode::<F>::TupleAccess(TupleAccessNode {
        target: expr_nodes.alloc_item(variable),
        index: index as usize,
        span: Span::new(file_id, l, r),
    }),
    <l:@L> <variable:Expression> "." <field:Identifier> <r:@R> => ExprNode::<F>::MemberAccess(MemberAccessNode {
        target: expr_nodes.alloc_item(variable),
        field,
        span: Span::new(file_id, l, r),
    }),
    <l:@L> <lhs:Expression> AS <ty:TYPE_FELT> <r:@R> => ExprNode::<F>::Cast(
        CastNode::new(expr_nodes.alloc_item(lhs), UncheckedType::Basic(IdentId::TYPE_FELT), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> AS <ty:TYPE_BOOL> <r:@R> => ExprNode::<F>::Cast(
        CastNode::new(expr_nodes.alloc_item(lhs), UncheckedType::Basic(IdentId::TYPE_BOOL), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> AS <ty:TYPE_U32> <r:@R> => ExprNode::<F>::Cast(
        CastNode::new(expr_nodes.alloc_item(lhs), UncheckedType::Basic(IdentId::TYPE_U32), Span::new(file_id, l, r))
    ),

    #[precedence(level="4")] #[assoc(side="right")]
    <l:@L> "!" <rhs:Expression> <r:@R> => ExprNode::<F>::Unary(
        UnaryNode{operator: UnaryOperator::Not, rhs: expr_nodes.alloc_item(rhs), span: Span::new(file_id, l, r)}
    ),
    #[precedence(level="4")] #[assoc(side="right")]
    <l:@L> "-" <rhs:Expression> <r:@R> => ExprNode::<F>::Unary(
        UnaryNode{operator: UnaryOperator::Neg, rhs: expr_nodes.alloc_item(rhs), span: Span::new(file_id, l, r)}
    ),

    #[precedence(level="6")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "**" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Pow, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "*" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Mul, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "/" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Div, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "%" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Mod, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="7")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "+" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Add, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "-" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Sub, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="8")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "<<" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitShl, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> ">>" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitShr, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="9")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "&" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitAnd, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="10")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "^" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitXor, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="11")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "|" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitOr, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="12")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> ">" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Gt, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "<" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Lt, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> ">=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Gte, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "<=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Lte, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="13")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "==" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Eq, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "!=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Neq, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="14")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "&&" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::And, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="15")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "||" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Or, expr_nodes.alloc_item(rhs), Span::new(file_id, l, r))
    ),

    #[precedence(level="16")]
    LambdaFunctionExpression
}

Term: ExprNode<F> = {
    ValueExpression,
    PathExpression,
    IfExpression,
    MatchExpression,
    BlockExpression,

}

ValueExpression: ExprNode<F> = {
    FeltExpression,
    BoolExpression,
    U32Expression,
    ArrayExpression,
    TupleExpression,
    NEW <StructExpression>
}

FeltExpression: ExprNode<F> = {
    <l:@L> <n:U64> <r:@R> => ExprNode::<F>::Value(ValueNode::Felt(ctx.op_const(n), Span::new(file_id, l, r))),
}

BoolExpression: ExprNode<F> = {
    <l:@L> <b:BOOL> <r:@R> => ExprNode::<F>::Value(ValueNode::Bool(if b { ctx.op_true() } else { ctx.op_false() }, Span::new(file_id, l, r)))
}

U32Expression: ExprNode<F> = {
    <l:@L> <n:U32> <r:@R> => {
        ExprNode::<F>::Value(ValueNode::U32(ctx.op_const_u32(n), Span::new(file_id, l, r)))
    },
}

StructExpression: ExprNode<F> = {
   <l:@L> <name:Identifier> <generic_parameters:Monomorphization> "{" <kv:Comma<KeyValue>> "}" <r:@R> => ExprNode::<F>::Value(
       ValueNode::Struct(
           name,
           generic_parameters,
           kv.into_iter().collect(),
           Span::new(file_id, l, r),
       )
   ),
}

KeyValue: (IdentId, ExprId) = {
    <l:@L> <name:Identifier> ":" <value:Expression> <r:@R> => (name, expr_nodes.alloc_item(value)),
    <l:@L> <name:Identifier> <r:@R> => (name, expr_nodes.alloc_item(ExprNode::Path(PathNode::from_target(name))))
}

LambdaFunctionExpression: ExprNode<F> = {
    <l:@L> "||" <return_type:FunctionReturn?> <block_expr:BlockExpression> <r:@R> => ExprNode::<F>::LambdaFunction(
        LambdaFunctionNode {
            parameters: vec![],
            body: expr_nodes.alloc_item(block_expr),
            return_type,
            span: Span::new(file_id, l, r),
        }
    ),
    <l:@L> "|" <parameters:Comma<FunctionParameter>> "|" <return_type:FunctionReturn?> <block_expr:BlockExpression> <r:@R> => ExprNode::<F>::LambdaFunction(
        LambdaFunctionNode {
            parameters,
            body: expr_nodes.alloc_item(block_expr),
            return_type,
            span: Span::new(file_id, l, r),
        }
    )
}

PathExpression: ExprNode<F> = {
    <l:@L> <target: IdentifierOrSelf> <r:@R> => ExprNode::Path(PathNode {
        root: None,
        segments: vec![],
        target,
        span: Span::new(file_id, l, r),
    }),
    <l:@L> <root: IdentifierOrBasicType> "::" <segments: (<Identifier> "::")*> <target: IdentifierOrNew> <r:@R> => {
        let segs = segments.into_iter().map(|seg| seg).collect::<Vec<_>>();
        ExprNode::Path(PathNode {
            root: Some(root),
            segments: segs,
            target,
            span: Span::new(file_id, l, r),
        })
    },
};

ArgumentList: Vec<ExprNode<F>> = {
    <items:Sep<Expression, ",">> => items
}

ArrayExpression: ExprNode<F> = {
    <l:@L> "[" <elements:Comma<Expression>> "]" <r:@R> => ExprNode::<F>::Value(
        ValueNode::Array(elements.len(), expr_nodes.alloc_items(elements), Span::new(file_id, l, r)),
    ),
}

UseNode: (IdentId, Vec<IdentId>, Option<IdentId>) =
    <a:ModuleUseKind> "::" <h:(<Identifier> "::")*> <t:IdentifierOrAll> => {
        (a, h, t)
    };

Monomorphization: Vec<UncheckedType> = {
    <l:@L> "#" "<" <generic_parameters:Comma<Ty>> ">" <r:@R> => generic_parameters,
    () => vec![]
}

Ty: UncheckedType = {
    BasicType,
    ArrayType,
    TupleType,
    GenericType,
    FunctionSignature
}

GenericType: UncheckedType = {
    <l:@L> <name:Identifier> "<" <generic_parameters:Comma<Ty>> ">" <r:@R> => UncheckedType::Generic(name, generic_parameters),
    <l:@L>  "[" <ty:Ty> ";" <n:Identifier> "]" <r:@R> => UncheckedType::Generic(
        IdentId::TYPE_ARRAY,
        vec![ty, UncheckedType::Basic(n)]
    )
}

ArrayType: UncheckedType = {
    <l:@L> "[" <ty:Ty> ";" <n:U64> "]" <r:@R> => UncheckedType::Array(Box::new(ty), usize::try_from(n).unwrap())
}

ConstType: UncheckedType = {
    <l:@L> <ty:TYPE_FELT>  <r:@R> => UncheckedType::Basic(IdentId::TYPE_FELT),
    <l:@L> <ty:TYPE_BOOL>  <r:@R> => UncheckedType::Basic(IdentId::TYPE_BOOL),
    <l:@L> <ty:TYPE_U32>   <r:@R> => UncheckedType::Basic(IdentId::TYPE_U32),
}

BasicType: UncheckedType = {
    ConstType,
    <l:@L> <ty:TYPE_SELF>  <r:@R> => UncheckedType::Basic(IdentId::TYPE_SELF),
    <l:@L> <ty:Identifier> <r:@R> => UncheckedType::Basic(ty)
}

ModuleUseKind: IdentId = {
    <l:@L> SELF            <r:@R> => IdentId::SELF,
    <l:@L> SUPER           <r:@R> => IdentId::SUPER,
    <l:@L> CRATE           <r:@R> => IdentId::CRATE,
    <l:@L>  <k:Identifier> <r:@R> => k
}

IdentifierOrAll: Option<IdentId> = {
    Identifier => Some(<>),
    <l:@L> "*" <r:@R> => None
}

IdentifierOrSelf: IdentId = {
    Identifier,
    <l:@L> <name:SELF> <r:@R> => IdentId::SELF
}

IdentifierOrNew: IdentId = {
    Identifier,
    <l:@L> <name:NEW> <r:@R> => IdentId::NEW
}

IdentifierOrBasicType: IdentId = {
    Identifier,
    <l:@L> <ty:TYPE_FELT> <r:@R> => IdentId::TYPE_FELT,
    <l:@L> <ty:TYPE_BOOL> <r:@R> => IdentId::TYPE_BOOL,
    <l:@L> <ty:TYPE_U32> <r:@R> => IdentId::TYPE_U32,
    <l:@L> <ty:TYPE_SELF> <r:@R> => IdentId::TYPE_SELF,
}

Identifier: IdentId = {
    <l:@L> <name:IDENT> <r:@R> => interner.intern_ident(name)
}

Sep<E,S>: Vec<E> =
    <v0:(<E> S)*> <e1:E?> =>
        v0.into_iter().chain(e1).collect();

DoubleColon<E>: Vec<E> = Sep<E, "::">;
Dot<E>: Vec<E> = Sep<E, ".">;
Comma<E>: Vec<E> = Sep<E, ",">;
Plus<E>: Vec<E> = Sep<E, "+">;

extern {
    type Location = Loc;
    type Error = Error;

    enum Token<'input> {
        CONST => Token::KeywordConst,
        LET => Token::KeywordLet,

        MUT => Token::KeywordMut,

        FN => Token::KeywordFn,
        STRUCT => Token::KeywordStruct,
        ENUM => Token::KeywordEnum,
        IMPL => Token::KeywordImpl,
        TRAIT => Token::KeywordTrait,
        RETURN => Token::KeywordReturn,
        MATCH => Token::KeywordMatch,
        IF => Token::KeywordIf,
        ELSE => Token::KeywordElse,
        WHILE => Token::KeywordWhile,
        FOR => Token::KeywordFor,
        IN => Token::KeywordIn,
        WHERE => Token::KeywordWhere,

        ASSERT => Token::IntrinsicAssert,
        ASSERT_EQ => Token::IntrinsicAssertEq,
        Hash => Token::IntrinsicHash,
        STORAGE_READ => Token::IntrinsicStorageRead,
        STORAGE_WRITE => Token::IntrinsicStorageWrite,
        CTX_GET_USER_ID => Token::IntrinsicCtxGetUserId,
        CTX_GET_CONTRACT_ID => Token::IntrinsicCtxGetContractId,
        CTX_GET_CHECKPOINT_ID => Token::IntrinsicCtxGetCheckpointId,
        CTX_GET_LAST_NONCE => Token::IntrinsicCtxGetLastNonce,
        CTX_GET_USER_PUBLIC_KEY_HASH => Token::IntrinsicCtxGetUserPublicKeyHash,
        CTX_GET_STATE_HASH_AT => Token::IntrinsicCtxGetStateHashAt,
        CTX_GET_OTHER_CONTRACT_STATE_HASH_AT => Token::IntrinsicCtxGetOtherContractStateHashAt,
        CTX_GET_OTHER_USER_CONTRACT_STATE_HASH_AT => Token::IntrinsicCtxGetOtherUserContractStateHashAt,
        CTX_SET_STATE_HASH_AT => Token::IntrinsicCtxSetStateHashAt,

        MOD => Token::KeywordMod,
        USE => Token::KeywordUse,
        SUPER => Token::KeywordSuper,
        CRATE => Token::KeywordCrate,
        SELF => Token::KeywordSelf,

        PUB => Token::KeywordPub,

        IDENT => Token::Ident(<&'input str>),

        BOOL => Token::Bool(<bool>),
        U64 => Token::U64(<u64>),
        U32 => Token::U32(<u32>),
        STRING => Token::String(<&'input str>),

        TYPE_BOOL => Token::TypeBool,
        TYPE_FELT => Token::TypeFelt,
        TYPE_U32 => Token::TypeU32,
        TYPE_ARRAY => Token::TypeArray,
        TYPE_SELF => Token::TypeSelf,

        AS => Token::KeywordAs,
        TYPE => Token::KeywordType,

        EXTERN => Token::KeywordExtern,
        NEW => Token::KeywordNew,

        "#" => Token::Pound,
        "_" => Token::Placeholder,

        "(" => Token::LParen,
        ")" => Token::RParen,
        "{" => Token::LBrace,
        "}" => Token::RBrace,
        "[" => Token::LBracket,
        "]" => Token::RBracket,

        "=" => Token::Assign,
        ";" => Token::Semicolon,
        "," => Token::Comma,
        "." => Token::Dot,
        ".." => Token::DoubleDot,
        ":" => Token::Colon,
        "::" => Token::DoubleColon,
        "->" => Token::Arrow,
        "=>" => Token::FatArrow,

        "+" => Token::OperatorAdd,
        "-" => Token::OperatorSub,
        "*" => Token::OperatorMul,
        "/" => Token::OperatorDiv,
        "**" => Token::OperatorPow,
        "%" => Token::OperatorMod,

        "==" => Token::OperatorEq,
        "!=" => Token::OperatorNeq,
        "<" => Token::OperatorLt,
        "<=" => Token::OperatorLte,
        ">" => Token::OperatorGt,
        ">=" => Token::OperatorGte,
        "&&" => Token::OperatorAnd,
        "||" => Token::OperatorOr,

        "&" => Token::OperatorBitAnd,
        "|" => Token::OperatorBitOr,
        "^" => Token::OperatorBitXor,

        "<<" => Token::OperatorShl,
        ">>" => Token::OperatorShr,

        "!" => Token::OperatorNot,

        "+=" => Token::OperatorAddAssign,
        "-=" => Token::OperatorSubAssign,
        "*=" => Token::OperatorMulAssign,
        "/=" => Token::OperatorDivAssign,
        "%=" => Token::OperatorModAssign,

        "|=" => Token::OperatorBitOrAssign,
        "&=" => Token::OperatorBitAndAssign,
        "^=" => Token::OperatorBitXorAssign,

        "<<=" => Token::OperatorBitShlAssign,
        ">>=" => Token::OperatorBitShrAssign,
    }
}
