use qed_common::{FileId, Arena};
use qedlang_core::dpn::ops::context_trait::{ContextFelt, DPNContext};
use qed_ast::*;
use qed_lexer::{Token, Error};
use qed_ast::expr::block_expr::BlockExprNode;

grammar<'input, F, C>(
    file_content: &'input str,
    file_id: FileId,
    module_name: IdentId,
    expr_nodes: &mut Arena<ExprId, ExprNode<F>>,
    stmt_nodes: &mut Arena<StmtId, StmtNode>,
    def_nodes: &mut Arena<DefId, DefinitionNode>,
    interner: &mut Interner,
    _visibility_: Visibility,
    is_std: bool,
    is_self_std: bool,
    is_self_prelude: bool,
    ctx: &mut C
) where F: ContextFelt + From<u32>, C: DPNContext<F>;

use super::Loc;
use std::convert::TryFrom;
use std::collections::HashMap;

ModuleItem: ModuleItemNode = {
    InlineModule => ModuleItemNode::InlineModule(<>),
    ModuleDecl => ModuleItemNode::ModuleDecl(<>),
    ModuleUse => ModuleItemNode::ModuleUse(<>),
    Definition => ModuleItemNode::Definition(<>),
}

pub Module: ModuleNode = {
    <l:@L> <module_items: ModuleItem*> <r:@R> => {
        let mut inline_modules = vec![];
        let mut modules = vec![];
        let mut uses = vec![];
        let mut definitions = vec![];
        for item in module_items.iter() {
            match item.clone() {
                ModuleItemNode::InlineModule(m) => inline_modules.push(m),
                ModuleItemNode::ModuleDecl(m) => modules.push(m),
                ModuleItemNode::ModuleUse(m) => uses.push(m),
                ModuleItemNode::Definition(d) => definitions.push(d),
            }
        }
        ModuleNode {
            name: module_name,
            file_id,
            modules: {
                if !is_std {
                    modules.insert(0, (IdentId::STD, Visibility::Public));
                }
                modules
            },
            inline_modules: inline_modules,
            uses: {
                if !is_std  {
                    uses.insert(0, UsePath {
                        visibility: Visibility::Public,
                        kind: IdentId::STD,
                        segments: vec![IdentId::PRELUDE],
                        target: None,
                    });
                } else if !is_self_std && !is_self_prelude {
                    uses.insert(0, UsePath {
                        visibility: Visibility::Public,
                        kind: IdentId::PRELUDE,
                        segments: vec![],
                        target: None,
                    });
                }
                uses
            },
            definitions: def_nodes.alloc_items(definitions),
            visibility: _visibility_,
            is_std,
            is_self_std,
            is_self_prelude,
        }
    }
}

pub InlineModule: ModuleNode = {
    <l:@L> <visibility:Visibility> MOD <name:Identifier> "{" <module_items: ModuleItem*> "}" <r:@R> => { 
        let mut inline_modules = vec![];
        let mut modules = vec![];
        let mut uses = vec![];
        let mut definitions = vec![];
        for item in module_items.iter() {
            match item.clone() {
                ModuleItemNode::InlineModule(m) => inline_modules.push(m),
                ModuleItemNode::ModuleDecl(m) => modules.push(m),
                ModuleItemNode::ModuleUse(m) => uses.push(m),
                ModuleItemNode::Definition(d) => definitions.push(d),
            }
        }
        ModuleNode {
            name: name,
            file_id,
            modules: {
                if !is_std {
                    modules.insert(0, (IdentId::STD, Visibility::Public));
                }
                modules
            },
            inline_modules: inline_modules,
            uses: {
                if !is_std  {
                    uses.insert(0, UsePath {
                        visibility: Visibility::Public,
                        kind: IdentId::STD,
                        segments: vec![IdentId::PRELUDE],
                        target: None,
                    });
                } else if !is_self_std && !is_self_prelude {
                    uses.insert(0, UsePath {
                        visibility: Visibility::Public,
                        kind: IdentId::PRELUDE,
                        segments: vec![],
                        target: None,
                    });
                }
                uses
            },
            definitions: def_nodes.alloc_items(definitions),
            visibility: visibility,
            is_std,
            is_self_std,
            is_self_prelude,
        }
    }
}

ModuleDecl: (IdentId, Visibility) = {
    <l:@L> <visibility:Visibility> MOD <name:Identifier> ";" <r:@R> => {
        (name, visibility)
    },
}

ModuleUse: UsePath = {
    <l:@L> <visibility:Visibility> USE <path:UsePath> ";" <r:@R> => {
        assert!(visibility.is_public());
        UsePath {
            visibility,
            kind: path.0,
            target: path.2,
            segments: path.1,
        }
    }
}

Statement: StmtNode = {
    VariableStatement,
    AssignmentStatement,
    ReturnStatement,
    WhileStatement,
    BlockStatement,
    IfStatement,
    Definition => StmtNode::Definition(def_nodes.alloc_item(<>)),
    AssertStatement,
    UseStatement,
    ExpressionStatement
}

UseStatement: StmtNode = {
    ModuleUse => StmtNode::Use(<>),
}

ExpressionStatement: StmtNode = {
    <l:@L> <expr:Expression> ";" <r:@R> => StmtNode::Expression(expr_nodes.alloc_item(expr))
}

AssertStatement: StmtNode = {
    <l:@L> <variable:ASSERT> "(" <left: Expression> "," <message: STRING?>  ","? ")" ";" <r:@R> => {
        StmtNode::Assert(
            AssertNode {
                left: expr_nodes.alloc_item(left),
                message: message.map(|m| m.to_string()),
            }
        )
    },
    <l:@L> <variable:ASSERT_EQ> "(" <left: Expression> "," <right: Expression> "," <message: STRING?>  ","? ")" ";" <r:@R> => {
        StmtNode::AssertEq(
            AssertEqNode {
                left: expr_nodes.alloc_item(left),
                right: expr_nodes.alloc_item(right),
                message: message.map(|m| m.to_string()),
            }
        )
    },
}

Definition: DefinitionNode = {
    ImplDef => DefinitionNode::Impl(<>),
    TraitDef => DefinitionNode::Trait(<>),
    EnumDef => DefinitionNode::Enum(<>),
    StructDef => DefinitionNode::Struct(<>),
    FunctionDef => <>,
}

ImplDef: ImplNode = {
   <l:@L> IMPL <generic_parameters_lhs:GenericParameters> <ty:Identifier> <generic_parameters_rhs:GenericParameters> "{" <body:FunctionDef*> "}" <r:@R> => {
       assert_eq!(generic_parameters_lhs, generic_parameters_rhs);
       ImplNode {
           generic_parameters: generic_parameters_lhs,
           trait_name: None,
           ty,
           body: def_nodes.alloc_items(body)
       }
   },
   <l:@L> IMPL <generic_parameters_lhs:GenericParameters> <trait_name:Identifier> FOR <ty:IdentifierOrBasicType> <generic_parameters_rhs:GenericParameters> "{" <body:FunctionDef*> "}" <r:@R> => {
       assert_eq!(generic_parameters_lhs, generic_parameters_rhs);
       ImplNode {
           generic_parameters: generic_parameters_lhs,
           trait_name: Some(trait_name),
           ty,
           body: def_nodes.alloc_items(body)
       }
   }
}

TraitDef: TraitNode = {
   <l:@L> <visibility:Visibility> TRAIT <name:Identifier> <generic_parameters:GenericParameters> "{" <body:FunctionDef*> "}" <r:@R> => {
       TraitNode {
           generic_parameters,
           name,
           body: def_nodes.alloc_items(body),
           visibility
       }
   }
}

EnumDef: EnumNode = {
    <l:@L> <visibility:Visibility> ENUM <name:Identifier> <generic_parameters:GenericParameters> "{" <variants:Comma<EnumVariant>>  "}" <r:@R> => EnumNode {
        name,
        generic_parameters,
        variants,
        visibility
    }
}

Attribute: AttrNode = {
    <l:@L> "#" "[" <name:Identifier>  <properties:AttributeProperties> "]" <r:@R> => AttrNode { name, properties }
}

AttributeProperties: Vec<IdentId> = {
    <l:@L> "(" <properties:Comma<Identifier>> ")" <r:@R> => properties,
    () => vec![]
}

StructDef: StructNode = {
    <l:@L> <attrs:Attribute*> <visibility: Visibility> STRUCT <name:Identifier> <generic_parameters:GenericParameters> "{" <fields:Comma<FieldTypeAnnotation>> "}" <r:@R> => StructNode {
        name,
        generic_parameters,
        fields: fields.into_iter().map(|(field_name, field_type, visibility)| (field_name, (field_type, visibility))).collect(),
        attrs,
        visibility
    }
}

FunctionDef: DefinitionNode = {
    <l:@L> <attrs:Attribute*> <visibility:Visibility> <is_extern:EXTERN?> FN <name:IdentifierOrNew> <generic_parameters:GenericParameters> "(" <parameters:Comma<FunctionParameter>> ")" <return_type:FunctionReturn?> <block_stmt:BlockStatement> <r:@R> => DefinitionNode::Function(FunctionNode {
        name,
        parameters,
        generic_parameters,
        body: Some(stmt_nodes.alloc_item(block_stmt)),
        return_type,
        is_extern: {
           let is_extern = is_extern.is_some();
           assert!(!is_extern || is_std && is_self_prelude);
           is_extern
        },
        visibility,
        attrs
    }),
    <l:@L> <attrs:Attribute*> <visibility:Visibility> <is_extern:EXTERN?> FN <name:IdentifierOrNew> <generic_parameters:GenericParameters> "(" <parameters:Comma<FunctionParameter>> ")" <return_type:FunctionReturn?> ";" <r:@R> => DefinitionNode::Function(FunctionNode {
        name,
        parameters,
        generic_parameters,
        body: None,
        return_type,
        is_extern: {
           let is_extern = is_extern.is_some();
           assert!(!is_extern || is_std && is_self_prelude);
           is_extern
        },
        visibility,
        attrs
    })
}

FunctionReturn: UncheckedType = {
    <l:@L> "->" <return_type:Ty> <r:@R> => return_type
}

EnumVariant: EnumVariant = {
    <l:@L> <name:Identifier> <r:@R> => EnumVariant::Basic(name),
    <l:@L> <name:Identifier> "(" <members:Comma<Ty>> ")" <r:@R> => EnumVariant::Tuple(name, members),
    <l:@L> <name:Identifier> "{" <fields:Comma<FieldTypeAnnotation>> "}" <r:@R> => EnumVariant::Struct(name, fields.into_iter().map(|(field_name, field_type, visibility)| (field_name, (field_type, visibility))).collect())
}

FunctionParameter: (IdentId, bool, UncheckedType) = {
    <l:@L> <mutable:MUT?> <name:IdentifierOrSelf> ":" <ty:Ty> <r:@R> => (name, mutable.is_some(), ty)
}

TypeAnnotation: (IdentId, UncheckedType) = {
    <l:@L> <name:Identifier> ":" <ty:Ty> <r:@R> => (name, ty)
}

FieldTypeAnnotation: (IdentId, UncheckedType, Visibility) = {
    <l:@L> <visibility:Visibility> <name:Identifier> ":" <ty:Ty> <r:@R> => (name, ty, visibility)
}

Visibility: Visibility = {
    PUB => Visibility::Public,
    () => Visibility::Private
}

GenericParameters: Vec<IdentId> = {
    <l:@L> "<" <generic_parameters:Comma<Identifier>> ">" <r:@R> => generic_parameters,
    () => vec![]
}

BlockStatement: StmtNode = {
    <l:@L> "{" <mut stmts:Statement*> <ret:Expression> "}" <r:@R> => {
        stmts.push(StmtNode::Return(ReturnNode(Some(expr_nodes.alloc_item(ret)))));
        let (uses, normal_stmts): (Vec<StmtNode>, Vec<StmtNode>) = stmts.into_iter().partition(|stmt| {
            stmt.is_use()
        });
        StmtNode::Block(BlockNode {
            stmts: stmt_nodes.alloc_items(normal_stmts),
            uses: stmt_nodes.alloc_items(uses),
        })
    },
    <l:@L> "{" <stmts:Statement*> "}" <r:@R> => {
        let (uses, normal_stmts): (Vec<StmtNode>, Vec<StmtNode>) = stmts.into_iter().partition(|stmt| {
            stmt.is_use()
        });
        StmtNode::Block(BlockNode {
            stmts: stmt_nodes.alloc_items(normal_stmts),
            uses: stmt_nodes.alloc_items(uses),
        })
    }
}

BlockExpr: ExprNode<F> = {
    <l:@L> "{" <stmts:Statement*> <result:Expression?> "}" <r:@R> => {
        let return_expr = match result {
            None => {
                None
            }
            Some(expr) => {
                Some(expr_nodes.alloc_item(expr))
            }
        };

        ExprNode::BlockExpr(
            BlockExprNode {
                stmts: stmt_nodes.alloc_items(stmts),
                return_expr,
            }
        )
    }
}
WhileStatement: StmtNode = {
    <l:@L> WHILE <predicate:Expression> <block_stmt:BlockStatement> <r:@R>  => StmtNode::While(WhileNode {
        predicate: expr_nodes.alloc_item(predicate),
        body: stmt_nodes.alloc_item(block_stmt)
    }),
}

IfStatement: StmtNode = {
    <l:@L> <if_branch:IfBranch> <elseif_branch:ElseIfBranch*> <else_branch:ElseBranch?> <r:@R> => StmtNode::If(
        IfNode {
            if_branch,
            elseif_branch,
            else_branch
        }
    ),
}

IfBranch: Case = {
    <l:@L> IF <predicate:Expression> <block_stmt:BlockStatement> <r:@R> => Case::new(
        expr_nodes.alloc_item(predicate),
        stmt_nodes.alloc_item(block_stmt)
    ),
}

ElseIfBranch: Case = {
    <l:@L> ELSE IF <predicate:Expression> <block_stmt:BlockStatement> <r:@R> => Case::new(
        expr_nodes.alloc_item(predicate),
        stmt_nodes.alloc_item(block_stmt)
    ),
}

ElseBranch: StmtId = {
    <l:@L> ELSE <block_stmt:BlockStatement> <r:@R> => stmt_nodes.alloc_item(block_stmt),
}

ReturnStatement: StmtNode = {
    <l:@L> RETURN <ret:Expression?> ";" <r:@R> => StmtNode::Return(ReturnNode(ret.map(|x| expr_nodes.alloc_item(x))))
}

VariableStatement: StmtNode = {
    <l:@L> LET <mutable:MUT?> <decl:TypeAnnotation> "=" <value:Expression> ";" <r:@R>  => StmtNode::Variable(
        VariableNode {
            name: decl.0,
            ty: decl.1,
            mutable: mutable.is_some(),
            cnst: false,
            value: expr_nodes.alloc_item(value)
        }
    ),
    <l:@L> LET <mutable:MUT?> <decl:TypeAnnotation> "=" <block:BlockExpr> ";" <r:@R>  => StmtNode::Variable(
        {
            VariableNode {
                name: decl.0,
                ty: decl.1,
                mutable: mutable.is_some(),
                cnst: false,
                value: expr_nodes.alloc_item(block)
            }
        }
    ),

    <l:@L> CONST <decl:TypeAnnotation> "=" <value:Expression> ";" <r:@R>  => StmtNode::Variable(
        VariableNode {
            name: decl.0,
            ty: decl.1,
            mutable: false,
            cnst: true,
            value: expr_nodes.alloc_item(value)
        }
    ),
}

AssignmentStatement: StmtNode = {
    <l:@L> <variable:Expression> "=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::Eq, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "+=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::AddAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "-=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::SubAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "*=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::MulAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "/=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::DivAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "%=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::ModAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "&=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitAndAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "|=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitOrAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "^=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitXorAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> "<<=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitShlAssign, expr_nodes.alloc_item(value))
    ),
    <l:@L> <variable:Expression> ">>=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitShrAssign, expr_nodes.alloc_item(value))
    )
}


Term: ExprNode<F> = {
    <l:@L> "(" <expr:Expression> ")" <r:@R> => expr,
    ValueExpression,
    PathExpression,
}

PathExpression: ExprNode<F> = {
    <variable: IdentifierOrSelf> => ExprNode::Path(PathNode {
        root: None,
        segments: vec![],
        target: variable,
    }),
    <root: IdentifierOrBasicType> "::" <segments: (<Identifier> "::")*> <target: IdentifierOrNew> => {
        let mut segment_ids = segments.into_iter().map(|seg| seg).collect::<Vec<_>>();
        ExprNode::Path(PathNode {
            root: Some(root),
            segments: segment_ids,
            target,
        })
    },
};

ExpressionList: Vec<ExprNode<F>> = {
    <items:Sep<Expression, ",">> => items
}

Expression: ExprNode<F> = {
    #[precedence(level="1")]
    Term,

    //#[precedence(level="2")]
    //todo: Temporarily disable generic capabilities
    //<l:@L> <variable:Expression> <generic_parameters:Monomorphization> "(" <args:Comma<Expression>> ")" <r:@R> => ExprNode::<F>::Call(
    //    CallNode {
    //        receiver: if let ExprNode::<F>::MemberAccess(MemberAccessNode { value: receiver, .. }) = &variable { Some(receiver.clone()) } else { None },
    //        variable: expr_nodes.alloc_item(variable),
    //        generic_parameters,
    //        args: expr_nodes.alloc_items(args)
    //    }
    //),


    #[precedence(level="2")]
    <l:@L> <variable:Expression> "(" <args:ExpressionList> ")" <r:@R> => ExprNode::<F>::Call(
       CallNode {
           receiver: if let ExprNode::<F>::MemberAccess(MemberAccessNode { target: receiver, .. }) = &variable { Some(receiver.clone()) } else { None },
           variable: expr_nodes.alloc_item(variable),
           generic_parameters: Vec::new(),
           args: expr_nodes.alloc_items(args)
       }
    ),
    #[precedence(level="2")]
    <l:@L> <variable:Expression> "[" <index:NUMBER> "]" <r:@R> => ExprNode::<F>::IndexAccess(IndexAccessNode {
        target: expr_nodes.alloc_item(variable),
        index: usize::try_from(index).unwrap()
    }),
    #[precedence(level="2")]
    <l:@L> <variable:Expression> "." <field:Identifier> <r:@R> => ExprNode::<F>::MemberAccess(MemberAccessNode {
        target: expr_nodes.alloc_item(variable),
        field
    }),

    #[precedence(level="3")]
    <l:@L> "!" <rhs:Expression> <r:@R> => ExprNode::<F>::Unary(
        UnaryNode{operator: UnaryOperator::Not, rhs: expr_nodes.alloc_item(rhs)}
    ),
    #[precedence(level="3")]
    <l:@L> "-" <rhs:Expression> <r:@R> => ExprNode::<F>::Unary(
        UnaryNode{operator: UnaryOperator::Neg, rhs: expr_nodes.alloc_item(rhs)}
    ),

    #[precedence(level="4")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> AS <ty:TYPE_FELT> <r:@R> => ExprNode::<F>::Cast(
        CastNode::new(expr_nodes.alloc_item(lhs), UncheckedType::Basic(IdentId::TYPE_FELT))
    ),

    #[precedence(level="4")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> AS <ty:TYPE_BOOL> <r:@R> => ExprNode::<F>::Cast(
        CastNode::new(expr_nodes.alloc_item(lhs), UncheckedType::Basic(IdentId::TYPE_BOOL))
    ),

    #[precedence(level="5")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "*" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Mul, expr_nodes.alloc_item(rhs))
    ),
    #[precedence(level="5")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "/" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Div, expr_nodes.alloc_item(rhs))
    ),
    #[precedence(level="5")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "%" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Mod, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="6")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "+" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Add, expr_nodes.alloc_item(rhs))
    ),
    #[precedence(level="6")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "-" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Sub, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="7")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "<<" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitShl, expr_nodes.alloc_item(rhs))
    ),
    #[precedence(level="7")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> ">>" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitShr, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="8")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "&" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitAnd, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="9")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "^" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitXor, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="10")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "|" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitOr, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="11")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> ">" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Gt, expr_nodes.alloc_item(rhs))
    ),
    #[precedence(level="11")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "<" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Lt, expr_nodes.alloc_item(rhs))
    ),
    #[precedence(level="11")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> ">=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Gte, expr_nodes.alloc_item(rhs))
    ),
    #[precedence(level="11")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "<=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Lte, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="12")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "==" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Eq, expr_nodes.alloc_item(rhs))
    ),
    #[precedence(level="12")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "!=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Neq, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="13")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "&&" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::And, expr_nodes.alloc_item(rhs))
    ),

    #[precedence(level="14")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "||" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Or, expr_nodes.alloc_item(rhs))
    ),
}

ValueExpression: ExprNode<F> = {
    FeltExpression,
    BoolExpression,
    ArrayExpression,
    NEW <StructExpression>
}

FeltExpression: ExprNode<F> = {
    <l:@L> <n:NUMBER> <r:@R> => ExprNode::<F>::Value(ValueNode::Felt(ctx.op_const(n))),
}

BoolExpression: ExprNode<F> = {
    <l:@L> <b:BOOL> <r:@R> => ExprNode::<F>::Value(ValueNode::Bool(if b { ctx.op_true() } else { ctx.op_false() }))
}


//todo: Temporarily disable generic capabilities
//StructExpression: ExprNode<F> = {
//    <l:@L> <name:Identifier> <generic_parameters:Monomorphization> "{" <kv:Comma<KeyValue>> "}" <r:@R> => ExprNode::<F>::Value(ValueNode::Struct(
//        name,
//        generic_parameters,
//        kv.into_iter().collect()
//    )),
//}

StructExpression: ExprNode<F> = {
    <l:@L> <name:Identifier>  "{" <kv:Comma<KeyValue>> "}" <r:@R> => ExprNode::<F>::Value(ValueNode::Struct(
        name,
        Vec::new(),
        kv.into_iter().collect()
    )),
}

KeyValue: (IdentId, ExprId) = {
    <l:@L> <name:Identifier> ":" <value:Expression> <r:@R> => (name, expr_nodes.alloc_item(value))
}

ArrayExpression: ExprNode<F> = {
    <l:@L> "[" <elements:Comma<Expression>> "]" <r:@R> => ExprNode::<F>::Value(
        ValueNode::Array(elements.len(), expr_nodes.alloc_items(elements))
    ),
}

UsePath: (IdentId, Vec<IdentId>, Option<IdentId>) =
    <a:ModuleUseKind> "::" <h:(<Identifier> "::")*> <t:IdentifierOrAll> => {
        (a, h, t)
    };

Monomorphization: Vec<UncheckedType> = {
    <l:@L> "::" "<" <generic_parameters:Comma<Ty>> ">" <r:@R> => generic_parameters,
    () => vec![]
}

Ty: UncheckedType = {
    BasicType,
    ArrayType,
    GenericType
}

GenericType: UncheckedType = {
    <l:@L> <name:Identifier> "<" <generic_parameters:Comma<Ty>> ">" <r:@R> => UncheckedType::Generic(name, generic_parameters)
}

ArrayType: UncheckedType = {
    <l:@L> "[" <ty:Ty> ";" <n:NUMBER> "]" <r:@R> => UncheckedType::Array(Box::new(ty), usize::try_from(n).unwrap())
}

BasicType: UncheckedType = {
    <l:@L> <ty:TYPE_FELT>  <r:@R> => UncheckedType::Basic(IdentId::TYPE_FELT),
    <l:@L> <ty:TYPE_BOOL>  <r:@R> => UncheckedType::Basic(IdentId::TYPE_BOOL),
    <l:@L> <ty:TYPE_SELF>  <r:@R> => UncheckedType::Basic(IdentId::TYPE_SELF),
    <l:@L> <ty:Identifier> <r:@R> => UncheckedType::Basic(ty)
}

ModuleUseKind: IdentId = {
    <l:@L> SELF            <r:@R> => IdentId::SELF,
    <l:@L> SUPER           <r:@R> => IdentId::SUPER,
    <l:@L> CRATE           <r:@R> => IdentId::CRATE,
    <l:@L>  <k:Identifier> <r:@R> => k
}

IdentifierOrAll: Option<IdentId> = {
    Identifier => Some(<>),
    <l:@L> "*" <r:@R> => None
}

IdentifierOrSelf: IdentId = {
    Identifier,
    <l:@L> <name:SELF> <r:@R> => IdentId::SELF
}

IdentifierOrNew: IdentId = {
    Identifier,
    <l:@L> <name:NEW> <r:@R> => IdentId::NEW
}

IdentifierOrBasicType: IdentId = {
    Identifier,
    <l:@L> <ty:TYPE_FELT> <r:@R> => IdentId::TYPE_FELT,
    <l:@L> <ty:TYPE_BOOL> <r:@R> => IdentId::TYPE_BOOL,
    <l:@L> <ty:TYPE_SELF> <r:@R> => IdentId::TYPE_SELF,
}

Identifier: IdentId = {
    <l:@L> <name:IDENT> <r:@R> => interner.intern_ident(name)
}

Sep<E,S>: Vec<E> =
    <v0:(<E> S)*> <e1:E?> =>
        v0.into_iter().chain(e1).collect();

DoubleColon<E>: Vec<E> = Sep<E, "::">;
Dot<E>: Vec<E> = Sep<E, ".">;
Comma<E>: Vec<E> = Sep<E, ",">;
Plus<E>: Vec<E> = Sep<E, "+">;

extern {
    type Location = Loc;
    type Error = Error;

    enum Token<'input> {
        CONST => Token::KeywordConst,
        LET => Token::KeywordLet,

        MUT => Token::KeywordMut,

        FN => Token::KeywordFn,
        STRUCT => Token::KeywordStruct,
        ENUM => Token::KeywordEnum,
        IMPL => Token::KeywordImpl,
        TRAIT => Token::KeywordTrait,
        RETURN => Token::KeywordReturn,
        IF => Token::KeywordIf,
        ELSE => Token::KeywordElse,
        WHILE => Token::KeywordWhile,
        FOR => Token::KeywordFor,
        WHERE => Token::KeywordWhere,

        ASSERT => Token::KeywordAssert,
        ASSERT_EQ => Token::KeywordAssertEq,

        MOD => Token::KeywordMod,
        USE => Token::KeywordUse,
        SUPER => Token::KeywordSuper,
        CRATE => Token::KeywordCrate,
        SELF => Token::KeywordSelf,

        PUB => Token::KeywordPub,

        IDENT => Token::Ident(<&'input str>),

        BOOL => Token::Bool(<bool>),
        NUMBER => Token::Number(<u64>),
        STRING => Token::String(<&'input str>),

        TYPE_BOOL => Token::TypeBool,
        TYPE_FELT => Token::TypeFelt,
        TYPE_SELF => Token::TypeSelf,

        AS => Token::KeywordAs,
        EXTERN => Token::KeywordExtern,
        NEW => Token::KeywordNew,

        "#" => Token::Pound,

        "(" => Token::LParen,
        ")" => Token::RParen,
        "{" => Token::LBrace,
        "}" => Token::RBrace,
        "[" => Token::LBracket,
        "]" => Token::RBracket,

        "=" => Token::Assign,
        ";" => Token::Semicolon,
        "," => Token::Comma,
        "." => Token::Dot,
        ":" => Token::Colon,
        "::" => Token::DoubleColon,
        "->" => Token::Arrow,

        "+" => Token::OperatorAdd,
        "-" => Token::OperatorSub,
        "*" => Token::OperatorMul,
        "/" => Token::OperatorDiv,
        "%" => Token::OperatorMod,

        "==" => Token::OperatorEq,
        "!=" => Token::OperatorNeq,
        "<" => Token::OperatorLt,
        "<=" => Token::OperatorLte,
        ">" => Token::OperatorGt,
        ">=" => Token::OperatorGte,
        "&&" => Token::OperatorAnd,
        "||" => Token::OperatorOr,

        "&" => Token::OperatorBitAnd,
        "|" => Token::OperatorBitOr,
        "^" => Token::OperatorBitXor,

        "<<" => Token::OperatorShl,
        ">>" => Token::OperatorShr,

        "!" => Token::OperatorNot,

        "+=" => Token::OperatorAddAssign,
        "-=" => Token::OperatorSubAssign,
        "*=" => Token::OperatorMulAssign,
        "/=" => Token::OperatorDivAssign,
        "%=" => Token::OperatorModAssign,

        "|=" => Token::OperatorBitOrAssign,
        "&=" => Token::OperatorBitAndAssign,
        "^=" => Token::OperatorBitXorAssign,

        "<<=" => Token::OperatorBitShlAssign,
        ">>=" => Token::OperatorBitShrAssign,
    }
}
