// AUTOGENERATED - DO NOT MODIFY
use plonky2::plonk::config::{AlgebraicHasher, GenericConfig};
use qed_common_circuit::circuits::lookalikes::{
    get_agg_state_transition_type_d_common_data, get_end_cap_type_e_common_data,
    get_guta_type_c_common_data,
};
use qed_crypto::common::generic_circuit_verifier::{
    GenericCircuitCommonDataLibrary, SerializedGenericCircuitCommonDataLibraryInfo,
};

pub fn get_cached_common_data_library<C: GenericConfig<D>, const D: usize>(
) -> GenericCircuitCommonDataLibrary<C, D>
where
    C::Hasher: AlgebraicHasher<C::F>,
{
    let serialized_library =
        serde_json::from_str::<SerializedGenericCircuitCommonDataLibraryInfo>(
            r#"{"common_data_hashes":["acd2052c5f2d49c2a931d3c8545876e51ce9c42ca1f7713d46cdac5e2e0f7f19","70724c5b671675652c93e738c2ec3296b6366994fae960f747f03c2156720c11","7ea492b556ffc919706ac50511cadc6c6b3b38afe4810c7b5ef3320652b50f0e"],"common_circuit_list":[[8,13,14,11,10,15,226,9,7,12],[0,1,32,19,48,54,227,18],[228,6]]}"#
        ).unwrap();

    GenericCircuitCommonDataLibrary::<C, D>::from_serialized(
        &serialized_library,
        vec![
            get_guta_type_c_common_data::<C, D>(),
            get_agg_state_transition_type_d_common_data::<C, D>(),
            get_end_cap_type_e_common_data::<C, D>(),
        ],
    )
    .unwrap()
}
