pub mod prove_proxy;

use std::{sync::Arc, time::Duration};

use jsonrpsee::{
    core::async_trait,
    proc_macros::rpc,
    types::{ErrorObject, ErrorObjectOwned},
};
use parking_lot::{Mutex, RwLock};
use plonky2::{field::goldilocks_field::GoldilocksField, plonk::config::PoseidonGoldilocksConfig};
use psy_common::{
    args::{ContractCallArgs, ContractCallData},
    data::qhashout::QHashOut,
};
use psy_crypto::signature::zk::data::ZKPublicKeyInfo;
use psy_data::qblock::cmds::deploy_contract::QBCDeployContract;
use psy_provider::provider::RpcProvider;
use psy_vm::dpn::vm::def::DPNFunctionCircuitDefinition;
use tokio::time::timeout;

use crate::{
    local::store::UserProverWorkerStore,
    session::{WalletKeyPair, WalletSession},
};

type C = PoseidonGoldilocksConfig;
type F = GoldilocksField;
const D: usize = 2;

#[rpc(server, client, namespace = "psy")]
pub trait Rpc {
    /// local proving operation
    #[method(name = "exec_contract_call")]
    async fn exec_contract_call(&self, public_key: QHashOut<F>, contract_call_args: Vec<ContractCallArgs>) -> Result<String, ErrorObjectOwned>;
    #[method(name = "start_session")]
    async fn start_session(&self, public_key: QHashOut<F>) -> Result<String, ErrorObjectOwned>;
    #[method(name = "prove_contract_calls")]
    async fn prove_contract_call(&self, public_key: QHashOut<F>, contract_call_args: Vec<ContractCallArgs>) -> Result<String, ErrorObjectOwned>;
    #[method(name = "sign_and_submit")]
    async fn sign_and_submit(&self, public_key: QHashOut<F>) -> Result<String, ErrorObjectOwned>;
    #[method(name = "register_user")]
    async fn register_user(&self, private_key: QHashOut<F>, fingerprint: QHashOut<F>) -> Result<QHashOut<F>, ErrorObjectOwned>;
    #[method(name = "add_user")]
    async fn add_user(&self, private_key: QHashOut<F>, fingerprint: QHashOut<F>) -> Result<QHashOut<F>, ErrorObjectOwned>;
    #[method(name = "get_zk_public_key")]
    async fn get_zk_public_key(&self, private_key: QHashOut<F>) -> Result<ZKPublicKeyInfo<F>, ErrorObjectOwned>;
    #[method(name = "get_random_keypair")]
    async fn get_random_keypair(&self) -> Result<WalletKeyPair, ErrorObjectOwned>;
    #[method(name = "deploy_contract")]
    async fn deploy_contract(&self, deployer: QHashOut<F>, circuit_defs: Vec<DPNFunctionCircuitDefinition>) -> Result<String, ErrorObjectOwned>;
    #[method(name = "get_deploy_contract_cmd")]
    async fn get_deploy_contract_cmd(
        &self,
        deployer: QHashOut<F>,
        circuit_defs: Vec<DPNFunctionCircuitDefinition>,
    ) -> Result<QBCDeployContract<F>, ErrorObjectOwned>;
}

// RpcServer trait is generated by the #[rpc] macro above

#[derive(Clone)]
pub struct RpcServerImpl {
    wallet_session: Arc<RwLock<WalletSession>>,
}

impl RpcServerImpl {
    pub fn new(wallet_session: Arc<RwLock<WalletSession>>) -> Self {
        Self { wallet_session }
    }

    pub fn rpc_provider(&self) -> RpcProvider {
        self.wallet_session.read().st_provider.clone()
    }
}

#[async_trait]
impl RpcServer for RpcServerImpl {
    async fn exec_contract_call(&self, public_key: QHashOut<F>, contract_call_args: Vec<ContractCallArgs>) -> Result<String, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        tokio::task::spawn_blocking(move || {
            tokio::runtime::Handle::current().block_on(async move {
                wallet_session
                    .read()
                    .exec_contract_call(public_key, ContractCallData::new(contract_call_args))
                    .await
            })
        })
        .await
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
        Ok("exec contract call".to_string())
    }

    async fn start_session(&self, public_key: QHashOut<F>) -> Result<String, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        tokio::task::spawn_blocking(move || {
            tokio::runtime::Handle::current().block_on(async move { wallet_session.read().start_session(public_key).await })
        })
        .await
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
        Ok("start session".to_string())
    }

    async fn prove_contract_call(&self, public_key: QHashOut<F>, contract_call_args: Vec<ContractCallArgs>) -> Result<String, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        match timeout(
            Duration::from_secs(60),
            tokio::task::spawn_blocking(move || {
                tokio::runtime::Handle::current()
                    .block_on(async move { wallet_session.read().prove_contract_call(public_key, contract_call_args).await })
            }),
        )
        .await
        {
            Ok(join_result) => match join_result {
                Ok(result) => {
                    result.map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
                    Ok("prove contract calls".to_string())
                }
                Err(join_err) => Err(ErrorObject::owned(1, join_err.to_string(), None::<()>)),
            },
            Err(_) => Err(ErrorObject::owned(
                1,
                "Timeout: prove_contract_calls took longer than 60 seconds".to_string(),
                None::<()>,
            )),
        }
    }

    async fn sign_and_submit(&self, public_key: QHashOut<F>) -> Result<String, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        let hash = tokio::task::spawn_blocking(move || {
            tokio::runtime::Handle::current().block_on(async move { wallet_session.read().sign_and_submit(public_key, None).await })
        })
        .await
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?;
        Ok(hash.to_string())
    }

    async fn register_user(&self, private_key: QHashOut<F>, fingerprint: QHashOut<F>) -> Result<QHashOut<F>, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        tokio::task::spawn_blocking(move || {
            tokio::runtime::Handle::current().block_on(async move { wallet_session.write().register_user(private_key, fingerprint).await })
        })
        .await
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn add_user(&self, private_key: QHashOut<F>, fingerprint: QHashOut<F>) -> Result<QHashOut<F>, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        tokio::task::spawn_blocking(move || {
            tokio::runtime::Handle::current().block_on(async move { wallet_session.write().add_user(private_key, fingerprint).await })
        })
        .await
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn get_zk_public_key(&self, private_key: QHashOut<F>) -> Result<ZKPublicKeyInfo<F>, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        tokio::task::spawn_blocking(move || {
            tokio::runtime::Handle::current().block_on(async move { wallet_session.read().get_zk_public_key(private_key).await })
        })
        .await
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn get_random_keypair(&self) -> Result<WalletKeyPair, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        tokio::task::spawn_blocking(move || {
            tokio::runtime::Handle::current().block_on(async move { wallet_session.read().get_random_keypair().await })
        })
        .await
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn deploy_contract(&self, deployer: QHashOut<F>, circuit_defs: Vec<DPNFunctionCircuitDefinition>) -> Result<String, ErrorObjectOwned> {
        let wallet_session = self.wallet_session.clone();
        tokio::task::spawn_blocking(move || {
            tokio::runtime::Handle::current().block_on(async move { wallet_session.read().deploy_contract(deployer, circuit_defs).await })
        })
        .await
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))?
        .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }

    async fn get_deploy_contract_cmd(
        &self,
        deployer: QHashOut<F>,
        circuit_defs: Vec<DPNFunctionCircuitDefinition>,
    ) -> Result<QBCDeployContract<F>, ErrorObjectOwned> {
        self.wallet_session
            .read()
            .get_deploy_contract_cmd(deployer, circuit_defs)
            .map_err(|e| ErrorObject::owned(1, e.to_string(), None::<()>))
    }
}
