[package]
edition = "2021"
name    = "qed_prover"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
maybe-async = { workspace = true }
async-trait = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with = { workspace = true }
plonky2 = { workspace = true }
tracing = { workspace = true }
serde_cbor = { workspace = true}
clap = { workspace = true }
ts-rs = { workspace = true }
dashmap = { workspace = true }

kvq = { workspace = true }
qed_core = { workspace = true }
qed_common_circuit = { workspace = true, default-features = false }
qed_rollup_circuit = { workspace = true, default-features = false }
qed_rollup_utils = { workspace = true }
qedlang_core = { workspace = true }
qed_data = { workspace = true, default-features = false }
qed_crypto = { workspace = true }
qed_exec = { workspace = true, default-features = false }
qed_store = { workspace = true, default-features = false }
qedlang_macros = { workspace = true }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
wasm-logger = { workspace = true }
wasm-tracing = { workspace = true }
cfg-if = {workspace = true}
web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen-futures = { workspace = true }
serde-wasm-bindgen = { workspace = true }

k256 = { workspace = true }

rand = { workspace = true }
getrandom = { workspace = true }
thiserror = { workspace = true }

rpassword = { workspace = true }
# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
jsonrpsee = { workspace = true }
reqwest = { workspace = true }
sodalite = { workspace = true }
secp256k1 = { workspace = true }
hex = {workspace = true}
bincode = { workspace = true }
dirs = {workspace = true}
# WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }

[features]
default = ["is_sync"]
is_sync = [
    "qed_data/is_sync",
    "maybe-async/is_sync",
    "qed_exec/is_sync",
    "qed_store/is_sync",
    "qed_common_circuit/is_sync", 
    "qed_rollup_circuit/is_sync",
]