// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type AltVerifierOnlyCircuitData = { constants_sigmas_cap: Array<QHashOut>, circuit_digest: QHashOut, };
