// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DPNStateCmdGetSelfUserExternalContractStateSlotRange = { contract_id: bigint, sub_slot_index: bigint, length: number, contract_state_tree_height: number, };
