// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GUTAStats = { guta_fees_collected: bigint, da_fees_collected: bigint, user_ops_processed: bigint, total_transactions: bigint, slots_modified: bigint, };
