// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PsyBlockState = { checkpoint_id: bigint, next_add_withdrawal_id: bigint, next_process_withdrawal_id: bigint, next_deposit_id: bigint, total_deposits_claimed_epoch: bigint, next_user_id: bigint, end_balance: bigint, next_contract_id: number, };
