// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QBCDeployContract } from "./QBCDeployContract";
import type { QHashOut } from "./QHashOut";

export type QBCDeployContractV2 = { deploy_contract: QBCDeployContract, layout_protocol_version: number, state_layout_root: QHashOut, state_layout_field_count: bigint, state_layout_slot_count: bigint, canonical_layout_verifier_fingerprint: QHashOut, canonical_layout_proof: Array<number>, };
