// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QBCDeployContractV2 } from "./QBCDeployContractV2";

export type QDeployContractRPCRequest = { deploy_contract: QBCDeployContractV2, };
