// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QEDCheckpointGlobalStateRoots } from "./QEDCheckpointGlobalStateRoots";
import type { QEDCheckpointLeafCompact } from "./QEDCheckpointLeafCompact";

export type QEDCheckpointLeafCompactWithStateRoots = { checkpoint_leaf: QEDCheckpointLeafCompact, global_state_roots: QEDCheckpointGlobalStateRoots, };
