// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyCheckpointLeafStats } from "./PsyCheckpointLeafStats";
import type { QHashOut } from "./QHashOut";

export type PsyCheckpointLeaf = { global_chain_root: QHashOut, stats: PsyCheckpointLeafStats, };
