// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QUserContractStateTreeLeafHashRPCRequest = { checkpoint_id: bigint, user_id: bigint, contract_id: number, leaf_id: bigint, };
