// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyContractStateUpdateHistory } from "./PsyContractStateUpdateHistory";
import type { SubmitUserEndCapNonProofCoreInput } from "./SubmitUserEndCapNonProofCoreInput";

export type SubmitUserEndCapNonProofInput = { core: SubmitUserEndCapNonProofCoreInput, contract_state_updates: Array<PsyContractStateUpdateHistory>, };
