[package]
edition = "2021"
name    = "parth_core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["rand", "std", "parth_node", "ptypes_goldilocks_qhashout", "serialize_bytemuck", "serialize_rkyv", "serialize_speedy"]
std = ["psy_io/std"]
proof_hasher_plonky2_goldilocks = ["ptypes_goldilocks_qhashout"]
ptypes_goldilocks_qhashout = ["goldilocks"]
goldilocks = ["plonky2"]
ptypes_u64_hash256 = []
rand = ["dep:rand"]
parth_node = []
serialize_rkyv = ["dep:rkyv", "plonky2?/serialize_rkyv"]
serialize_speedy = ["dep:speedy", "plonky2?/serialize_speedy"]
serialize_postcard = ["dep:postcard"]
serialize_bytemuck = ["dep:bytemuck", "plonky2/serialize_bytemuck", "psy_serialize/serialize_bytemuck"]

[dependencies]
anyhow     = { workspace = true }
const_format = { workspace = true }
num-traits = { workspace = true }
async-trait      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
bincode = { workspace = true }
auto_impl = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
ts-rs = { workspace = true }
psy_io = { workspace = true }


rand = { workspace = true, optional = true }
postcard = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
plonky2 = { workspace = true, optional = true }

# start local packages
pser = { workspace = true }
psy_serialize = { workspace = true }
pderive = { workspace = true }
cf_utils = { workspace = true }


[dev-dependencies]
plonky2 = { workspace = true }
ts-rs = { workspace = true }
criterion = { workspace = true }
paste = { workspace = true }
rayon = { workspace = true }
dashmap = { workspace = true }



[[bench]]
name = "main"
harness = false
