import { ProvingJobCircuitType } from "./id";

const CityJobNames: Record<ProvingJobCircuitType, string> = {
  [ProvingJobCircuitType.RegisterUser]: "Register User",
  [ProvingJobCircuitType.RegisterUserAggregate]: "Register User Aggregate",
  [ProvingJobCircuitType.AddL1Deposit]: "Add L1 Deposit",
  [ProvingJobCircuitType.AddL1DepositAggregate]: "Add L1 Deposit Aggregate",
  [ProvingJobCircuitType.ClaimL1Deposit]: "Claim L1 Deposit",
  [ProvingJobCircuitType.ClaimL1DepositAggregate]: "Claim L1 Deposit Aggregate",
  [ProvingJobCircuitType.TransferTokensL2]: "Transfer Tokens L2",
  [ProvingJobCircuitType.TransferTokensL2Aggregate]: "Transfer Tokens L2 Aggregate",
  [ProvingJobCircuitType.AddL1Withdrawal]: "Add L1 Withdrawal",
  [ProvingJobCircuitType.AddL1WithdrawalAggregate]: "Add L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.ProcessL1Withdrawal]: "Process L1 Withdrawal",
  [ProvingJobCircuitType.ProcessL1WithdrawalAggregate]: "Process L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.GenerateRollupStateTransitionProof]: "Generate Rollup State Transition Proof",
  [ProvingJobCircuitType.GenerateSigHashIntrospectionProof]: "Generate SigHash Introspection Proof",
  [ProvingJobCircuitType.GenerateFinalSigHashProof]: "Generate Final SigHash Proof",
  [ProvingJobCircuitType.GenerateFinalSigHashProofGroth16]: "Generate Final SigHash Proof Groth16",
  [ProvingJobCircuitType.WrapFinalSigHashProofBLS12381]: "Wrap Final SigHash Proof BLS12381",
  [ProvingJobCircuitType.AggUserRegisterClaimDepositL2Transfer]: "Agg User Register Claim Deposit L2 Transfer",
  [ProvingJobCircuitType.AggAddProcessL1WithdrawalAddL1Deposit]: "Agg Add Process L1 Withdrawal Add L1 Deposit",
  [ProvingJobCircuitType.DummyRegisterUserAggregate]: "Dummy Register User Aggregate",
  [ProvingJobCircuitType.DummyAddL1DepositAggregate]: "Dummy Add L1 Deposit Aggregate",
  [ProvingJobCircuitType.DummyClaimL1DepositAggregate]: "Dummy Claim L1 Deposit Aggregate",
  [ProvingJobCircuitType.DummyTransferTokensL2Aggregate]: "Dummy Transfer Tokens L2 Aggregate",
  [ProvingJobCircuitType.DummyAddL1WithdrawalAggregate]: "Dummy Add L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.DummyProcessL1WithdrawalAggregate]: "Dummy Process L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.WrappedSignatureProof]: "Wrapped Signature Proof",
  [ProvingJobCircuitType.Secp256K1SignatureProof]: "Secp256K1 Signature Proof",
  [ProvingJobCircuitType.Unknown]: "Unknown",
};

/*
const CityWidgetNames: Record<ProvingJobCircuitType, string> = {
  [ProvingJobCircuitType.RegisterUser]: "Register\nUser",
  [ProvingJobCircuitType.RegisterUserAggregate]: "[AGG]\nRegister\nUser",
  [ProvingJobCircuitType.AddL1Deposit]: "Add L1\nDeposit",
  [ProvingJobCircuitType.AddL1DepositAggregate]: "[AGG]\nAdd L1\nDeposit",
  [ProvingJobCircuitType.ClaimL1Deposit]: "Claim\nDeposit",
  [ProvingJobCircuitType.ClaimL1DepositAggregate]: "[AGG]\nClaim\nDeposit",
  [ProvingJobCircuitType.TransferTokensL2]: "Transfer\nTokens",
  [ProvingJobCircuitType.TransferTokensL2Aggregate]: "[AGG]\nTransfer\nTokens",
  [ProvingJobCircuitType.AddL1Withdrawal]: "Add\nWithdrawal",
  [ProvingJobCircuitType.AddL1WithdrawalAggregate]: "[AGG]\nAdd\nWithdrawal",
  [ProvingJobCircuitType.ProcessL1Withdrawal]: "Process\nWithdrawal",
  [ProvingJobCircuitType.ProcessL1WithdrawalAggregate]: "[AGG]\nProcess\nWithdrawal",
  [ProvingJobCircuitType.GenerateRollupStateTransitionProof]: "State\nTransition",
  [ProvingJobCircuitType.GenerateSigHashIntrospectionProof]: "SigHash\nIntrospection",
  [ProvingJobCircuitType.GenerateFinalSigHashProof]: "Final\nSigHash",
  [ProvingJobCircuitType.GenerateFinalSigHashProofGroth16]: "Final\nSigHash (G16)",
  [ProvingJobCircuitType.WrapFinalSigHashProofBLS12381]: "Final\nSigHash\n(Groth16)",
  [ProvingJobCircuitType.AggUserRegisterClaimDepositL2Transfer]: "Register Users\nClaim Deposits\nTransfers",
  [ProvingJobCircuitType.AggAddProcessL1WithdrawalAddL1Deposit]: "Add+Process\nWithdrawals\nAdd Deposits",
  [ProvingJobCircuitType.DummyRegisterUserAggregate]: "Dummy\nRegister\nUser",
  [ProvingJobCircuitType.DummyAddL1DepositAggregate]: "Dummy Add L1 Deposit Aggregate",
  [ProvingJobCircuitType.DummyClaimL1DepositAggregate]: "Dummy Claim L1 Deposit Aggregate",
  [ProvingJobCircuitType.DummyTransferTokensL2Aggregate]: "Dummy Transfer Tokens L2 Aggregate",
  [ProvingJobCircuitType.DummyAddL1WithdrawalAggregate]: "Dummy Add L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.DummyProcessL1WithdrawalAggregate]: "Dummy Process L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.WrappedSignatureProof]: "Wrapped Signature Proof",
  [ProvingJobCircuitType.Secp256K1SignatureProof]: "Secp256K1 Signature Proof",
  [ProvingJobCircuitType.Unknown]: "Unknown",
};
*/

const CityWidgetNames: Record<ProvingJobCircuitType, string> = {
  [ProvingJobCircuitType.RegisterUser]: "Register User",
  [ProvingJobCircuitType.RegisterUserAggregate]: " [AGG]\nRegister User",
  [ProvingJobCircuitType.AddL1Deposit]: "Add L1 Deposit",
  [ProvingJobCircuitType.AddL1DepositAggregate]: " [AGG]\nAdd L1 Deposit",
  [ProvingJobCircuitType.ClaimL1Deposit]: "Claim Deposit",
  [ProvingJobCircuitType.ClaimL1DepositAggregate]: " [AGG]\nClaim Deposit",
  [ProvingJobCircuitType.TransferTokensL2]: "Transfer Tokens",
  [ProvingJobCircuitType.TransferTokensL2Aggregate]: " [AGG]\nTransfer Tokens",
  [ProvingJobCircuitType.AddL1Withdrawal]: "Add Withdrawal",
  [ProvingJobCircuitType.AddL1WithdrawalAggregate]: " [AGG]\nAdd Withdrawal",
  [ProvingJobCircuitType.ProcessL1Withdrawal]: "Process Withdrawal",
  [ProvingJobCircuitType.ProcessL1WithdrawalAggregate]: " [AGG]\nProcess Withdrawal",
  [ProvingJobCircuitType.GenerateRollupStateTransitionProof]: "State Transition",
  [ProvingJobCircuitType.GenerateSigHashIntrospectionProof]: "SigHash Introspection",
  [ProvingJobCircuitType.GenerateFinalSigHashProof]: "Final SigHash",
  [ProvingJobCircuitType.GenerateFinalSigHashProofGroth16]: "Final SigHash\n(G16)",
  [ProvingJobCircuitType.WrapFinalSigHashProofBLS12381]: "Groth16 SigHash",
  [ProvingJobCircuitType.AggUserRegisterClaimDepositL2Transfer]: "Register Users\nClaim Deposits\nTransfers",
  [ProvingJobCircuitType.AggAddProcessL1WithdrawalAddL1Deposit]: "Add Withdrawals\nProcess Withdrawals\nAdd Deposits",
  [ProvingJobCircuitType.DummyRegisterUserAggregate]: "Dummy Register User",
  [ProvingJobCircuitType.DummyAddL1DepositAggregate]: "Dummy Add L1 Deposit Aggregate",
  [ProvingJobCircuitType.DummyClaimL1DepositAggregate]: "Dummy Claim L1 Deposit Aggregate",
  [ProvingJobCircuitType.DummyTransferTokensL2Aggregate]: "Dummy Transfer Tokens L2 Aggregate",
  [ProvingJobCircuitType.DummyAddL1WithdrawalAggregate]: "Dummy Add L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.DummyProcessL1WithdrawalAggregate]: "Dummy Process L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.WrappedSignatureProof]: "Wrapped Signature Proof",
  [ProvingJobCircuitType.Secp256K1SignatureProof]: "Secp256K1 Signature Proof",
  [ProvingJobCircuitType.Unknown]: "Unknown",
};

export {
  CityJobNames,
  CityWidgetNames,
}