[package]
build = "build.rs"
edition = "2021"
name = "qed_user_cli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
plonky2 = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
psy_crypto = { workspace = true }
qed_common_circuit = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
psy_core = { workspace = true }
qedlang_core = { workspace = true }
qed_prover = { workspace = true, default-features = false}
psy_data = { workspace = true }
qed_node = { workspace = true }
qed_rollup_utils = { workspace = true }
qed_api_services = { workspace = true }
qed-common = { workspace = true }
qed_store = { workspace = true, default-features = false }
kvq = { workspace = true }
hashbrown = { workspace = true }
async-trait = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
serde_with = { workspace = true }
bincode = { workspace = true }
dashmap = { workspace = true }
ts-rs =  { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }
cfg-if = {workspace = true}
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
serde-wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
console_error_panic_hook = { workspace = true }
wasm-logger = { workspace = true }
wasm-tracing = { workspace = true }
rpassword = { workspace = true }

# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { workspace = true }
shadow-rs = { workspace = true }

# Native-only build dependencies
[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
shadow-rs = { workspace = true }

# WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
#reqwest = { version = "0.12", default-features = false }
reqwest = { version = "0.12", default-features = false, features = ["json"] }

[features]
# default = ["is_sync"]
is_sync = ["qed_prover/is_sync", "qed_store/is_sync"]
