[package]
build = "build.rs"
edition = "2021"
name = "qed_user_cli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
plonky2 = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
rand = { workspace = true }
qed_crypto = { workspace = true }
qed_common_circuit = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
kvq = { workspace = true }
qed_store = { path = "../qed_store", default-features = false }
qed_core = { workspace = true }
qed_common = { workspace = true }
qedlang_core = { workspace = true }
qed_prover = { path = "../qed_prover", default-features = false}
qed_data = { workspace = true }
qed_rollup_utils = { workspace = true }
hashbrown = { workspace = true }
ts-rs =  { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
async-trait = {workspace = true}
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
web-sys = "0.3"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
wasm-logger = "0.2"
wasm-tracing = "2.0"
cfg-if = {workspace = true}
maybe-async = { workspace = true }

# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
kvq_store_lmdbx = { workspace = true }
reqwest = { workspace = true }
shadow-rs = { workspace = true }

# Native-only build dependencies
[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
shadow-rs = { workspace = true }

# WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
#reqwest = { version = "0.12", default-features = false }
reqwest = { version = "0.12", default-features = false, features = ["json"] }

[features]
default = ["is_sync"]
is_sync = ["qed_prover/is_sync","maybe-async/is_sync", "qed_store/is_sync"]
wasm32 = []
