[package]
build = "build.rs"
edition = "2021"
name = "qed_user_cli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

plonky2 = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
rand = { workspace = true }
qed_crypto = { path = "../qed_crypto" }
qed_common_circuit = { path = "../qed_common_circuit" }
qed_rollup_circuit = { path = "../qed_rollup_circuit" }
# qed_common           = { path = "../qed_common" }
# qed_rollup_user_prover_api           = { path = "../qed_rollup_user_prover_api" }
# qed_rollup_common    = { path = "../qed_rollup_common" }
# qed_rollup_core_node    = { path = "../qed_rollup_core_node" }
# qed_rollup_core_orchestrator = { path = "../qed_rollup_core_orchestrator" }
# bitcoincore-rpc       = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true }
shadow-rs = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
kvq = { path = "../kvq" }
qed_store = { path = "../qed_store" }
qed_core = { path = "../qed_core" }
qed_common = { path = "../qed_common" }
qedlang_core = { path = "../qedlang_core" }
qed_exec = { path = "../qed_exec" }
qed_prover = { path = "../qed_prover" }
qed_data = { path = "../qed_data" }

repl-rs = "0.2.8"
[build-dependencies]
shadow-rs = { workspace = true }
