[package]
edition = "2021"
name    = "parth_common"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["std", "parth_core/serialize_rkyv", "parth_core/serialize_speedy", "parth_core/serialize_postcard", "k256_crypto", "async_tree"]
std = ["parth_core/std", "pser/std"]
serialize_rkyv = ["dep:rkyv","pser/serialize_rkyv", "parth_core/serialize_rkyv"]
serialize_speedy = ["dep:speedy", "pser/serialize_speedy", "parth_core/serialize_speedy"]
serialize_postcard = ["dep:postcard", "pser/serialize_postcard", "parth_core/serialize_postcard"]
k256_crypto = ["dep:k256"]
async_tree = ["dep:dashmap"]

[dependencies]
anyhow     = { workspace = true }
async-trait      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
hex = { workspace = true }
hashbrown = { workspace = true }
hex-literal = { workspace = true }
bincode = { workspace = true }
auto_impl = { workspace = true }
postcard = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
pser = { workspace = true }
ts-rs = { workspace = true }
cf_utils = { workspace = true }
k256 = { workspace = true, optional = true }
dashmap = { workspace = true, optional = true }

# start local packages
parth_core = { workspace = true }

[dev-dependencies]
parth_crypto = { workspace = true }
rand = { workspace = true }