// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContractCallArgs = { contract_id: bigint, method_name: string, inputs: Array<bigint>, };
