// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeltaMerkleProofCore = { old_root: bigint, old_value: bigint, new_root: bigint, new_value: bigint, index: bigint, siblings: Array<bigint>, };
