// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DPNStateCmdInvokeExternalContractFunctionSync = { condition: bigint, contract_id: bigint, method_id: bigint, input_args: Array<bigint>, num_outputs: number, };
