// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DPNStateCmdGetCheckpointLeafStats } from "./DPNStateCmdGetCheckpointLeafStats";
import type { DPNStateCmdGetOtherUserContractStateSlotHash } from "./DPNStateCmdGetOtherUserContractStateSlotHash";
import type { DPNStateCmdGetOtherUserContractStateSlotRange } from "./DPNStateCmdGetOtherUserContractStateSlotRange";
import type { DPNStateCmdGetOtherUserContractStateSlotSingle } from "./DPNStateCmdGetOtherUserContractStateSlotSingle";
import type { DPNStateCmdGetSelfUserCurrentContractStateSlotHash } from "./DPNStateCmdGetSelfUserCurrentContractStateSlotHash";
import type { DPNStateCmdGetSelfUserCurrentContractStateSlotRange } from "./DPNStateCmdGetSelfUserCurrentContractStateSlotRange";
import type { DPNStateCmdGetSelfUserCurrentContractStateSlotSingle } from "./DPNStateCmdGetSelfUserCurrentContractStateSlotSingle";
import type { DPNStateCmdGetSelfUserExternalContractStateSlotHash } from "./DPNStateCmdGetSelfUserExternalContractStateSlotHash";
import type { DPNStateCmdGetSelfUserExternalContractStateSlotRange } from "./DPNStateCmdGetSelfUserExternalContractStateSlotRange";
import type { DPNStateCmdGetSelfUserExternalContractStateSlotSingle } from "./DPNStateCmdGetSelfUserExternalContractStateSlotSingle";
import type { DPNStateCmdInvokeExternalContractFunctionDeferred } from "./DPNStateCmdInvokeExternalContractFunctionDeferred";
import type { DPNStateCmdInvokeExternalContractFunctionSync } from "./DPNStateCmdInvokeExternalContractFunctionSync";
import type { DPNStateCmdSetContractStateSlotHash } from "./DPNStateCmdSetContractStateSlotHash";
import type { DPNStateCmdSetContractStateSlotRange } from "./DPNStateCmdSetContractStateSlotRange";
import type { DPNStateCmdSetContractStateSlotSingle } from "./DPNStateCmdSetContractStateSlotSingle";

export type DPNStateCmd = { "type": "SetContractStateSlotHash" } & DPNStateCmdSetContractStateSlotHash | { "type": "SetContractStateSlotSingle" } & DPNStateCmdSetContractStateSlotSingle | { "type": "SetContractStateSlotRange" } & DPNStateCmdSetContractStateSlotRange | { "type": "InvokeExternalContractFunctionSync" } & DPNStateCmdInvokeExternalContractFunctionSync | { "type": "InvokeExternalContractFunctionDeferred" } & DPNStateCmdInvokeExternalContractFunctionDeferred | { "type": "GetSelfUserCurrentContractStateSlotHash" } & DPNStateCmdGetSelfUserCurrentContractStateSlotHash | { "type": "GetSelfUserCurrentContractStateSlotSingle" } & DPNStateCmdGetSelfUserCurrentContractStateSlotSingle | { "type": "GetSelfUserCurrentContractStateSlotRange" } & DPNStateCmdGetSelfUserCurrentContractStateSlotRange | { "type": "GetSelfUserExternalContractStateSlotHash" } & DPNStateCmdGetSelfUserExternalContractStateSlotHash | { "type": "GetSelfUserExternalContractStateSlotSingle" } & DPNStateCmdGetSelfUserExternalContractStateSlotSingle | { "type": "GetSelfUserExternalContractStateSlotRange" } & DPNStateCmdGetSelfUserExternalContractStateSlotRange | { "type": "GetOtherUserContractStateSlotHash" } & DPNStateCmdGetOtherUserContractStateSlotHash | { "type": "GetOtherUserContractStateSlotSingle" } & DPNStateCmdGetOtherUserContractStateSlotSingle | { "type": "GetOtherUserContractStateSlotRange" } & DPNStateCmdGetOtherUserContractStateSlotRange | { "type": "GetCheckpointLeafStats" } & DPNStateCmdGetCheckpointLeafStats;
