import { QEDCheckpointLeaf } from "./QEDCheckpointLeaf";
import { QHashOut } from "../core";

/**
 * @file Automatically generated by barrelsby.
 */

export * from "./ContractCallArgs";
export * from "./ContractCodeDefinition";
export * from "./ContractFunctionCodeDefinition";
export * from "./DeltaMerkleProofCore";
export * from "./GUTAStats";
export * from "./PMRewardCommitment";
export * from "./QAddWithdrawalRPCRequest";
export * from "./QBCDeployContract";
export * from "./QCheckpointGlobalStateRootsRPCRequest";
export * from "./QCheckpointLeafDataFRPCRequest";
export * from "./QCheckpointLeafDataRPCRequest";
export * from "./QCheckpointTreeLeafHashFRPCRequest";
export * from "./QCheckpointTreeLeafHashRPCRequest";
export * from "./QCheckpointTreeMerkleProofFRPCRequest";
export * from "./QCheckpointTreeMerkleProofRPCRequest";
export * from "./QCheckpointTreeRootFRPCRequest";
export * from "./QCheckpointTreeRootRPCRequest";
export * from "./QClaimDepositRPCRequest";
export * from "./QContractCodeDefinitionFRPCRequest";
export * from "./QContractCodeDefinitionRPCRequest";
export * from "./QContractFunctionTreeLeafHashFRPCRequest";
export * from "./QContractFunctionTreeLeafHashRPCRequest";
export * from "./QContractFunctionTreeMerkleProofFRPCRequest";
export * from "./QContractFunctionTreeMerkleProofRPCRequest";
export * from "./QContractFunctionTreeRootFRPCRequest";
export * from "./QContractFunctionTreeRootRPCRequest";
export * from "./QContractLeafDataFRPCRequest";
export * from "./QContractLeafDataRPCRequest";
export * from "./QContractTreeLeafHashFRPCRequest";
export * from "./QContractTreeLeafHashRPCRequest";
export * from "./QContractTreeMerkleProofFRPCRequest";
export * from "./QContractTreeMerkleProofRPCRequest";
export * from "./QContractTreeRootFRPCRequest";
export * from "./QContractTreeRootRPCRequest";
export * from "./QDeployContractRPCRequest";
export * from "./QDepositTreeLeafHashFRPCRequest";
export * from "./QDepositTreeLeafHashRPCRequest";
export * from "./QDepositTreeMerkleProofFRPCRequest";
export * from "./QDepositTreeMerkleProofRPCRequest";
export * from "./QDepositTreeRootFRPCRequest";
export * from "./QDepositTreeRootRPCRequest";
export * from "./QEDCheckpointGlobalStateRoots";
export * from "./QEDCheckpointLeaf";
export * from "./QEDCheckpointLeafCompact";
export * from "./QEDCheckpointLeafCompactWithStateRoots";
export * from "./QEDCheckpointLeafStats";
export * from "./QEDContractLeaf";
export * from "./QEDContractStateUpdateHistory";
export * from "./QEDL2BlockState";
export * from "./QEDUserLeaf";
export * from "./QEDUserPublicKeyRecord";
export * from "./QHashOut";
export * from "./QL2BlockStateFRPCRequest";
export * from "./QL2BlockStateRPCRequest";
export * from "./QLatestCheckpointTreeRootRPCRequest";
export * from "./QLatestL2BlockStateRPCRequest";
export * from "./QRPCRequest";
export * from "./QRegisterUserRPCRequest";
export * from "./QSubmitEndCapRPCRequest";
export * from "./QTokenTransferRPCRequest";
export * from "./QUserContractStateTreeLeafHashFRPCRequest";
export * from "./QUserContractStateTreeLeafHashRPCRequest";
export * from "./QUserContractStateTreeMerkleProofFRPCRequest";
export * from "./QUserContractStateTreeMerkleProofRPCRequest";
export * from "./QUserContractStateTreeRootFRPCRequest";
export * from "./QUserContractStateTreeRootRPCRequest";
export * from "./QUserContractTreeLeafHashFRPCRequest";
export * from "./QUserContractTreeLeafHashRPCRequest";
export * from "./QUserContractTreeMerkleProofFRPCRequest";
export * from "./QUserContractTreeMerkleProofRPCRequest";
export * from "./QUserContractTreeRootFRPCRequest";
export * from "./QUserContractTreeRootRPCRequest";
export * from "./QUserLeafDataFRPCRequest";
export * from "./QUserLeafDataRPCRequest";
export * from "./QUserRegistrationTreeLeafHashFRPCRequest";
export * from "./QUserRegistrationTreeLeafHashRPCRequest";
export * from "./QUserRegistrationTreeMerkleProofFRPCRequest";
export * from "./QUserRegistrationTreeMerkleProofRPCRequest";
export * from "./QUserRegistrationTreeRootFRPCRequest";
export * from "./QUserRegistrationTreeRootRPCRequest";
export * from "./QUserSubTreeMerkleProofRPCRequest";
export * from "./QUserTreeLeafHashFRPCRequest";
export * from "./QUserTreeLeafHashRPCRequest";
export * from "./QUserTreeMerkleProofFRPCRequest";
export * from "./QUserTreeMerkleProofRPCRequest";
export * from "./QUserTreeRootFRPCRequest";
export * from "./QUserTreeRootRPCRequest";
export * from "./QWithdrawalTreeLeafHashFRPCRequest";
export * from "./QWithdrawalTreeLeafHashRPCRequest";
export * from "./QWithdrawalTreeMerkleProofFRPCRequest";
export * from "./QWithdrawalTreeMerkleProofRPCRequest";
export * from "./QWithdrawalTreeRootFRPCRequest";
export * from "./QWithdrawalTreeRootRPCRequest";
export * from "./SubmitUserEndCapNonProofCoreInput";
export * from "./SubmitUserEndCapNonProofInput";
export * from "./UPSEndCapResultCompact";
export * from "./ZKPublicKeyInfo";
export * from "./plonkTypes";
export * from "./vmTypes";


// User leaf data
export interface QEDUserLeaf {
    user_id: bigint;
    nonce: bigint;
    last_checkpoint_id: bigint;
    user_state_tree_root: QHashOut;
    user_contract_tree_root: QHashOut;
    user_pk_hash: QHashOut;
}

// Contract state updates
export interface QEDContractStateUpdateHistory {
    contract_id: bigint;
    updates: any[]; // This is a placeholder, replace with actual type if needed
}

// User EndCap core input
export interface SubmitUserEndCapNonProofCoreInput {
    checkpoint_id: bigint;
    stats: any; // GUTAStats
    state_transition: any; // UPSEndCapResultCompact
    new_user_leaf: QEDUserLeaf;
}

// Full NonProof input
export interface SubmitUserEndCapNonProofInput {
    core: SubmitUserEndCapNonProofCoreInput;
    contract_state_updates: QEDContractStateUpdateHistory[];
}

/**
 * L2 Block State structure
 */
export interface QEDL2BlockState {
    checkpoint_id: bigint;
    next_add_withdrawal_id: bigint;
    next_process_withdrawal_id: bigint;
    next_deposit_id: bigint;
    total_deposits_claimed_epoch: bigint;
    next_user_id: bigint;
    end_balance: bigint;
}

/**
 * QED Contract Leaf structure
 */
export interface QEDContractLeaf {
    contract_id: bigint;
    owner_id: bigint;
    code_hash: QHashOut;
    whitelist_root: QHashOut;
    is_core_contract: boolean;
    create_checkpoint_id: bigint;
}

/**
 * QED Contract Code Definition
 */
export interface ContractCodeDefinition {
    contract_id: bigint;
    code_hash: QHashOut;
    code_path: string;
    code_size: bigint;
}

/**
 * QED Checkpoint Global State Roots
 */
export interface QEDCheckpointGlobalStateRoots {
    contract_tree_root: QHashOut;
    deposit_tree_root: QHashOut;
    user_tree_root: QHashOut;
    withdrawal_tree_root: QHashOut;
    user_registration_tree_root: QHashOut;
}

/**
 * QED Checkpoint Sync Info Compact
 */
export interface QEDCheckpointSyncInfoCompact {
    checkpoint_id: bigint;
    checkpoint_tree_root: QHashOut;
    checkpoint_leaf_data: QEDCheckpointLeaf;
    global_state_roots: QEDCheckpointGlobalStateRoots;
}

/**
 * Checkpoint Sync Info Full Structure
 */
export interface CheckpointSyncInfo {
    latest_checkpoint_id: bigint;
    description: string | null;
    source_coordinator_edge_id: string | null;
    sync_timestamp: bigint;
    compact: QEDCheckpointSyncInfoCompact;
}

/**
 * ZK Public Key Info
 */
export interface ZKPublicKeyInfo {
    fingerprint: QHashOut;
    public_key_param: QHashOut;
}

/**
 * Response for the latest checkpoint
 */
export interface LatestCheckpointResponse {
    checkpoint_id: bigint;
}

// Request types for RPC methods
export interface QContractLeafDataRPCRequest {
    contract_id: number;
}

export interface QContractLeafDataFRPCRequest {
    contract_id: bigint;
}

export interface QCheckpointLeafDataRPCRequest {
    checkpoint_id: number;
}

export interface QCheckpointLeafDataFRPCRequest {
    checkpoint_id: bigint;
}

export interface QContractCodeDefinitionRPCRequest {
    contract_id: number;
}

export interface QContractCodeDefinitionFRPCRequest {
    contract_id: bigint;
}

export interface QL2BlockStateRPCRequest {
    checkpoint_id: number;
}

export interface QL2BlockStateFRPCRequest {
    checkpoint_id: bigint;
}

export interface QUserRegistrationTreeRootRPCRequest {
    checkpoint_id: number;
}

export interface QUserRegistrationTreeRootFRPCRequest {
    checkpoint_id: bigint;
}

export interface QUserRegistrationTreeLeafHashRPCRequest {
    checkpoint_id: number;
    leaf_index: number;
}

export interface QUserRegistrationTreeLeafHashFRPCRequest {
    checkpoint_id: bigint;
    leaf_index: bigint;
}

export interface QUserRegistrationTreeMerkleProofRPCRequest {
    checkpoint_id: number;
    leaf_index: number;
}

export interface QUserRegistrationTreeMerkleProofFRPCRequest {
    checkpoint_id: bigint;
    leaf_index: bigint;
}

export interface QUserTreeRootRPCRequest {
    checkpoint_id: number;
}

export interface QUserTreeRootFRPCRequest {
    checkpoint_id: bigint;
}

export interface QUserSubTreeMerkleProofRPCRequest {
    checkpoint_id: number;
    root_level: number;
    leaf_level: number;
    leaf_index: number;
}

export interface QUserLeafDataRPCRequest {
    checkpoint_id: number;
    user_id: number;
}

export interface QUserTreeMerkleProofRPCRequest {
    checkpoint_id: number;
    user_id: number;
}

export interface QUserTreeMerkleProofFRPCRequest {
    checkpoint_id: bigint;
    user_id: bigint;
}

export interface QContractFunctionTreeRootRPCRequest {
    checkpoint_id: number;
    contract_id: number;
}

export interface QContractFunctionTreeRootFRPCRequest {
    checkpoint_id: bigint;
    contract_id: bigint;
}

export interface QContractFunctionTreeLeafHashRPCRequest {
    checkpoint_id: number;
    contract_id: number;
    function_id: number;
}

export interface QContractFunctionTreeLeafHashFRPCRequest {
    checkpoint_id: bigint;
    contract_id: bigint;
    function_id: bigint;
}

export interface QContractFunctionTreeMerkleProofRPCRequest {
    checkpoint_id: number;
    contract_id: number;
    function_id: number;
}

export interface QContractFunctionTreeMerkleProofFRPCRequest {
    checkpoint_id: bigint;
    contract_id: bigint;
    function_id: bigint;
}

export interface QContractTreeRootRPCRequest {
    checkpoint_id: number;
}

export interface QContractTreeRootFRPCRequest {
    checkpoint_id: bigint;
}

export interface QContractTreeLeafHashRPCRequest {
    checkpoint_id: number;
    contract_id: number;
}

export interface QContractTreeLeafHashFRPCRequest {
    checkpoint_id: bigint;
    contract_id: bigint;
}

export interface QContractTreeMerkleProofRPCRequest {
    checkpoint_id: number;
    contract_id: number;
}

export interface QContractTreeMerkleProofFRPCRequest {
    checkpoint_id: bigint;
    contract_id: bigint;
}

export interface QDepositTreeRootRPCRequest {
    checkpoint_id: number;
}

export interface QDepositTreeRootFRPCRequest {
    checkpoint_id: bigint;
}

export interface QDepositTreeLeafHashRPCRequest {
    checkpoint_id: number;
    deposit_id: number;
}

export interface QDepositTreeLeafHashFRPCRequest {
    checkpoint_id: bigint;
    deposit_id: bigint;
}

export interface QDepositTreeMerkleProofRPCRequest {
    checkpoint_id: number;
    deposit_id: number;
}

export interface QDepositTreeMerkleProofFRPCRequest {
    checkpoint_id: bigint;
    deposit_id: bigint;
}

export interface QWithdrawalTreeRootRPCRequest {
    checkpoint_id: number;
}

export interface QWithdrawalTreeRootFRPCRequest {
    checkpoint_id: bigint;
}

export interface QWithdrawalTreeLeafHashRPCRequest {
    checkpoint_id: number;
    withdrawal_id: number;
}

export interface QWithdrawalTreeLeafHashFRPCRequest {
    checkpoint_id: bigint;
    withdrawal_id: bigint;
}

export interface QWithdrawalTreeMerkleProofRPCRequest {
    checkpoint_id: number;
    withdrawal_id: number;
}

export interface QWithdrawalTreeMerkleProofFRPCRequest {
    checkpoint_id: bigint;
    withdrawal_id: bigint;
}

export interface QCheckpointTreeRootRPCRequest {
    checkpoint_id: number;
}

export interface QCheckpointTreeRootFRPCRequest {
    checkpoint_id: bigint;
}

export interface QCheckpointTreeLeafHashRPCRequest {
    checkpoint_id: number;
    leaf_checkpoint_id: number;
}

export interface QCheckpointTreeLeafHashFRPCRequest {
    checkpoint_id: bigint;
    leaf_checkpoint_id: bigint;
}

export interface QCheckpointTreeMerkleProofRPCRequest {
    checkpoint_id: number;
    leaf_checkpoint_id: number;
}

export interface QCheckpointTreeMerkleProofFRPCRequest {
    checkpoint_id: bigint;
    leaf_checkpoint_id: bigint;
}
