// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PMJobsCompletedStats = { deploy_contracts_completed: bigint, register_users_completed: bigint, gutas_completed: bigint, };