// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QAddWithdrawalRPCRequest = { user_id: bigint, value: bigint, nonce: bigint, destination_type: number, destination: String, signature_proof: String, };
