// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractCodeDefinition } from "./ContractCodeDefinition";
import type { QHashOut } from "./QHashOut";

export type QBCDeployContract = { deployer: QHashOut, code_definition: ContractCodeDefinition, function_whitelist: Array<QHashOut>, function_code_hashes: Array<QHashOut>, };
