// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QContractFunctionTreeMerkleProofRPCRequest = { checkpoint_id: bigint, contract_id: number, function_id: number, };
