// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type QEDCheckpointGlobalStateRoots = { contract_tree_root: QHashOut, deposit_tree_root: QHashOut, user_tree_root: QHashOut, withdrawal_tree_root: QHashOut, user_registration_tree_root: QHashOut, };
