// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type QEDUserPublicKeyRecord = { public_key_param: QHashOut, fingerprint: QHashOut, public_key: QHashOut, user_id: bigint, checkpoint_id: bigint, };
