// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmitUserEndCapNonProofInput } from "./SubmitUserEndCapNonProofInput";

export type QSubmitEndCapRPCRequest = { user_ec_input: SubmitUserEndCapNonProofInput, proof: any, };
