// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QTokenTransferRPCRequest = { user_id: bigint, to: bigint, value: bigint, nonce: bigint, signature_proof: string, };
