// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QUserSubTreeMerkleProofRPCRequest = { checkpoint_id: bigint, root_level: number, leaf_level: number, leaf_index: bigint, };
