[package]
edition = "2021"
name = "psy_node_cli"
version = "0.1.0"

[dependencies]
clap = { workspace = true }
dotenv = { workspace = true }
psy_node = { workspace = true }
psy_core = { workspace = true }
plonky2 = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
psy-common = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
psy_network_circuit = { workspace = true }
psy_dpn_circuit = { workspace = true }
psy_ups_circuit = { workspace = true }
psy_crypto = { workspace = true }
psy_prover = { workspace = true }
psy_rust_sdk = { workspace = true }
psy_store = { workspace = true }
psy_data = { workspace = true }
psy_config = { workspace = true }
kvq = { workspace = true }
psy_services = { workspace = true }
