use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=../config.json");

    let config_path = Path::new("../config.json");
    let config_content = fs::read_to_string(config_path)
        .expect("Failed to read config.json");

    let config: serde_json::Value = serde_json::from_str(&config_content)
        .expect("Failed to parse config.json");

    let network = &config["network"];
    let global_user_tree_height = network["global_user_tree_height"]
        .as_u64()
        .expect("global_user_tree_height must be a number") as u8;
    let realm_user_tree_height = network["realm_user_tree_height"]
        .as_u64()
        .expect("realm_user_tree_height must be a number") as u8;
    let users_per_realm = network["users_per_realm"]
        .as_u64()
        .expect("users_per_realm must be a number");
    let group_realm_height = network["group_realm_height"]
        .as_u64()
        .expect("group_realm_height must be a number") as u8;

    if global_user_tree_height < realm_user_tree_height {
        panic!("global_user_tree_height ({}) must be >= realm_user_tree_height ({})",
               global_user_tree_height, realm_user_tree_height);
    }

    let expected_users_per_realm = 1u64 << realm_user_tree_height;
    if users_per_realm != expected_users_per_realm {
        panic!("users_per_realm ({}) must equal 2^realm_user_tree_height (2^{} = {})",
               users_per_realm, realm_user_tree_height, expected_users_per_realm);
    }

    let coordinator_user_tree_height = global_user_tree_height - realm_user_tree_height;

    let native_currency_decimal = network["native_currency_decimal"]
        .as_u64()
        .expect("native_currency_decimal must be a number") as u8;

    let native_currency = network["native_currency"]
        .as_str()
        .expect("native_currency must be a string")
        .to_string();

    let native_currency_name = network["native_currency_name"]
        .as_str()
        .expect("native_currency_name must be a string")
        .to_string();

    let fees = &network["fees"];
    let register_user_fee = fees["register_user_fee"]
        .as_u64()
        .expect("register_user_fee must be a number");
    let deploy_contract_fee = fees["deploy_contract_fee"]
        .as_u64()
        .expect("deploy_contract_fee must be a number");
    let guta_fee = fees["guta_fee"]
        .as_u64()
        .expect("guta_fee must be a number");

    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_constants.rs");

    let content = format!(
        r#"// This file is auto-generated by build.rs from config.json
// DO NOT EDIT MANUALLY

pub const GLOBAL_USER_TREE_HEIGHT: u8 = {};
pub const COORDINATOR_USER_TREE_HEIGHT: u8 = {};
pub const REALM_USER_TREE_HEIGHT: u8 = {};
pub const GROUP_REALM_HEIGHT: u8 = {};
pub const USERS_PER_REALM: u64 = {};

// Native currency configuration
pub const NATIVE_CURRENCY_DECIMAL: u8 = {};
pub const NATIVE_CURRENCY: &str = "{}";
pub const NATIVE_CURRENCY_NAME: &str = "{}";

// Fee configuration
pub const REGISTER_USER_FEE: u64 = {};
pub const DEPLOY_CONTRACT_FEE: u64 = {};
pub const GUTA_FEE: u64 = {};
"#,
        global_user_tree_height,
        coordinator_user_tree_height,
        realm_user_tree_height,
        group_realm_height,
        users_per_realm,
        native_currency_decimal,
        native_currency,
        native_currency_name,
        register_user_fee,
        deploy_contract_fee,
        guta_fee
    );

    fs::write(&dest_path, content).expect("Failed to write generated constants");
}
