[package]
name = "dargo"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
clap.workspace = true
clap_complete = { workspace = true }
anyhow.workspace = true
tokio = { workspace = true }
color-eyre = { workspace = true }
serde.workspace = true
serde_json.workspace = true

qed_package.workspace = true
qed-interpreter.workspace = true
qedlang_core.workspace = true
qed-common = { workspace = true }
plonky2 = { workspace = true }
qed_crypto = { workspace = true }
qed_exec = { workspace = true }
qed_data = { workspace = true, default-features = false }
qed_core = { workspace = true }
qed_common_circuit = { workspace = true }
qed-sema = { workspace = true }
qed-ast = { workspace = true }
qed-abi = { workspace = true }
num-bigint = { workspace = true }
kvq = { workspace = true }
qed_store = { workspace = true, default-features = false }
qed_prover = { workspace = true, default-features = false }

[features]
default = ["is_sync"]
is_sync = [
    "qed_data/is_sync",
    "qed_store/is_sync",
    "qed_prover/is_sync",
]

[dev-dependencies]
num-traits = { workspace = true }
insta = { workspace = true }
