[package]
name = "dargo"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
clap.workspace = true
clap_complete = { workspace = true }
anyhow.workspace = true
tokio = { workspace = true }
color-eyre = { workspace = true }
serde.workspace = true
serde_json.workspace = true

qed_package.workspace = true
qed-interpreter.workspace = true
psy_vm.workspace = true
qed-common = { workspace = true }
plonky2 = { workspace = true }
psy_crypto = { workspace = true }
psy_exec = { workspace = true }
psy_data = { workspace = true, default-features = false }
psy_core = { workspace = true }
qed_common_circuit = { workspace = true }
qed-sema = { workspace = true }
qed-ast = { workspace = true }
qed-abi = { workspace = true }
num-bigint = { workspace = true }
kvq = { workspace = true }
psy_store = { workspace = true, default-features = false }
qed_prover = { workspace = true, default-features = false }

[features]
# default = ["is_sync"]
is_sync = [
    "psy_data/is_sync",
    "psy_store/is_sync",
    "qed_prover/is_sync",
]

[dev-dependencies]
num-traits = { workspace = true }
insta = { workspace = true }
