[package]
edition = "2021"
name = "qed_realm_node"
version = "0.1.0"

[lib]
name = "qed_realm_node"
path = "src/lib.rs"

[dependencies]
qed_core = { workspace = true }
qed_data = { workspace = true }
qed_store = { workspace = true }
qed_crypto = { workspace = true }
qed_node = { workspace = true }
qed_rollup_utils = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
fred = { workspace = true }
jsonrpsee = { workspace = true }
plonky2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tokio = { workspace = true }
kvq = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
tower = { workspace = true }

tracing = { workspace = true }
clap = { workspace = true }
hex.workspace = true
bincode.workspace = true

redis = { workspace = true }
bb8-redis = { workspace = true }
bb8 = { workspace = true }
