// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QHashOut } from "./QHashOut";
import type { UpdateNCAWithAdditionalLink } from "./UpdateNCAWithAdditionalLink";

export type NCAProofsWithTopLine = { nca_proofs: Array<UpdateNCAWithAdditionalLink>, top_line_proof: DeltaMerkleProofCore<QHashOut>, };
