// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { PartialUpdateNearestCommonAncestorProof } from "./PartialUpdateNearestCommonAncestorProof";
import type { QHashOut } from "./QHashOut";

export type PartialNCAProofsWithTopLine = { nca_proofs: Array<PartialUpdateNearestCommonAncestorProof>, top_line_proof: DeltaMerkleProofCore<QHashOut>, };
