// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type PartialUpdateNearestCommonAncestorProof = { child_a: DeltaMerkleProofCore<QHashOut>, child_b: DeltaMerkleProofCore<QHashOut>, nearest_common_ancestor_level: number, };
