// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartialUpdateNearestCommonAncestorProof } from "./PartialUpdateNearestCommonAncestorProof";
import type { QHashOut } from "./QHashOut";

export type PartialUpdateNCAWithAdditionalLink = { nca_proof: PartialUpdateNearestCommonAncestorProof, link_siblings: Array<QHashOut>, };
