// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";

export type SpidermanUpdateProof<Hash> = { top_line_proof: DeltaMerkleProofCore<Hash>, web_proof_old_leaves: Array<Hash>, web_proof_new_leaves: Array<Hash>, };
