// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagTreeNodePreimage } from "./TagTreeNodePreimage";
import type { TagTreeProofNode } from "./TagTreeProofNode";

export type TagTreeMerkleProof<Hash> = { index: bigint, leaf: TagTreeNodePreimage<Hash>, root: Hash, siblings: Array<TagTreeProofNode<Hash>>, };
