// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QHashOut } from "./QHashOut";
import type { UpdateNearestCommonAncestorProof } from "./UpdateNearestCommonAncestorProof";

export type UpdateNCAWithAdditionalLink = { nca_proof: UpdateNearestCommonAncestorProof, link_proof: DeltaMerkleProofCore<QHashOut>, };
