// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type UpdateNearestCommonAncestorProof = { old_nearest_common_ancestor_value: QHashOut, new_nearest_common_ancestor_value: QHashOut, child_a: DeltaMerkleProofCore<QHashOut>, child_b: DeltaMerkleProofCore<QHashOut>, nearest_common_ancestor_level: number, nearest_common_ancestor_index: bigint, level_a: number, level_b: number, };
