// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QHashOut } from "./QHashOut";
import type { UpdateNearestCommonAncestorProof } from "./UpdateNearestCommonAncestorProof";

export type UpdateNCAProofsWithDependencies = { nca_proofs: Array<UpdateNearestCommonAncestorProof>, dependencies: Array<[bigint, bigint]>, root_proof_index: number, nearest_common_ancestor_level: number, nearest_common_ancestor_index: bigint, link_level: number, link_index: bigint, link_proof: DeltaMerkleProofCore<QHashOut>, };
