[package]
edition = "2021"
name    = "cf_utils"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rand", "std"]
std = []
rand = ["dep:rand"]

[dependencies]
anyhow     = { workspace = true }
async-trait      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
rand = { workspace = true, optional = true }
