[package]
edition = "2021"
name    = "parth_crypto"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "parth_core/serialize_rkyv", "parth_core/serialize_speedy", "parth_core/serialize_postcard"]
std = ["parth_core/std", "pser/std"]
serialize_rkyv = ["dep:rkyv","pser/serialize_rkyv", "parth_core/serialize_rkyv"]
serialize_speedy = ["dep:speedy", "pser/serialize_speedy", "parth_core/serialize_speedy"]
serialize_postcard = ["dep:postcard", "pser/serialize_postcard", "parth_core/serialize_postcard"]

[dependencies]
postcard = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
pser = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }



parth_core = { workspace = true }


[dev-dependencies]
criterion = { workspace = true }
cf_utils = { workspace = true }
rayon = { workspace = true }


[[bench]]
name = "main"
harness = false
