// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QJobTopic = "GenerateStandardProof" | "GenerateGroth16Proof" | "BlockUserSignatureProof" | "NotifyCoordinatorComplete" | "NotifyRealmComplete" | "AggregateJobs" | "Invalid" | "Unknown";
