[package]
edition = "2021"
name    = "parth_node_scylla"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["std", "parth_core/serialize_rkyv", "parth_core/serialize_speedy", "parth_core/serialize_postcard", "parallel_rayon"]
std = ["parth_core/std", "pser/std", "psy_serialize/std"]
serialize_rkyv = ["dep:rkyv","pser/serialize_rkyv", "parth_core/serialize_rkyv"]
serialize_speedy = ["dep:speedy", "pser/serialize_speedy", "parth_core/serialize_speedy"]
serialize_postcard = ["dep:postcard", "pser/serialize_postcard", "parth_core/serialize_postcard"]
parallel_rayon = ["dep:rayon"]
[dependencies]
rayon = { workspace = true, optional = true }
postcard = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
anyhow     = { workspace = true }
uuid = { workspace = true }
async-trait      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true}
rand = { workspace = true }
rand_chacha = { workspace = true }
auto_impl = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
scylla = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
# start local packages
pser = { workspace = true }
pderive = { workspace = true }
parth_core = { workspace = true }
psy_serialize = { workspace = true }
# parth_common = { workspace = true }
# psy_core = { workspace = true }
# parth_crypto = { workspace = true }
# psy_common = { workspace = true }
psy_node_core = { workspace = true }
dashmap = { workspace = true }


[dev-dependencies]
criterion = { workspace = true }
parth_crypto = { workspace = true }
parth_common = { workspace = true }
psy_data = { workspace = true }
cf_utils = { workspace = true }


[[bench]]
name = "main"
harness = false