[package]
edition = "2021"
name = "qed_rollup_utils"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jsonwebtoken = { workspace = true }

#
#[target.'cfg(target_arch = "wasm32")'.dependencies]
#jsonwebtoken = { workspace = true }
