[package]
edition = "2021"
name    = "qed_store"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
hashbrown      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_with = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
lazy_static = { workspace = true }
async-trait = { workspace = true }
plonky2 = { workspace = true }
twox-hash = { workspace = true }
tracing = { workspace = true }
indexmap = { workspace = true }

kvq = { path = "../kvq" }
qed_core = { path = "../qed_core" }
qed_data = { path = "../qed_data" }
qed_crypto = { path = "../qed_crypto" }
thiserror = { workspace = true }
maybe-async = { workspace = true }
#maybe-async = { workspace = true, optional = true }

[features]
default = ["is_sync"]
#default = []
#is_sync = ["dep:maybe-async"]
is_sync = ["maybe-async/is_sync"]