// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QEDCheckpointSyncInfoCompact } from "./QEDCheckpointSyncInfoCompact";
import type { QHashOut } from "./QHashOut";

/**
 * push the latest checkpoint sync info
 */
export type CheckpointSyncInfo = { latest_checkpoint_id: bigint, description: string | null, source_coordinator_edge_id: string | null, sync_timestamp: bigint, compact: QEDCheckpointSyncInfoCompact, realm_root: QHashOut, };
