// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContractConfig = { name: string, path: string, contract_name: string, method_names: Array<string>, };
