// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeltaMerkleProofCore<Hash> = { old_root: Hash, old_value: Hash, new_root: Hash, new_value: Hash, index: bigint, siblings: Array<Hash>, };
