// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";

export type GlobalUserTreeAggregatorHeaderWithProofStats = { base_header: GlobalUserTreeAggregatorHeader, total_guta_proofs_generated: bigint, };
