// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { QHashOut } from "./QHashOut";
import type { SubTreeNodeStateTransition } from "./SubTreeNodeStateTransition";

export type GlobalUserTreeAggregatorHeader = { guta_circuit_whitelist: QHashOut, checkpoint_tree_root: QHashOut, state_transition: SubTreeNodeStateTransition, stats: GUTAStats, };
