// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeaderWithTagValue } from "./GlobalUserTreeAggregatorHeaderWithTagValue";
import type { QProvingJobDataID } from "./QProvingJobDataID";

export type GlobalUserTreeAggregatorHeaderWithTagValueAndJobID = { header: GlobalUserTreeAggregatorHeaderWithTagValue, job_id: QProvingJobDataID, };
