// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeaderWithProofStats } from "./GlobalUserTreeAggregatorHeaderWithProofStats";
import type { QHashOut } from "./QHashOut";

export type GlobalUserTreeAggregatorHeaderWithTagValue = { header_with_stats: GlobalUserTreeAggregatorHeaderWithProofStats, new_tag_tree_node_value: QHashOut, };
