// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTARegisterUserFullInput } from "./GUTARegisterUserFullInput";
import type { QHashOut } from "./QHashOut";

export type GUTAOnlyRegisterUsersInput = { checkpoint_tree_root: QHashOut, guta_register_user_inputs: Array<GUTARegisterUserFullInput>, };
