// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type GUTARegisterUserFullInput = { user_registration_tree_merkle_proof: MerkleProofCore<QHashOut>, global_user_tree_update_proof: DeltaMerkleProofCore<QHashOut>, };
