// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QEDCheckpointLeafCompactWithStateRoots } from "./QEDCheckpointLeafCompactWithStateRoots";
import type { QHashOut } from "./QHashOut";

export type GUTANoChangeFullInput = { checkpoint_tree_proof: MerkleProofCore<QHashOut>, checkpoint_leaf: QEDCheckpointLeafCompactWithStateRoots, };
