// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type PMRewardCommitmentHash = { register_users_root: QHashOut, gutas_root: QHashOut, deploy_contracts_root: QHashOut, };
