// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PMJobsCompletedStats } from "./PMJobsCompletedStats";
import type { PMRewardCommitmentHash } from "./PMRewardCommitmentHash";
import type { QHashOut } from "./QHashOut";

export type QEDCheckpointLeafStats = { fees_collected: bigint, user_ops_processed: bigint, total_transactions: bigint, slots_modified: bigint, pm_jobs_completed: PMJobsCompletedStats, block_time: bigint, random_seed: QHashOut, pm_rewards_commitment: PMRewardCommitmentHash, da_challenges_claimed: [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint], };
