// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QEDCheckpointLeafStats } from "./QEDCheckpointLeafStats";
import type { QHashOut } from "./QHashOut";

export type QEDCheckpointLeaf = { global_chain_root: QHashOut, stats: QEDCheckpointLeafStats, };
