// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QEDCheckpointGlobalStateRoots } from "./QEDCheckpointGlobalStateRoots";
import type { QEDCheckpointLeafStats } from "./QEDCheckpointLeafStats";
import type { QEDL2BlockState } from "./QEDL2BlockState";
import type { QHashOut } from "./QHashOut";
import type { ZKPublicKeyInfo } from "./ZKPublicKeyInfo";

export type QEDCheckpointSyncInfoCompact = { l2_block_state: QEDL2BlockState, stats: QEDCheckpointLeafStats, state_roots: QEDCheckpointGlobalStateRoots, checkpoint_tree_update_siblings: Array<QHashOut>, regsitered_users_start_pivot_siblings: Array<QHashOut>, registered_users: Array<ZKPublicKeyInfo>, old_checkpoint_leaf_hash: QHashOut, slot: bigint, };
