// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QEDCheckpointGlobalStateRoots } from "./QEDCheckpointGlobalStateRoots";
import type { QEDCheckpointLeaf } from "./QEDCheckpointLeaf";
import type { QEDL2BlockState } from "./QEDL2BlockState";
import type { QHashOut } from "./QHashOut";

export type QEDCheckpointCoreSyncInfo = { checkpoint_tree_root: QHashOut, checkpoint_leaf_hash: QHashOut, l2_block_state: QEDL2BlockState, checkpoint_leaf: QEDCheckpointLeaf, state_roots: QEDCheckpointGlobalStateRoots, };
