// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QEDContractLeaf } from "./QEDContractLeaf";
import type { QHashOut } from "./QHashOut";

export type QEDContractInclusionProof = { contract_leaf: QEDContractLeaf, contract_tree_merkle_proof: MerkleProofCore<QHashOut>, };
