// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QEDContractInclusionProof } from "./QEDContractInclusionProof";
import type { QHashOut } from "./QHashOut";

export type QEDContractFunctionInclusionProof = { contract_inclusion_proof: QEDContractInclusionProof, contract_function_merkle_proof: MerkleProofCore<QHashOut>, };
