// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type QEDCheckpointLeafCompact = { global_chain_root: QHashOut, stats_hash: QHashOut, };
