// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type QEDContractLeaf = { deployer: QHashOut, function_tree_root: QHashOut, state_tree_height: bigint, };
