// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type QEDUserLeaf = { public_key: QHashOut, user_state_tree_root: QHashOut, balance: bigint, nonce: bigint, last_checkpoint_id: bigint, event_index: bigint, user_id: bigint, };
