// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProvingJobCircuitType } from "./ProvingJobCircuitType";
import type { ProvingJobDataType } from "./ProvingJobDataType";
import type { QJobTopic } from "./QJobTopic";

export type QProvingJobDataID = { topic: QJobTopic, goal_id: bigint, circuit_type: ProvingJobCircuitType, group_id: number, sub_group_id: number, task_index: number, data_type: ProvingJobDataType, data_index: number, };
