// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimpleContractFunctionCodeDefinition } from "./SimpleContractFunctionCodeDefinition";

export type SimpleContractCodeDefinition = { state_tree_height: number, functions: Array<SimpleContractFunctionCodeDefinition>, };
