// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type SubTreeNodeStateTransition = { old_node_value: QHashOut, new_node_value: QHashOut, node_index: bigint, node_level: bigint, };
