// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type UPSEndCapResultCompact = { start_user_leaf_hash: QHashOut, end_user_leaf_hash: QHashOut, checkpoint_tree_root_hash: QHashOut, user_id: bigint, };
