// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { PartialUpdateNearestCommonAncestorProof } from "./PartialUpdateNearestCommonAncestorProof";
import type { QHashOut } from "./QHashOut";
import type { VerifyEndCapSimpleStandardInput } from "./VerifyEndCapSimpleStandardInput";

export type VerifyLeftEndCapRightGUTAInput = { checkpoint_tree_root: QHashOut, stats_b: GUTAStats, a_end_cap: VerifyEndCapSimpleStandardInput, nca_proof: PartialUpdateNearestCommonAncestorProof, guta_inclusion_proof_b: MerkleProofCore<QHashOut>, };
