// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTARegisterUserFullInput } from "./GUTARegisterUserFullInput";
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { QHashOut } from "./QHashOut";

export type VerifyGUTARegisterUsersCircuitInputSimple = { guta_proof_header: GlobalUserTreeAggregatorHeader, top_line_siblings: Array<QHashOut>, guta_register_user_inputs: Array<GUTARegisterUserFullInput>, };
