// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { PartialUpdateNearestCommonAncestorProof } from "./PartialUpdateNearestCommonAncestorProof";
import type { QHashOut } from "./QHashOut";

export type VerifyTwoGUTAProofGadgetStandardInput = { checkpoint_tree_root: QHashOut, b_checkpoint_tree_root: QHashOut, stats_a: GUTAStats, stats_b: GUTAStats, nca_proof: PartialUpdateNearestCommonAncestorProof, guta_inclusion_proof_a: MerkleProofCore<QHashOut>, guta_inclusion_proof_b: MerkleProofCore<QHashOut>, };
