// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";
import type { VerifyEndCapSimpleStandardInput } from "./VerifyEndCapSimpleStandardInput";

export type VerifySingleEndCapInput = { guta_circuit_whitelist: QHashOut, a_end_cap: VerifyEndCapSimpleStandardInput, start_user_leaf_hash: QHashOut, end_user_leaf_hash: QHashOut, user_id: bigint, };
