// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { PartialUpdateNearestCommonAncestorProof } from "./PartialUpdateNearestCommonAncestorProof";
import type { QHashOut } from "./QHashOut";

export type VerifyTwoGUTAProofUpgradeCheckpointStandardInputSimple = { historical_checkpoint_proof_a: MerkleProofCore<QHashOut>, historical_checkpoint_proof_b: MerkleProofCore<QHashOut>, stats_a: GUTAStats, stats_b: GUTAStats, nca_proof: PartialUpdateNearestCommonAncestorProof, };
