// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartialUpdateNearestCommonAncestorProof } from "./PartialUpdateNearestCommonAncestorProof";
import type { QHashOut } from "./QHashOut";
import type { VerifyEndCapSimpleStandardInput } from "./VerifyEndCapSimpleStandardInput";

export type VerifyTwoEndCapCircuitInput = { guta_circuit_whitelist: QHashOut, a_end_cap: VerifyEndCapSimpleStandardInput, b_end_cap: VerifyEndCapSimpleStandardInput, nca_proof: PartialUpdateNearestCommonAncestorProof, };
