// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type VerifyEndCapSimpleStandardInput = { guta_stats: GUTAStats, checkpoint_root: QHashOut, checkpoint_historical_merkle_proof: MerkleProofCore<QHashOut>, };
