// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QProvingJobDataID } from "./QProvingJobDataID";
import type { VerifyTwoEndCapCircuitInput } from "./VerifyTwoEndCapCircuitInput";

export type VerifyTwoEndCapCircuitWithIdsInput = { input: VerifyTwoEndCapCircuitInput, proof_a_id: QProvingJobDataID, proof_b_id: QProvingJobDataID, };
