// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { PartialUpdateNearestCommonAncestorProof } from "./PartialUpdateNearestCommonAncestorProof";
import type { QHashOut } from "./QHashOut";

export type VerifyTwoGUTAProofGadgetStandardInputSimple = { checkpoint_tree_root: QHashOut, b_checkpoint_tree_root: QHashOut, stats_a: GUTAStats, stats_b: GUTAStats, nca_proof: PartialUpdateNearestCommonAncestorProof, };
