// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type VerifyGUTAToCapUpgradeCheckpointCircuitInputSimple = { guta_proof_header: GlobalUserTreeAggregatorHeader, top_line_siblings: Array<QHashOut>, historical_checkpoint_proof: MerkleProofCore<QHashOut>, };
