#!/usr/bin/env bash
set -eo pipefail

# NOTE: if you make modifications to this script, please increment the version number.
# Major / minor: incremented for each stable release of Psy.
# Patch: incremented for each change between stable releases.
PSYUP_INSTALLER_VERSION="1.0.0"

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
Psy_DIR=${Psy_DIR:-"$BASE_DIR/.psy"}
Psy_VERSIONS_DIR="$Psy_DIR/versions"
Psy_BIN_DIR="$Psy_DIR/bin"
Psy_MAN_DIR="$Psy_DIR/share/man/man1"
Psy_BIN_URL="https://raw.githubusercontent.com/PsyProtocol/psy-v1/master/psyup/psyup"
Psy_BIN_PATH="$Psy_BIN_DIR/psyup"

PSYUP_JOBS=""

BINS=(psy_user_cli psy_node_cli psy_dev_cli dargo psy-lsp-server)

export RUSTFLAGS="${RUSTFLAGS:--C target-cpu=native}"

main() {
  need_cmd git
  need_cmd curl

  while [[ -n $1 ]]; do
    case $1 in
      --)               shift; break;;

      -v|--version)     shift; version;;
      -U|--update)      shift; update;;
      -r|--repo)        shift; PSYUP_REPO=$1;;
      -b|--branch)      shift; PSYUP_BRANCH=$1;;
      -i|--install)     shift; PSYUP_VERSION=$1;;
      -l|--list)        shift; list;;
      -u|--use)         shift; PSYUP_VERSION=$1; use;;
      -p|--path)        shift; PSYUP_LOCAL_REPO=$1;;
      -P|--pr)          shift; PSYUP_PR=$1;;
      -C|--commit)      shift; PSYUP_COMMIT=$1;;
      -j|--jobs)        shift; PSYUP_JOBS=$1;;
      --arch)           shift; PSYUP_ARCH=$1;;
      --platform)       shift; PSYUP_PLATFORM=$1;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        warn "unknown option: $1"
        usage
        exit 1
    esac; shift
  done

  CARGO_BUILD_ARGS=(--profile release)

  if [ -n "$PSYUP_JOBS" ]; then
    CARGO_BUILD_ARGS+=(--jobs "$PSYUP_JOBS")
  fi

  # Print the banner after successfully parsing args
  banner

  if [ -n "$PSYUP_PR" ]; then
    if [ -z "$PSYUP_BRANCH" ]; then
      PSYUP_BRANCH="refs/pull/$PSYUP_PR/head"
    else
      err "can't use --pr and --branch at the same time"
    fi
  fi

  check_bins_in_use

  # Installs Psy from a local repository if --path parameter is provided
  if [[ -n "$PSYUP_LOCAL_REPO" ]]; then
    need_cmd cargo

    # Ignore branches/versions as we do not want to modify local git state
    if [ -n "$PSYUP_REPO" ] || [ -n "$PSYUP_BRANCH" ] || [ -n "$PSYUP_VERSION" ]; then
      warn "--branch, --install, --use, and --repo arguments are ignored during local install"
    fi

    # Enter local repo and build
    say "installing from $PSYUP_LOCAL_REPO"
    cd "$PSYUP_LOCAL_REPO"
    
    # Set DARGO_STD_PATH for compilation
    export DARGO_STD_PATH="$PWD/psy_compiler/psy-std/std.psy"
    export SQLX_OFFLINE=true
    
    ensure cargo build --bins "${CARGO_BUILD_ARGS[@]}" --bin psy_user_cli --bin psy_node_cli --bin psy_dev_cli --bin dargo --bin psy-lsp-server

    for bin in "${BINS[@]}"; do
      # Remove prior installations if they exist
      rm -f "$Psy_BIN_DIR/$bin"
      # Symlink from local repo binaries to bin dir
      ensure ln -s "$PWD/target/release/$bin" "$Psy_BIN_DIR/$bin"
    done

    say "done"
    exit 0
  fi

  PSYUP_REPO=${PSYUP_REPO:-PsyProtocol/psy-v1}

  # Install by downloading binaries
  if [[ "$PSYUP_REPO" == "PsyProtocol/psy-v1" && -z "$PSYUP_BRANCH" && -z "$PSYUP_COMMIT" ]]; then
    PSYUP_VERSION=${PSYUP_VERSION:-stable}
    PSYUP_TAG=$PSYUP_VERSION

    # Normalize versions (handle channels, versions without v prefix
    if [[ "$PSYUP_VERSION" =~ ^nightly ]]; then
      PSYUP_VERSION="nightly"
    elif [[ "$PSYUP_VERSION" == [[:digit:]]* ]]; then
      # Add v prefix
      PSYUP_VERSION="v${PSYUP_VERSION}"
      PSYUP_TAG="${PSYUP_VERSION}"
    fi

    say "installing psy (version ${PSYUP_VERSION}, tag ${PSYUP_TAG})"

    uname_s=$(uname -s)
    PLATFORM=$(tolower "${PSYUP_PLATFORM:-$uname_s}")
    EXT="tar.gz"
    case $PLATFORM in
      linux|alpine) ;;
      darwin|mac*)
        PLATFORM="darwin"
        ;;
      mingw*|win*)
        EXT="zip"
        PLATFORM="win32"
        ;;
      *)
        err "unsupported platform: $PLATFORM"
        ;;
    esac

    uname_m=$(uname -m)
    ARCHITECTURE=$(tolower "${PSYUP_ARCH:-$uname_m}")
    if [ "${ARCHITECTURE}" = "x86_64" ]; then
      # Redirect stderr to /dev/null to avoid printing errors if non Rosetta.
      if [ "$(sysctl -n sysctl.proc_translated 2>/dev/null)" = "1" ]; then
        ARCHITECTURE="arm64" # Rosetta.
      else
        ARCHITECTURE="amd64" # Intel.
      fi
    elif [ "${ARCHITECTURE}" = "arm64" ] || [ "${ARCHITECTURE}" = "aarch64" ] ; then
      ARCHITECTURE="arm64" # Arm.
    else
      ARCHITECTURE="amd64" # Amd.
    fi

    # Compute the URL of the release tarball in the Psy repository.
    RELEASE_URL="https://github.com/${PSYUP_REPO}/releases/download/${PSYUP_TAG}/"
    BIN_ARCHIVE_URL="${RELEASE_URL}psy_${PSYUP_VERSION}_${PLATFORM}_${ARCHITECTURE}.$EXT"
    MAN_TARBALL_URL="${RELEASE_URL}psy_man_${PSYUP_VERSION}.tar.gz"

    ensure mkdir -p "$Psy_VERSIONS_DIR"
    # Download and extract the binaries archive
    say "downloading psy_user_cli, psy_node_cli, psy_dev_cli, dargo, and psy-lsp-server for $PSYUP_TAG version"
    if [ "$PLATFORM" = "win32" ]; then
      tmp="$(mktemp -d 2>/dev/null || echo ".")/psy.zip"
      ensure download "$BIN_ARCHIVE_URL" "$tmp"
      ensure unzip "$tmp" -d "$Psy_VERSIONS_DIR/$PSYUP_TAG"
      rm -f "$tmp"
    else
      tmp="$(mktemp -d 2>/dev/null || echo ".")/psy.tar.gz"
      ensure download "$BIN_ARCHIVE_URL" "$tmp"
      # Make sure it's a valid tar archive.
      ensure tar tf $tmp 1> /dev/null
      ensure mkdir -p "$Psy_VERSIONS_DIR/$PSYUP_TAG"
      ensure tar -C "$Psy_VERSIONS_DIR/$PSYUP_TAG" -xvf $tmp
      rm -f "$tmp"
    fi

    # Optionally download the manuals
    if check_cmd tar; then
      say "downloading manpages"
      mkdir -p "$Psy_MAN_DIR"
      download "$MAN_TARBALL_URL" | tar -xzC "$Psy_MAN_DIR" 2>/dev/null || say "manpage download failed, continuing..."
    else
      say 'skipping manpage download: missing "tar"'
    fi

    # Use newly installed version.
    PSYUP_VERSION=$PSYUP_TAG
    use

    say "done!"

  # Install by cloning the repo with the provided branch/tag
  else
    need_cmd cargo
    PSYUP_BRANCH=${PSYUP_BRANCH:-main}
    REPO_PATH="$Psy_DIR/$PSYUP_REPO"
    AUTHOR="$(echo "$PSYUP_REPO" | cut -d'/' -f1 -)"

    # If repo path does not exist, grab the author from the repo, make a directory in .psy, cd to it and clone.
    if [ ! -d "$REPO_PATH" ]; then
      ensure mkdir -p "$Psy_DIR/$AUTHOR"
      cd "$Psy_DIR/$AUTHOR"
      ensure git clone "https://github.com/$PSYUP_REPO"
    fi

    # Force checkout, discarding any local changes
    cd "$REPO_PATH"
    ensure git fetch origin "${PSYUP_BRANCH}:remotes/origin/${PSYUP_BRANCH}"
    ensure git checkout "origin/${PSYUP_BRANCH}"

    # Create custom version based on the install method, e.g.:
    # - PsyProtocol-commit-c22c4cc96b0535cd989ee94b79da1b19d236b8db
    # - PsyProtocol-pr-1
    # - PsyProtocol-branch-chore-bump-forge-std
    if [ -n "$PSYUP_COMMIT" ]; then
      # If set, checkout specific commit from branch
      ensure git checkout "$PSYUP_COMMIT"
      PSYUP_VERSION=$AUTHOR-commit-$PSYUP_COMMIT
    elif [ -n "$PSYUP_PR" ]; then
     PSYUP_VERSION=$AUTHOR-pr-$PSYUP_PR
    else
      if [ -n "$PSYUP_BRANCH" ]; then
        NORMALIZED_BRANCH="$(echo "$PSYUP_BRANCH" | tr / -)"
        PSYUP_VERSION=$AUTHOR-branch-$NORMALIZED_BRANCH
      fi
    fi
    say "installing version $PSYUP_VERSION"

    # Set required environment variables for Psy build
    export DARGO_STD_PATH="$PWD/psy_compiler/psy-std/std.psy"
    export SQLX_OFFLINE=true

    # Build the repo.
    ensure cargo build --bins "${CARGO_BUILD_ARGS[@]}" --bin psy_user_cli --bin psy_node_cli --bin psy_dev_cli --bin dargo --bin psy-lsp-server
    # Create Psy custom version directory.
    ensure mkdir -p "$Psy_VERSIONS_DIR/$PSYUP_VERSION"
    for bin in "${BINS[@]}"; do
      for try_path in target/release/$bin target/release/$bin.exe; do
        if [ -f "$try_path" ]; then
          mv -f "$try_path" "$Psy_VERSIONS_DIR/$PSYUP_VERSION"
        fi
      done
    done

    # Use newly built version.
    use

    # If help2man is installed, use it to add Psy man pages.
    if check_cmd help2man; then
      for bin in "${BINS[@]}"; do
        help2man -N "$Psy_BIN_DIR/$bin" > "$Psy_MAN_DIR/$bin.1" 2>/dev/null || true
      done
    fi

    say "done"
  fi
}

usage() {
  cat 1>&2 <<EOF
The installer for Psy.

Update or revert to a specific Psy version with ease.

By default, the latest stable version is installed from built binaries.

USAGE:
    psyup <OPTIONS>

OPTIONS:
    -h, --help      Print help information
    -v, --version   Print the version of psyup
    -U, --update    Update psyup to the latest version
    -i, --install   Install a specific version from built binaries
    -l, --list      List versions installed from built binaries
    -u, --use       Use a specific installed version from built binaries
    -b, --branch    Build and install a specific branch
    -P, --pr        Build and install a specific Pull Request
    -C, --commit    Build and install a specific commit
    -r, --repo      Build and install from a remote GitHub repo (uses default branch if no other options are set)
    -p, --path      Build and install a local repository
    -j, --jobs      Number of CPUs to use for building Psy (default: all CPUs)
    --arch          Install a specific architecture (supports amd64 and arm64)
    --platform      Install a specific platform (supports win32, linux, darwin and alpine)
EOF
}

version() {
  say "$PSYUP_INSTALLER_VERSION"
  exit 0
}

update() {
  say "updating psyup..."

  # Download to a temporary file first
  tmp_file="$(mktemp)"
  ensure download "$Psy_BIN_URL" "$tmp_file"

  # Replace the current psyup with the downloaded file
  ensure mv "$tmp_file" "$Psy_BIN_PATH"
  ensure chmod +x "$Psy_BIN_PATH"

  say "successfully updated psyup"
  exit 0
}

list() {
  if [ -d "$Psy_VERSIONS_DIR" ]; then
    for VERSION in $Psy_VERSIONS_DIR/*; do
      say "${VERSION##*/}"
      for bin in "${BINS[@]}"; do
        bin_path="$VERSION/$bin"
        say "- $("$bin_path" --version 2>/dev/null || echo "$bin (version unavailable)")"
      done
      printf "\n"
    done
  else
    for bin in "${BINS[@]}"; do
      bin_path="$Psy_BIN_DIR/$bin"
      say "- $("$bin_path" --version 2>/dev/null || echo "$bin (version unavailable)")"
    done
  fi
  exit 0
}

use() {
  [ -z "$PSYUP_VERSION" ] && err "no version provided"
  Psy_VERSION_DIR="$Psy_VERSIONS_DIR/$PSYUP_VERSION"
  if [ -d "$Psy_VERSION_DIR" ]; then

    check_bins_in_use

    for bin in "${BINS[@]}"; do
      bin_path="$Psy_BIN_DIR/$bin"
      cp "$Psy_VERSION_DIR/$bin" "$bin_path"
      # Print usage msg
      say "use - $("$bin_path" --version 2>/dev/null || echo "$bin (version unavailable)")"

      # Check if the default path of the binary is not in Psy_BIN_DIR
      which_path="$(command -v "$bin" || true)"
      if [ -n "$which_path" ] && [ "$which_path" != "$bin_path" ]; then
        warn ""
        cat 1>&2 <<EOF
There are multiple binaries with the name '$bin' present in your 'PATH'.
This may be the result of installing '$bin' using another method,
like Cargo or other package managers.
You may need to run 'rm $which_path' or move '$Psy_BIN_DIR'
in your 'PATH' to allow the newly installed version to take precedence!

EOF
      fi
    done
    exit 0
  else
    err "version $PSYUP_VERSION not installed"
  fi
}

say() {
  printf "psyup: %s\n" "$1"
}

warn() {
  say "warning: ${1}" >&2
}

err() {
  say "$1" >&2
  exit 1
}

tolower() {
  echo "$1" | awk '{print tolower($0)}'
}

need_cmd() {
  if ! check_cmd "$1"; then
    err "need '$1' (command not found)"
  fi
}

check_cmd() {
  command -v "$1" &>/dev/null
}

check_bins_in_use() {
  if check_cmd pgrep; then
    for bin in "${BINS[@]}"; do
      if pgrep -x "$bin" >/dev/null; then
        err "Error: '$bin' is currently running. Please stop the process and try again."
      fi
    done
  else
    warn "Make sure no Psy process is running during the install process!"
  fi
}

# Run a command that should never fail. If the command fails execution
# will immediately terminate with an error showing the failing command.
ensure() {
  if ! "$@"; then err "command failed: $*"; fi
}

# Downloads $1 into $2 or stdout
download() {
  if [ -n "$2" ]; then
    # output into $2
    if check_cmd curl; then
      curl -#o "$2" -L "$1"
    else
      wget --show-progress -qO "$2" "$1"
    fi
  else
    # output to stdout
    if check_cmd curl; then
      curl -#L "$1"
    else
      wget --show-progress -qO- "$1"
    fi
  fi
}

# Banner Function for Psy
banner() {
  printf '

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

 ╔═╗ ╔═╗ ╔╦╗     Programmable and modular toolkit
 ║═╬╗║╣   ║║      for Zero-Knowledge proofs and 
 ╚═╝╚╚═╝ ═╩╝     rollup-as-a-service infrastructure.

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

Repo       : https://github.com/PsyProtocol/psy-v1
Docs       : https://docs.psy.xyz/
Chat       : https://discord.gg/psyprotocol

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

'
}


main "$@"