use plonky2::plonk::config::PoseidonGoldilocksConfig;
use qed_common_circuit::circuits::traits::qstandard::QStandardCircuit;
use qed_core::{config::network_constants::QED_NETWORK_MAGIC_REGTEST, job::id::ProvingJobCircuitType};
use qed_crypto::common::{circuit_library::CircuitInfoLibraryBuilder, simple_circuit_library::SimpleCircuitLibrary};
use qed_prover::ups::circuit_manager::core::QEDUPSStepCircuitManager;
use qed_rollup_circuit::{coordinator::coordinator_helper::QEDCoordinatorCircuitManager, guta::guta_helper::QEDGUTACircuitManager};
use qed_data::config::store_config::QEDFelt;

fn run_gen_config() -> anyhow::Result<()> {

    const D: usize = 2;
    type C = PoseidonGoldilocksConfig;
    type F = QEDFelt;
    let mut library = SimpleCircuitLibrary::<F>::new();

    let main_circuits = QEDUPSStepCircuitManager::<C, D>::new_with_config(QED_NETWORK_MAGIC_REGTEST);
    
    library.register_circuit(
        ProvingJobCircuitType::UserEndCap,
        main_circuits.ups_end_cap.get_fingerprint(),
        main_circuits.ups_end_cap.get_verifier_config_ref().into(),
    );


    let guta_circuits = QEDGUTACircuitManager::<C,D>::new_with_config(
        main_circuits.ups_end_cap.get_common_circuit_data_ref(),
        main_circuits.ups_end_cap.get_verifier_config_ref().constants_sigmas_cap.height(),
        main_circuits.ups_end_cap.get_fingerprint(),
    );

    let coordinator_circuits = QEDCoordinatorCircuitManager::<C,D>::new_with_guta(guta_circuits);

    coordinator_circuits.register_library(&mut library);


    let lib_ser = library.to_serialized();

    let data = serde_json::to_string(&lib_ser)?;
    println!(r#"// AUTOGENERATED - DO NOT MODIFY

use plonky2::hash::hash_types::RichField;

use super::simple_circuit_library::{{SerializableSimpleCircuitLibrary, SimpleCircuitLibrary}};

pub fn get_cached_circuit_library<F: RichField>() -> SimpleCircuitLibrary<F> {{
    SimpleCircuitLibrary::from_serialized(
        serde_json::from_str::<SerializableSimpleCircuitLibrary<F>>(
            r{}"{}"{}
        ).unwrap()
    )
}}"#,"#",data,"#");


    Ok(())
}
fn main() {
    run_gen_config().unwrap();
}
