[package]
edition = "2021"
name    = "psy-parser"
version = "0.1.0"

[dependencies]
psy-ast = { workspace = true }
psy-lexer = { workspace = true }
lalrpop-util = { workspace = true }
psy-common = { workspace = true }
thiserror = { workspace = true }
psy_vm = { workspace = true }
indexmap = { workspace = true }

[build-dependencies]
lalrpop = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
