[package]
edition = "2021"
name    = "psy_plonky2_worker"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["std", "parth_core/serialize_rkyv", "parth_core/serialize_speedy", "parth_core/serialize_postcard"]
std = ["parth_core/std", "pser/std", "psy_data/std"]
serialize_rkyv = ["dep:rkyv","pser/serialize_rkyv", "parth_core/serialize_rkyv", "psy_data/serialize_rkyv"]
serialize_speedy = ["dep:speedy", "pser/serialize_speedy", "parth_core/serialize_speedy", "psy_data/serialize_speedy"]
serialize_postcard = ["dep:postcard", "pser/serialize_postcard", "parth_core/serialize_postcard", "psy_data/serialize_postcard"]

[dependencies]
postcard = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
anyhow     = { workspace = true }
async-trait      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true}
rand = { workspace = true }
auto_impl = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
hashbrown = { workspace = true }
plonky2 = { workspace = true }

# start local packages
parth_core = { workspace = true }
psy_plonky2_basic_helpers = { workspace = true }
psy_core = { workspace = true }
psy_data = { workspace = true }
pser = { workspace = true }
