use plonky2::plonk::config::PoseidonGoldilocksConfig;
use psy_common_circuit::circuits::traits::qstandard::QStandardCircuit;
use psy_core::{config::network_constants::Psy_NETWORK_MAGIC_REGTEST, job::id::ProvingJobCircuitType};
use psy_crypto::common::{circuit_library::CircuitInfoLibraryBuilder, simple_circuit_library::SimpleCircuitLibrary};
use psy_data::config::store_config::PsyFelt;
use psy_network_circuit::{coordinator::coordinator_helper::PsyCoordinatorCircuitManager, guta::guta_helper::PsyGUTACircuitManager};
use psy_prover::ups::circuit_manager::core::PsyUPSStepCircuitManager;

fn run_gen_config() -> anyhow::Result<()> {
    const D: usize = 2;
    type C = PoseidonGoldilocksConfig;
    type F = PsyFelt;
    let mut library = SimpleCircuitLibrary::<F>::new();

    let main_circuits = PsyUPSStepCircuitManager::<C, D>::new_with_config(Psy_NETWORK_MAGIC_REGTEST);

    library.register_circuit(
        ProvingJobCircuitType::UserEndCap,
        main_circuits.ups_end_cap.get_fingerprint(),
        main_circuits.ups_end_cap.get_verifier_config_ref().into(),
    );

    use psy_core::config::network_constants::get_default_worker_public_key;

    let guta_circuits = PsyGUTACircuitManager::<C, D>::new_with_config(
        main_circuits.ups_end_cap.get_common_circuit_data_ref(),
        main_circuits.ups_end_cap.get_verifier_config_ref().constants_sigmas_cap.height(),
        main_circuits.ups_end_cap.get_fingerprint(),
        get_default_worker_public_key::<F>(),
    );

    let coordinator_circuits = PsyCoordinatorCircuitManager::<C, D>::new_with_guta(guta_circuits, get_default_worker_public_key::<F>());

    coordinator_circuits.register_library(&mut library);

    let lib_ser = library.to_serialized();

    let data = serde_json::to_string(&lib_ser)?;
    println!(
        r#"// AUTOGENERATED - DO NOT MODIFY

use plonky2::hash::hash_types::RichField;

use super::simple_circuit_library::{{SerializableSimpleCircuitLibrary, SimpleCircuitLibrary}};

pub fn get_cached_circuit_library<F: RichField>() -> SimpleCircuitLibrary<F> {{
    SimpleCircuitLibrary::from_serialized(
        serde_json::from_str::<SerializableSimpleCircuitLibrary<F>>(
            r{}"{}"{}
        ).unwrap()
    )
}}"#,
        "#", data, "#"
    );

    Ok(())
}
fn main() {
    run_gen_config().unwrap();
}
