[package]
edition = "2021"
name = "qed_node"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
bincode      = { workspace = true }
async-recursion = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
hex = { workspace = true }
plonky2 = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
kvq = { workspace = true }
psy_core = { workspace = true }
qed_common_circuit = { workspace = true }
qed_rollup_circuit = { workspace = true }
psy_data = { workspace = true }
psy_crypto = { workspace = true }
qed_store = { workspace = true }
qed_api_services = { workspace = true }
psy_vm = { workspace = true }

indexmap = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
fred = { workspace = true }
once_cell = { workspace = true }
redis = { workspace = true }
bb8-redis = { workspace = true }
bb8 = { workspace = true }
rsmq = { workspace = true }
url = { workspace = true }

# Dependencies from other qed crates
jsonrpsee = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
serde_with = { workspace = true }
qed_rollup_utils = { workspace = true }
hyper = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
reqwest = { workspace = true }
jsonwebtoken = { workspace = true }
qed_prover = { workspace = true }
http = { workspace = true }
axum = { workspace = true }
headers = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
auto_impl = { workspace = true }
uuid = { workspace = true }
secp256k1 = { workspace = true }
k256 = { workspace = true }
ecdsa = { workspace = true }
alloy-primitives = { workspace = true }
sha2 = { workspace = true }
aws-config = "1.0"
aws-sdk-s3 = "1.0"
