[package]
edition = "2021"
name    = "qed_node"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
bincode      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
lazy_static = { workspace = true }
plonky2 = { workspace = true }
twox-hash = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
kvq = { path = "../kvq" }
kvq_store_lmdbx = { path = "../kvq_store_lmdbx" }
qed_core = { path = "../qed_core" }
qed_common_circuit = { path = "../qed_common_circuit" }
qed_rollup_circuit = { path = "../qed_rollup_circuit" }
qed_data = { path = "../qed_data" }
qed_crypto = { path = "../qed_crypto" }
qed_store = { path = "../qed_store" }
qed_node_common = { path = "../qed_node_common" }

rand = { workspace = true }
log = { workspace = true }

tokio = { workspace = true }
futures = { workspace = true }


lapin = "=2.5.0"
#prost-wkt-types = "0.6.0"

tokio-executor-trait = { workspace = true }
tokio-reactor-trait = { workspace = true }
fred = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = { workspace = true }
redis ={ workspace = true }
amqprs = "=2.1.0"
rsmq = { git = "https://github.com/GopherJ/rsmq-async-rs", rev = "2af5a5c06a0341cb60f73ba0f0af066f65fb5e77", default-features = false }
r2d2 = { git = "https://github.com/GopherJ/r2d2", rev = "976ca74a74871d78764da2a040edcadad1af9be9" }
r2d2_redis = { git = "https://github.com/GopherJ/r2d2-redis", rev = "63be37454cf441b832251aa915b1a9cb8bc27bff" }
broccoli_queue = { version = "0.3.3", features = ["redis"] }
rabbitmq-stream-client = "0.8.0"
