[package]
edition = "2021"
name    = "qed_benchmark"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
bincode      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
lazy_static = { workspace = true }
plonky2 = { workspace = true }
twox-hash = { workspace = true }
tracing = { workspace = true }

kvq = { path = "../kvq" }
qed_core = { path = "../qed_core" }
qed_common_circuit = { path = "../qed_common_circuit" }
qed_rollup_circuit = { path = "../qed_rollup_circuit" }
qedlang_core = { path = "../qedlang_core" }
qed_data = { path = "../qed_data" }
qed_crypto = { path = "../qed_crypto" }
qed_store = { path = "../qed_store" }
qed_exec = { path = "../qed_exec" }
qedlang_macros = { path = "../qed_compiler/qedlang_macros" }
qed_prover = { path = "../qed_prover" }
qed_node = { path = "../qed_node" }
qed_node_common = { path = "../qed_node_common" }



tokio = { workspace = true }

fred = { workspace = true }
