[package]
name = "reth-libmdbx"
description = "Idiomatic and safe MDBX wrapper"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "Apache-2.0"

[dependencies]
reth-mdbx-sys = { path = "./mdbx-sys" }

bitflags = { workspace = true }
byteorder = { workspace = true }
derive_more = "0.99"
indexmap = { workspace = true }
parking_lot = { workspace = true }
smallvec = { workspace = true }
thiserror = "1.0"
tracing = { workspace = true }

dashmap = { version = "5.5", features = ["inline"], optional = true }

[features]
default = []
return-borrowed = []
read-tx-timeouts = ["dep:dashmap"]

[dev-dependencies]
pprof = { version = "0.13", features = ["flamegraph", "frame-pointer", "criterion"] }
criterion = "0.5"
rand = "0.8"
tempfile = "3.8"

[[bench]]
name = "cursor"
harness = false

[[bench]]
name = "transaction"
harness = false