[package]
edition = "2021"
name    = "psy-sema"
version = "0.1.0"

[dependencies]
psy-ast = { workspace = true }
thiserror = { workspace = true }
psy-common = { workspace = true }
psy-fmt = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
indexmap = { workspace = true }
anyhow = { workspace = true }
enum-as-inner = { workspace = true }
psy_vm = { workspace = true }
derivative = { workspace = true }
itertools = { workspace = true }

petgraph = { workspace = true }
rangemap = { workspace = true }
