[package]
edition = "2021"
name    = "psy_prover"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Minimal core dependencies for WASM
maybe-async = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
plonky2 = { workspace = true }
tracing = { workspace = true }
ts-rs = { workspace = true }

psy_common = { workspace = true }
psy_config = { workspace = true }
psy_common_circuit = { workspace = true, default-features = false }
psy_network_circuit = { workspace = true, default-features = false }
psy_dpn_circuit = { workspace = true, default-features = false }
psy_vm = { workspace = true }
psy_data = { workspace = true, default-features = false }
psy_crypto = { workspace = true }
psy_provider = { workspace = true }
psy_ups_circuit = { workspace = true, default-features = false }

k256 = { workspace = true }
rand = { workspace = true }
getrandom = { workspace = true }
hex = {workspace = true}
dashmap = { workspace = true }

# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
kvq = { workspace = true }
psy_store = { workspace = true, default-features = false }
futures = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
jsonrpsee = { workspace = true }
reqwest = { workspace = true }
sodalite = { workspace = true }
secp256k1 = { workspace = true }
bincode = { workspace = true }
dirs = {workspace = true}
rpassword = { workspace = true }
rayon = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-primitives = { workspace = true }
parking_lot = { workspace = true}
http = { workspace = true }
clap = { workspace = true }
dashmap = { workspace = true }
quick_cache = { workspace = true }

# WASM-only dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { workspace = true }
wasm-logger = { workspace = true }
wasm-tracing = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Window"] }
js-sys = { workspace = true }

[features]
# default = ["is_sync"]
is_sync = [
    "maybe-async/is_sync",
]
