import { ProvingJobCircuitType } from "./id";

const CityJobNames: Record<ProvingJobCircuitType, string> = {
    [ProvingJobCircuitType.RegisterUser]: "Register User",
    [ProvingJobCircuitType.RegisterUserAggregate]: "Aggregate Register User Proofs",
    [ProvingJobCircuitType.AddL1Deposit]: "Add Deposit",
    [ProvingJobCircuitType.AddL1DepositAggregate]: "Aggregate Add Deposit Proofs",
    [ProvingJobCircuitType.ClaimL1Deposit]: "Claim Deposit",
    [ProvingJobCircuitType.ClaimL1DepositAggregate]: "Aggregate Claim Deposit Proofs",
    [ProvingJobCircuitType.TransferTokensL2]: "Transfer Tokens",
    [ProvingJobCircuitType.TransferTokensL2Aggregate]: "Aggregate Transfer Proofs",
    [ProvingJobCircuitType.AddL1Withdrawal]: "Add Withdrawal",
    [ProvingJobCircuitType.AddL1WithdrawalAggregate]: "Aggregate Add Withdrawal Proofs",
    [ProvingJobCircuitType.ProcessL1Withdrawal]: "Process Withdrawal",
    [ProvingJobCircuitType.ProcessL1WithdrawalAggregate]: "Aggregate Process Withdrawal Proofs",
    [ProvingJobCircuitType.GenerateRollupStateTransitionProof]: "Rollup State Transition Proof",
    [ProvingJobCircuitType.GenerateSigHashIntrospectionProof]: "SigHash Introspection Proof",
    [ProvingJobCircuitType.GenerateFinalSigHashProof]: "Final SigHash Proof",
    [ProvingJobCircuitType.GenerateFinalSigHashProofGroth16]: "Generate Final SigHash Proof Groth16",
    [ProvingJobCircuitType.WrapFinalSigHashProofBLS12381]: "Wrap Final SigHash Proof BLS12381",
    [ProvingJobCircuitType.AggUserRegisterClaimDepositL2Transfer]:
        "Aggregate Proofs: [User Register, Claim Deposit, Transfer]",
    [ProvingJobCircuitType.AggAddProcessL1WithdrawalAddL1Deposit]:
        "Aggregate Proofs: [Add/Process Withdrawals, Add Deposit]",
    [ProvingJobCircuitType.DummyRegisterUserAggregate]: "Dummy Aggregate Register User Proofs",
    [ProvingJobCircuitType.DummyAddL1DepositAggregate]: "Dummy Aggregate Add Deposit Proofs",
    [ProvingJobCircuitType.DummyClaimL1DepositAggregate]: "Dummy Aggregate Claim Deposit Proofs",
    [ProvingJobCircuitType.DummyTransferTokensL2Aggregate]: "Dummy Aggregate Transfer Proofs",
    [ProvingJobCircuitType.DummyAddL1WithdrawalAggregate]: "Dummy Aggregate Add Withdrawal Proofs",
    [ProvingJobCircuitType.DummyProcessL1WithdrawalAggregate]: "Dummy Aggregate Process Withdrawal Proofs",
    [ProvingJobCircuitType.WrappedSignatureProof]: "Wrapped Signature Proof",
    [ProvingJobCircuitType.Secp256K1SignatureProof]: "Secp256K1 Signature Proof",
    [ProvingJobCircuitType.Unknown]: "Unknown",
};

/*
const CityWidgetNames: Record<ProvingJobCircuitType, string> = {
  [ProvingJobCircuitType.RegisterUser]: "Register\nUser",
  [ProvingJobCircuitType.RegisterUserAggregate]: "[AGG]\nRegister\nUser",
  [ProvingJobCircuitType.AddL1Deposit]: "Add L1\nDeposit",
  [ProvingJobCircuitType.AddL1DepositAggregate]: "[AGG]\nAdd L1\nDeposit",
  [ProvingJobCircuitType.ClaimL1Deposit]: "Claim\nDeposit",
  [ProvingJobCircuitType.ClaimL1DepositAggregate]: "[AGG]\nClaim\nDeposit",
  [ProvingJobCircuitType.TransferTokensL2]: "Transfer\nTokens",
  [ProvingJobCircuitType.TransferTokensL2Aggregate]: "[AGG]\nTransfer\nTokens",
  [ProvingJobCircuitType.AddL1Withdrawal]: "Add\nWithdrawal",
  [ProvingJobCircuitType.AddL1WithdrawalAggregate]: "[AGG]\nAdd\nWithdrawal",
  [ProvingJobCircuitType.ProcessL1Withdrawal]: "Process\nWithdrawal",
  [ProvingJobCircuitType.ProcessL1WithdrawalAggregate]: "[AGG]\nProcess\nWithdrawal",
  [ProvingJobCircuitType.GenerateRollupStateTransitionProof]: "State\nTransition",
  [ProvingJobCircuitType.GenerateSigHashIntrospectionProof]: "SigHash\nIntrospection",
  [ProvingJobCircuitType.GenerateFinalSigHashProof]: "Final\nSigHash",
  [ProvingJobCircuitType.GenerateFinalSigHashProofGroth16]: "Final\nSigHash (G16)",
  [ProvingJobCircuitType.WrapFinalSigHashProofBLS12381]: "Final\nSigHash\n(Groth16)",
  [ProvingJobCircuitType.AggUserRegisterClaimDepositL2Transfer]: "Register Users\nClaim Deposits\nTransfers",
  [ProvingJobCircuitType.AggAddProcessL1WithdrawalAddL1Deposit]: "Add+Process\nWithdrawals\nAdd Deposits",
  [ProvingJobCircuitType.DummyRegisterUserAggregate]: "Dummy\nRegister\nUser",
  [ProvingJobCircuitType.DummyAddL1DepositAggregate]: "Dummy Add L1 Deposit Aggregate",
  [ProvingJobCircuitType.DummyClaimL1DepositAggregate]: "Dummy Claim L1 Deposit Aggregate",
  [ProvingJobCircuitType.DummyTransferTokensL2Aggregate]: "Dummy Transfer Tokens L2 Aggregate",
  [ProvingJobCircuitType.DummyAddL1WithdrawalAggregate]: "Dummy Add L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.DummyProcessL1WithdrawalAggregate]: "Dummy Process L1 Withdrawal Aggregate",
  [ProvingJobCircuitType.WrappedSignatureProof]: "Wrapped Signature Proof",
  [ProvingJobCircuitType.Secp256K1SignatureProof]: "Secp256K1 Signature Proof",
  [ProvingJobCircuitType.Unknown]: "Unknown",
};
*/

const CityWidgetNames: Record<ProvingJobCircuitType, string> = {
    [ProvingJobCircuitType.RegisterUser]: "Register User",
    [ProvingJobCircuitType.RegisterUserAggregate]: " [AGG]\nRegister User",
    [ProvingJobCircuitType.AddL1Deposit]: "Add L1 Deposit",
    [ProvingJobCircuitType.AddL1DepositAggregate]: " [AGG]\nAdd L1 Deposit",
    [ProvingJobCircuitType.ClaimL1Deposit]: "Claim Deposit",
    [ProvingJobCircuitType.ClaimL1DepositAggregate]: " [AGG]\nClaim Deposit",
    [ProvingJobCircuitType.TransferTokensL2]: "Transfer Tokens",
    [ProvingJobCircuitType.TransferTokensL2Aggregate]: " [AGG]\nTransfer Tokens",
    [ProvingJobCircuitType.AddL1Withdrawal]: "Add Withdrawal",
    [ProvingJobCircuitType.AddL1WithdrawalAggregate]: " [AGG]\nAdd Withdrawal",
    [ProvingJobCircuitType.ProcessL1Withdrawal]: "Process Withdrawal",
    [ProvingJobCircuitType.ProcessL1WithdrawalAggregate]: " [AGG]\nProcess Withdrawal",
    [ProvingJobCircuitType.GenerateRollupStateTransitionProof]: "State Transition",
    [ProvingJobCircuitType.GenerateSigHashIntrospectionProof]: "SigHash Introspection",
    [ProvingJobCircuitType.GenerateFinalSigHashProof]: "Final SigHash",
    [ProvingJobCircuitType.GenerateFinalSigHashProofGroth16]: "Final SigHash\n(G16)",
    [ProvingJobCircuitType.WrapFinalSigHashProofBLS12381]: "Groth16 SigHash",
    [ProvingJobCircuitType.AggUserRegisterClaimDepositL2Transfer]: "Register Users\nClaim Deposits\nTransfers",
    [ProvingJobCircuitType.AggAddProcessL1WithdrawalAddL1Deposit]: "Add Withdrawals\nProcess Withdrawals\nAdd Deposits",
    [ProvingJobCircuitType.DummyRegisterUserAggregate]: "[DUMMY AGG]\nRegister User",
    [ProvingJobCircuitType.DummyAddL1DepositAggregate]: "[DUMMY AGG]\nAdd L1 Deposit",
    [ProvingJobCircuitType.DummyClaimL1DepositAggregate]: "[DUMMY AGG]\nClaim L1 Deposit",
    [ProvingJobCircuitType.DummyTransferTokensL2Aggregate]: "[DUMMY AGG]\nTransfer Tokens L2",
    [ProvingJobCircuitType.DummyAddL1WithdrawalAggregate]: "[DUMMY AGG]\nAdd L1 Withdrawal",
    [ProvingJobCircuitType.DummyProcessL1WithdrawalAggregate]: "[DUMMY AGG]\nProcess L1 Withdrawal",
    [ProvingJobCircuitType.WrappedSignatureProof]: "Wrapped Signature Proof",
    [ProvingJobCircuitType.Secp256K1SignatureProof]: "Secp256K1 Signature Proof",
    [ProvingJobCircuitType.Unknown]: "Unknown",
};

export { CityJobNames, CityWidgetNames };
