[package]
edition = "2021"
name    = "psy_common"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_with = { workspace = true }
serde_repr = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
plonky2 = { workspace = true }
rand = { workspace = true }
bincode = { workspace = true }
async-trait = { workspace = true }
indexmap = { workspace = true }

ts-rs = { workspace = true }
k256 = { workspace = true }

kvq = { workspace = true }
uuid = { workspace = true }
strum_macros = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }

# Additional dependencies from merged psy-common
thiserror = { workspace = true }
clap = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jsonwebtoken = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
