use serde::{Deserialize, Serialize};

use crate::protocol::core_types::QHashBase;


#[pderive::serialize_copy]
#[serde(bound = "for<'de2> Hash: Deserialize<'de2>")]
pub struct QParthProofPublicInputsPreimage<Hash: QHashBase> {
    pub index: u64, // this index of the node in the merkle tree that this proof is proving updates to
    pub level: u8, // the level of the node in the merkle tree that this proof is proving updates to, 0 = root, tree_height = leaf
    pub old_node_value: Hash, // the old value of the node in the merkle tree that this proof proves an update to
    pub new_node_value: Hash, // the new value of the node in the merkle tree that this proof proves an update to
    pub rewards_hash_commitment: Hash, // hash(hash_two_to_one(left_child_reward_commitment, right_child_reward_commitment), new_reward_info_hash), for end cap proofs this is the zero hash
    pub checkpoint_tree_root: Hash, // hash of the checkpoint tree root that this operation is synced to, "the state of the block chain that this proof is aware of"
    pub parth_whitelist_root: Hash, // root of merkle tree which contains the whitelist of valid circuits for recursion
    pub total_guta_proofs_generated: u64, // total proofs generated by miners to get to this point, for end cap proofs this is 0, for guta proofs this is the sum of the two child proofs + 1
    pub total_user_updates: u64, // total user updates that have happened in the tree up to and including this proof, for end cap proofs this is 1, for guta proofs this is the sum of the two child proofs
    pub total_fees_paid: u64, // total fees paid by users in the tree up to and including this proof, for end cap proofs this is the fee paid by the user, for guta proofs this is the sum of the two child proofs
}

impl<Hash: QHashBase> QParthProofPublicInputsPreimage<Hash> {
    pub fn get_combined_preimage(left: &Self, right: &Self, new_rewards_hash_commitment: Hash, old_node_value: Hash, new_node_value: Hash, level: u8, index: u64, checkpoint_tree_root: Hash, parth_whitelist_root: Hash) -> Self {
        Self {
            index,
            level,
            old_node_value,
            new_node_value,
            rewards_hash_commitment: new_rewards_hash_commitment,
            checkpoint_tree_root,
            total_guta_proofs_generated: left.total_guta_proofs_generated + right.total_guta_proofs_generated + 1,
            total_user_updates: left.total_user_updates + right.total_user_updates,
            total_fees_paid: left.total_fees_paid + right.total_fees_paid,
            parth_whitelist_root,
        }
    }
}



#[derive(Clone, PartialEq, Eq, Debug, Serialize, Deserialize, Copy)]
#[serde(bound = "for<'de2> Hash: Deserialize<'de2>")]
pub struct QParthProofPublicInputsPreimageWithoutRewardsHash<Hash: QHashBase> {
    pub index: u64, // this index of the node in the merkle tree that this proof is proving updates to
    pub level: u8, // the level of the node in the merkle tree that this proof is proving updates to, 0 = root, tree_height = leaf
    pub old_node_value: Hash, // the old value of the node in the merkle tree that this proof proves an update to
    pub new_node_value: Hash, // the new value of the node in the merkle tree that this proof proves an update to
    pub checkpoint_tree_root: Hash, // hash of the checkpoint tree root that this operation is synced to, "the state of the block chain that this proof is aware of"
    pub parth_whitelist_root: Hash, // root of merkle tree which contains the whitelist of valid circuits for recursion
    pub total_guta_proofs_generated: u64, // total proofs generated by miners to get to this point, for end cap proofs this is 0, for guta proofs this is the sum of the two child proofs + 1
    pub total_user_updates: u64, // total user updates that have happened in the tree up to and including this proof, for end cap proofs this is 1, for guta proofs this is the sum of the two child proofs
    pub total_fees_paid: u64, // total fees paid by users in the tree up to and including this proof, for end cap proofs this is the fee paid by the user, for guta proofs this is the sum of the two child proofs
}

impl<Hash: QHashBase> QParthProofPublicInputsPreimageWithoutRewardsHash<Hash> {
    pub fn get_combined_preimage(left: &Self, right: &Self, old_node_value: Hash, new_node_value: Hash, level: u8, index: u64, checkpoint_tree_root: Hash, parth_whitelist_root: Hash) -> Self {
        Self {
            index,
            level,
            old_node_value,
            new_node_value,
            checkpoint_tree_root,
            total_guta_proofs_generated: left.total_guta_proofs_generated + right.total_guta_proofs_generated + 1,
            total_user_updates: left.total_user_updates + right.total_user_updates,
            total_fees_paid: left.total_fees_paid + right.total_fees_paid,
            parth_whitelist_root,
        }
    }
    pub fn to_full_preimage(&self, rewards_hash_commitment: Hash) -> QParthProofPublicInputsPreimage<Hash> {
        QParthProofPublicInputsPreimage {
            index: self.index,
            level: self.level,
            old_node_value: self.old_node_value,
            new_node_value: self.new_node_value,
            rewards_hash_commitment,
            checkpoint_tree_root: self.checkpoint_tree_root,
            parth_whitelist_root: self.parth_whitelist_root,
            total_guta_proofs_generated: self.total_guta_proofs_generated,
            total_user_updates: self.total_user_updates,
            total_fees_paid: self.total_fees_paid,
        }
    }
}
