// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZKPublicKeyInfo } from "./ZKPublicKeyInfo";

export type QRegisterUserRPCRequest = { public_key: ZKPublicKeyInfo, };
