[package]
edition = "2021"
name = "qed-cli"
version = "0.1.0"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
qed-utils = { workspace = true }
dotenv = { workspace = true }
qed-interpreter = { workspace = true }
qed-vm = { workspace = true }
thiserror = { workspace = true }
qed-builder = { workspace = true }
qed-sema = { workspace = true }
plonky2 = { workspace = true }
