// AUTOGENERATED - DO NOT MODIFY
use plonky2::plonk::config::{AlgebraicHasher, GenericConfig};
use qed_common_circuit::circuits::lookalikes::{
    get_agg_state_transition_type_d_common_data, get_end_cap_type_e_common_data,
    get_guta_type_c_common_data
};
use qed_crypto::common::generic_circuit_verifier::{
    GenericCircuitCommonDataLibrary, SerializedGenericCircuitCommonDataLibraryInfo,
};

pub fn get_cached_common_data_library<C: GenericConfig<D>, const D: usize>(
) -> GenericCircuitCommonDataLibrary<C, D>
where
    C::Hasher: AlgebraicHasher<C::F>,
{
    let serialized_library =
        serde_json::from_str::<SerializedGenericCircuitCommonDataLibraryInfo>(
            r#"{"common_data_hashes":["52f784e4ab910a348331adad639908a069f5e48e6154676cf5a5c8e383a6679a","f84fc3b771c231ede20191b1bf2a10025e030d4e85978138e1f33f795a09ff24","7ea492b556ffc919706ac50511cadc6c6b3b38afe4810c7b5ef3320652b50f0e"],"common_circuit_list":[[226,12,9,8,11,7,15,13,14,10],[48,1,18,19,32,54,0,227],[6,228]]}"#
        ).unwrap();

    GenericCircuitCommonDataLibrary::<C, D>::from_serialized(
        &serialized_library,
        vec![
            get_guta_type_c_common_data::<C, D>(),
            get_agg_state_transition_type_d_common_data::<C, D>(),
            get_end_cap_type_e_common_data::<C, D>(),
        ],
    )
    .unwrap()
}
