// AUTOGENERATED - DO NOT MODIFY
use plonky2::plonk::config::{AlgebraicHasher, GenericConfig};
use qed_common_circuit::circuits::lookalikes::{
    get_agg_state_transition_type_d_common_data, get_end_cap_type_e_common_data,
    get_guta_type_c_common_data
};
use qed_crypto::common::generic_circuit_verifier::{
    GenericCircuitCommonDataLibrary, SerializedGenericCircuitCommonDataLibraryInfo,
};

pub fn get_cached_common_data_library<C: GenericConfig<D>, const D: usize>(
) -> GenericCircuitCommonDataLibrary<C, D>
where
    C::Hasher: AlgebraicHasher<C::F>,
{
    let serialized_library =
        serde_json::from_str::<SerializedGenericCircuitCommonDataLibraryInfo>(
            r#"{"common_data_hashes":["078f14f90d76c1bd8b6bdb1aaca27fc92cd06cee8c09a9a30064cb03ff204c63","70724c5b671675652c93e738c2ec3296b6366994fae960f747f03c2156720c11","7ea492b556ffc919706ac50511cadc6c6b3b38afe4810c7b5ef3320652b50f0e"],"common_circuit_list":[[11,15,7,226,8,13,14,12,9,10],[48,54,0,18,19,32,1,227],[228,6]]}"#
        ).unwrap();

    GenericCircuitCommonDataLibrary::<C, D>::from_serialized(
        &serialized_library,
        vec![
            get_guta_type_c_common_data::<C, D>(),
            get_agg_state_transition_type_d_common_data::<C, D>(),
            get_end_cap_type_e_common_data::<C, D>(),
        ],
    )
    .unwrap()
}
