[package]
edition = "2021"
name    = "qcircuit_config_db_generator"
version = "0.1.0"


[dependencies]
plonky2 = { workspace = true }
anyhow = { workspace = true }
num = { workspace = true }
unroll = { workspace = true }
serde_json = { workspace = true }
itertools = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
ripemd = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
hashbrown = { workspace = true }
lazy_static = { workspace = true }
qed_crypto           = { path = "../qed_crypto" }
qed_core           = { path = "../qed_core" }
qcircuit_config_db = { path = "../qcircuit_config_db" }
async-trait = { workspace = true }
tracing = { workspace = true }
colored = { workspace = true }

[dev-dependencies]
criterion = "0.5.1"
rand_chacha = "0.3.1"
hex-literal = "0.4.1"
