pub const PQ_COORDINATOR_REGISTER_USER_PUBLIC_KEY_QUEUE_TOPIC_ID: u32 = 1;
pub const PQ_COORDINATOR_DEPLOY_CONTRACT_QUEUE_TOPIC_ID: u32 = 2;
pub const PQ_COORDINATOR_SUBMIT_REALM_GUTA_UPDATE_QUEUE_TOPIC_ID: u32 = 3;

pub const PQ_REALM_SUBMIT_USER_UPDATE_QUEUE_TOPIC_ID: u32 = 32;


pub const PQ_REALM_PROVING_WORK_QUEUE_TOPIC_ID: u32 = 64;
pub const PQ_COORDINATOR_PROVING_WORK_QUEUE_TOPIC_ID: u32 = 65;


