[package]
name = "psy_dev_cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "psy_dev_cli"
path = "src/lib.rs"

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
dotenv = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Psy dependencies
psy_node_utils = { workspace = true }
psy-common = { workspace = true }
psy_core = { workspace = true }
psy_data = { workspace = true }
psy_crypto = { workspace = true }
psy_store = { workspace = true }
psy_node = { workspace = true }
psy_network_circuit = { workspace = true }
psy_common_circuit = { workspace = true }
psy_prover = { workspace = true }
kvq = { workspace = true }
psy_vm = { workspace = true }
psylang_macros = { workspace = true }

# Additional dependencies
fred = { workspace = true }
bincode = { workspace = true }
minijinja = { workspace = true }
jsonrpsee = { workspace = true }
hex = { workspace = true }

# Plonky2
plonky2 = { workspace = true }
parking_lot = { workspace = true}

scheduled-thread-pool = "0.2.7"
num_cpus = "1.17.0"

[[bin]]
name = "psy_dev_cli"
path = "src/main.rs"
