[package]
edition = "2021"
name    = "psy_data"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["std", "parth_core/serialize_rkyv", "parth_core/serialize_speedy", "parth_core/serialize_postcard", "serialize_speedy", "serialize_postcard", "serialize_rkyv", "serialize_bytemuck", "node", "testbed", "rand_gen"]
std = ["parth_core/std", "pser/std", "psy_serialize/std", "psy_io/std"]
serialize_rkyv = ["dep:rkyv","pser/serialize_rkyv", "parth_core/serialize_rkyv"]
serialize_speedy = ["dep:speedy", "pser/serialize_speedy", "parth_core/serialize_speedy", "psy_core/serialize_speedy"]
serialize_postcard = ["dep:postcard", "pser/serialize_postcard", "parth_core/serialize_postcard"]
serialize_bytemuck = ["dep:bytemuck", "parth_core/serialize_bytemuck", "psy_serialize/serialize_bytemuck"]
node = ["serialize_bytemuck", "serialize_speedy", "dep:dashmap"]
rand_gen = []

testbed = []
[dependencies]
postcard = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
anyhow     = { workspace = true }
async-trait      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true}
rand = { workspace = true }
auto_impl = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
ts-rs = { workspace = true }
dashmap = { workspace = true, optional = true }

# start local packages
parth_core = { workspace = true }
parth_common = { workspace = true }
psy_core = { workspace = true }
pser = { workspace = true }
pderive = { workspace = true }
psy_io = { workspace = true }

psy_serialize = { workspace = true }


[dev-dependencies]
criterion = { workspace = true }
speedy = { workspace = true }
bytemuck = { workspace = true }
rkyv = { workspace = true }
parth_core = { workspace = true, features = ["proof_hasher_plonky2_goldilocks"]}


[[bench]]
name = "main"
harness = false
