services:
  pd0:
    image: pingcap/pd:latest
    container_name: tikv-pd0
    network_mode: host
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://127.0.0.1:2379
      - --advertise-peer-urls=http://127.0.0.1:2380
      - --initial-cluster=pd0=http://127.0.0.1:2380,pd1=http://127.0.0.1:2382,pd2=http://127.0.0.1:2384
      - --data-dir=/var/lib/pd
      - --log-file=/var/log/pd.log
    volumes:
      - pd0:/var/lib/pd
      - ./tikv/pd-config8.5.toml:/etc/tikv/pd-config.toml:ro 
    restart: unless-stopped

  pd1:
    image: pingcap/pd:latest
    container_name: tikv-pd1
    network_mode: host
    command:
      - --name=pd1
      - --client-urls=http://0.0.0.0:2381
      - --peer-urls=http://0.0.0.0:2382
      - --advertise-client-urls=http://127.0.0.1:2381
      - --advertise-peer-urls=http://127.0.0.1:2382
      - --initial-cluster=pd0=http://127.0.0.1:2380,pd1=http://127.0.0.1:2382,pd2=http://127.0.0.1:2384
      - --data-dir=/var/lib/pd
      - --log-file=/var/log/pd.log
    volumes:
      - pd1:/var/lib/pd
      - ./tikv/pd-config8.5.toml:/etc/tikv/pd-config.toml:ro 
    restart: unless-stopped

  pd2:
    image: pingcap/pd:latest
    container_name: tikv-pd2
    network_mode: host
    command:
      - --name=pd2
      - --client-urls=http://0.0.0.0:2383
      - --peer-urls=http://0.0.0.0:2384
      - --advertise-client-urls=http://127.0.0.1:2383
      - --advertise-peer-urls=http://127.0.0.1:2384
      - --initial-cluster=pd0=http://127.0.0.1:2380,pd1=http://127.0.0.1:2382,pd2=http://127.0.0.1:2384
      - --data-dir=/var/lib/pd
      - --log-file=/var/log/pd.log
    volumes:
      - pd2:/var/lib/pd
      - ./tikv/pd-config8.5.toml:/etc/tikv/pd-config.toml:ro 
    restart: unless-stopped

  tikv0:
    image: pingcap/tikv:latest
    container_name: tikv-server0
    network_mode: host
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=127.0.0.1:20160
      - --data-dir=/var/lib/tikv
      - --pd-endpoints=127.0.0.1:2379,127.0.0.1:2381,127.0.0.1:2383
      - --log-file=/var/log/tikv.log
      - --config=/etc/tikv/tikv-config.toml 
    volumes:
      - tikv0:/var/lib/tikv
      - ./tikv/tikv-config8.5.toml:/etc/tikv/tikv-config.toml:ro 
    restart: unless-stopped

  tikv1:
    image: pingcap/tikv:latest
    container_name: tikv-server1
    network_mode: host
    command:
      - --addr=0.0.0.0:20161
      - --advertise-addr=127.0.0.1:20161
      - --data-dir=/var/lib/tikv
      - --pd-endpoints=127.0.0.1:2379,127.0.0.1:2381,127.0.0.1:2383
      - --log-file=/var/log/tikv.log
      - --config=/etc/tikv/tikv-config.toml 
    volumes:
      - tikv1:/var/lib/tikv
      - ./tikv/tikv-config8.5.toml:/etc/tikv/tikv-config.toml:ro 
    restart: unless-stopped

  tikv2:
    image: pingcap/tikv:latest
    container_name: tikv-server2
    network_mode: host
    command:
      - --addr=0.0.0.0:20162
      - --advertise-addr=127.0.0.1:20162
      - --data-dir=/var/lib/tikv
      - --pd-endpoints=127.0.0.1:2379,127.0.0.1:2381,127.0.0.1:2383
      - --log-file=/var/log/tikv.log
      - --config=/etc/tikv/tikv-config.toml 
    volumes:
      - tikv2:/var/lib/tikv
      - ./tikv/tikv-config8.5.toml:/etc/tikv/tikv-config.toml:ro 
    restart: unless-stopped

volumes:
  pd0:
  pd1:
  pd2:
  tikv0:
  tikv1:
  tikv2: