[package]
edition = "2021"
name    = "psy-lsp-server"
version = "0.1.0"

[dependencies]
thiserror = { workspace = true }
tower-lsp = {workspace = true}
tokio = {workspace = true}
lsp-types = {workspace = true}

unicode-segmentation = { workspace = true }

psy-sema = { workspace = true }
psy-ast = { workspace = true }
psy-interpreter = { workspace = true }
dargo = { workspace = true }
psy-package = { workspace = true }

psy_vm = { workspace = true }
psy_common = { workspace = true }

[[bin]]
name = "psy-lsp-server"
path = "src/main.rs"
