[package]
edition = "2021"
name    = "qed-parser"
version = "0.1.0"

[dependencies]
qed-ast = { workspace = true }
qed-lexer = { workspace = true }
lalrpop-util = { workspace = true }
qed-common = { workspace = true }
thiserror = { workspace = true }
psy_vm = { workspace = true }
indexmap = { workspace = true }

[build-dependencies]
lalrpop = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
