[package]
edition = "2021"
name    = "qed-utils"
version = "0.1.0"

[dependencies]
clap = { workspace = true }
tracing-subscriber = { workspace = true }

qedlang_core = { workspace = true }
qed_store = { workspace = true }
kvq = { workspace = true }
qed_data = { workspace = true, default-features = false }
qed_core = { workspace = true, default-features = false }
qed_prover = { workspace = true, default-features = false }
qed_common_circuit = { workspace = true }
plonky2 = { workspace = true }
anyhow = { workspace = true }

[features]
default = ["is_sync"]
is_sync = [
    "qed_data/is_sync",
    "qed_store/is_sync",
    "qed_prover/is_sync",
]
