[package]
edition = "2021"
name    = "psy_rust_sdk"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
maybe-async = { workspace = true }
async-trait = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with = { workspace = true }
plonky2 = { workspace = true }
tracing = { workspace = true }
serde_cbor = { workspace = true}
clap = { workspace = true }
ts-rs = { workspace = true }
dashmap = { workspace = true }

kvq = { workspace = true }
psy_common = { workspace = true }
psy_config = { workspace = true }
psy_common_circuit = { workspace = true, default-features = false }
psy_network_circuit = { workspace = true, default-features = false }
psy_vm = { workspace = true, default-features = false }
psy_data = { workspace = true, default-features = false }
psy_crypto = { workspace = true }
psy_store = { workspace = true, default-features = false }

wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
wasm-logger = { workspace = true }
wasm-tracing = { workspace = true }
cfg-if = {workspace = true}
web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen-futures = { workspace = true }
serde-wasm-bindgen = { workspace = true }

k256 = { workspace = true }

rand = { workspace = true }
getrandom = { workspace = true }
hex = {workspace = true}

psy_provider = { workspace = true }
psy_prover = { workspace = true }

# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]

# WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { workspace = true, features = ["json"] }
getrandom = { workspace = true, features = ["js"] }


[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[features]
# default = ["is_sync"]
is_sync = [
    "psy_data/is_sync",
    "maybe-async/is_sync",
    "psy_vm/is_sync",
    "psy_store/is_sync",
    "psy_common_circuit/is_sync",
    "psy_network_circuit/is_sync",
]
