// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QContractTreeLeafHashFRPCRequest = { checkpoint_id: bigint, contract_id: bigint, };
