// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QUserRegistrationTreeMerkleProofFRPCRequest = { checkpoint_id: number, leaf_index: number, };
