// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QWithdrawalTreeLeafHashRPCRequest = { checkpoint_id: bigint, withdrawal_id: number, };
