[package]
edition = "2021"
name    = "psy_dpn_circuit"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maybe-async = { workspace = true }
async-trait = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with = { workspace = true }
plonky2 = { workspace = true }
tracing = { workspace = true }
serde_cbor = { workspace = true}
clap = { workspace = true }
ts-rs = { workspace = true }
dashmap = { workspace = true }

kvq = { workspace = true }
psy_common = { workspace = true }
psy_config = { workspace = true }
psy_common_circuit = { workspace = true, default-features = false }
psy_network_circuit = { workspace = true, default-features = false }
psy_vm = { workspace = true, default-features = false }
psy_data = { workspace = true, default-features = false }
psy_crypto = { workspace = true }
psy_store = { workspace = true, default-features = false }
psylang_macros = { workspace = true }

k256 = { workspace = true }

rand = { workspace = true }
getrandom = { workspace = true }
hex = {workspace = true}

# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
jsonrpsee = { workspace = true }
reqwest = { workspace = true }
sodalite = { workspace = true }
secp256k1 = { workspace = true }
bincode = { workspace = true }
dirs = {workspace = true}
rpassword = { workspace = true }
rayon = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-primitives = { workspace = true }
parking_lot = { workspace = true}
http = { workspace = true }





[features]
# default = ["is_sync"]
is_sync = [
    "psy_data/is_sync",
    "maybe-async/is_sync",
    "psy_vm/is_sync",
    "psy_store/is_sync",
    "psy_common_circuit/is_sync",
    "psy_network_circuit/is_sync",
]
