

pub const MAX_PREPARED_INSERT_BATCH_SIZE: usize = 128usize;
//const MAX_SELECT_SIZE: usize = 128usize;

pub const INSERT_SINGLE_ID_CHECKPOINTED_OBJECT_BATCH_SIZE: usize = 128usize;
pub const INSERT_DOUBLE_ID_CHECKPOINTED_OBJECT_BATCH_SIZE: usize = 128usize;
pub const INSERT_KEY_ID_VALUE_CHECKPOINTED_OBJECT_BATCH_SIZE: usize = 128usize;

pub const SELECT_SINGLE_ID_CHECKPOINTED_OBJECT_BATCH_SIZE: usize = 128usize;
pub const SELECT_DOUBLE_ID_CHECKPOINTED_OBJECT_BATCH_SIZE: usize = 128usize;
pub const SELECT_KEY_ID_VALUE_CHECKPOINTED_OBJECT_BATCH_SIZE: usize = 128usize;


pub const INSERT_HASH_ID_TO_U64_VALUE_BATCH_SIZE: usize = 128usize;