[package]
edition = "2021"
name = "qed_rollup_cli"
version = "0.1.0"

[dependencies]
clap = { workspace = true }
dotenv = { workspace = true }
qed_node = { workspace = true }
qed_core = { workspace = true }
plonky2 = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
qed_rollup_utils = { workspace = true }
tracing = { workspace = true }
