[package]
name = "qed_user_prover"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
qed_core = { workspace = true }
qed_crypto = { workspace = true }
qed_user_cli = { workspace = true }
qed_data = { workspace = true }
qedlang_core = { workspace = true }
qed_rollup_utils = { workspace = true }
plonky2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1"
wasm-logger = "0.2"
wasm-tracing = "2.0"
cfg-if = {workspace = true}
maybe-async = { workspace = true }

# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
jsonrpsee = { workspace = true }

# WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }

[features]
default = ["is_sync"]
is_sync = ["maybe-async/is_sync", "qed_user_cli/is_sync"]
wasm32 = []