[package]
edition = "2021"
name    = "pser"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "serialize_rkyv", "serialize_speedy", "serialize_postcard", "serialize_bytemuck"]
std = []
serialize_rkyv = ["dep:rkyv"]
serialize_speedy = ["dep:speedy", "std"]
serialize_postcard = ["dep:postcard"]
serialize_bytemuck = ["dep:bytemuck"]


[dependencies]
anyhow     = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
bincode = { workspace = true }
speedy = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
postcard = { workspace = true, optional = true }